#!/bin/sh
#
# put a link in the regular path
#
mkdir -p usr/bin
cd usr/bin
cat > lynis <<EOF
#!/bin/sh
cd /usr/versions/lynis
exec ./lynis "\$@"
EOF
chmod a+x lynis
#
# put the man page somewhere man might find it
#
cd ..
mkdir -p share/man/man8
mv versions/lynis/lynis.8 share/man/man8
