#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
mkdir -p usr/bin
cd usr/bin
cat > lynis <<EOF
#!/bin/sh
cd /usr/versions/lynis
exec ./lynis "\$@"
EOF
chmod a+x lynis
cd ../..
#
# put the man page somewhere man might find it
#
mkdir -p usr/share/man/man8
mv usr/versions/lynis/lynis.8 usr/share/man/man8
#
# clean up
#
rm -fr usr/versions/lynis/extras/openbsd
rm -fr usr/versions/lynis/extras/systemd
rm -fr usr/versions/lynis/extras/travis-ci
