#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# put a symlink to palemoon in /usr/bin
#
mkdir -p usr/bin
ln -s /usr/versions/palemoon/palemoon usr/bin
#
# create a desktop file so we populate the menus
#
mkdir -p usr/share/applications
cp ${BUILDROOT}/patches/palemoon.desktop usr/share/applications
