#!/bin/sh
#
# these not only look wrong, they conflict with other packages
#
PYVERS=3.11
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/test
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/tools
