#!/bin/sh
#
# clean up the junk from the checkout
# and add convenience links
#
VERSION=1.4
rm -fr usr/versions/go-${VERSION}/.hg*
rm -fr usr/versions/go-${VERSION}/.git*
rm -fr usr/versions/go-${VERSION}/test
rm -f usr/versions/go-${VERSION}/favicon.ico
rm -f usr/versions/go-${VERSION}/robots.txt
mkdir -p usr/bin
cd usr/bin
ln -s ../versions/go-${VERSION}/bin/* .
