#!/bin/sh
#
# assumes gnu find
#
gsed -i s:find:/usr/gnu/bin/find: usr/share/fish/functions/__fish_print_commands.fish
#
# save the themes
#
cd usr/share/fish/tools/web_config
tar cf themes.tar themes
rm -fr themes
