#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# themes has files whose names contain spaces, so we unpack them
# rather than package them
#
cd "${BASEDIR}/usr/share/fish/tools/web_config" || exit 0
if [ -d themes ]; then
  /usr/bin/rm -fr themes
fi
