#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
PYVERS=3.12
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/* .
#
# duplicate files
#
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/docs
