#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# don't ship docs to save a bit of space
#
rm -fr usr/share/doc

#
# legacy symlinks
#
mkdir -p usr/X11/include
cd usr/X11/include
ln -s ../../include/X11 .
ln -s ../../include/GL .
cd ../../..

#
# add sun extras
#
cp ${BUILDROOT}/patches/sun-ext-protos/* usr/include/X11/extensions

#
# libXvMC 1.0.12 provides this, so we shouldn't in future
#
rm -f usr/include/X11/extensions/vldXvMC.h
#
# now shipped as part of libX11
#
rm -f usr/include/X11/extensions/XKBgeom.h
