#!/bin/sh
#
# put a link in the regular path
#
VERSION=1.5
mv usr/versions/sqlmap-${VERSION} usr/versions/sqlmap
mkdir -p usr/bin
cd usr/bin
cat > sqlmap <<EOF
#!/bin/sh
exec /usr/bin/python3.9 /usr/versions/sqlmap/sqlmap.py "\$@"
EOF
chmod a+x sqlmap
