#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# not for us...
#
rm -fr usr/lib/systemd
#
# we tell it to put things under a /usr prefix, and get ignored
# move it back to where it lived before
#
mv etc usr/etc
