#!/bin/ksh -p

# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}

#
# Copyright 2018 OmniOS Community Edition (OmniOSce) Association.
#

. /usr/lib/brand/shared/common.ksh

trap "fail_incomplete 'Installation interrupted.'" INT

ZONENAME=
ZONEPATH=

while getopts "R:z:" opt; do
    case $opt in
        R)  ZONEPATH="$OPTARG" ;;
        z)  ZONENAME="$OPTARG" ;;
        *)  fail_usage "";;
    esac
done
shift $((OPTIND-1))

if [ -z "$ZONEPATH" -o -z "$ZONENAME" ]; then
    print -u2 "Brand error: No zone path or name."
    exit $ZONE_SUBPROC_USAGE
fi

ZONEROOT=$ZONEPATH/root
# Populates ZONEPATH_DS
get_zonepath_ds $ZONEPATH

# Populate initial structure
(
    set -e
    cd $ZONEPATH

    umask 022
    mkdir root
    cd root
    mkdir -p dev etc usr sbin lib var/run tmp
    chown -R root:sys .
    chmod 1777 tmp
    ln -s usr/bin

cat << EOM > etc/passwd
root:x:0:0:Super-User:/:/sbin/sh
EOM

    grep "^$ZONENAME:" /etc/zones/index | cut -d: -f4 > etc/uuid

) || fail_incomplete "Failed to build miniroot"

exit $ZONE_SUBPROC_OK

# Vim hints
# vim:ts=4:sw=4:et:fdm=marker
