#!/bin/sh
#

#
# need to put the manifest under var for sparse-root zone support
#
mkdir -p var/svc/manifest/network
cp ${BUILDROOT}/patches/kibana.xml var/svc/manifest/network

cd opt/tribblix
#
# Normalize the directory name
#
VERSION="4.5.4-linux-x86"
mv kibana-${VERSION} kibana

#
# need to replace node
#
cd kibana
rm -fr node
ln -s /usr/versions/node-v4 node
