#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add a convenience link
#
exit 0
rm -f usr/versions/python-3.12/bin/aws.cmd
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-3.12/bin/aws .
