#!/bin/sh
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# only ship the 64-bit binaries
#
if [ -d usr/bin/${ARCH64} ]; then
    cd usr/bin/${ARCH64}
    mv * ..
    cd ..
    rmdir ${ARCH64}
    cd ../..
fi
