#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up
#
gunzip usr/share/man/man1/ctwm.1.gz
rm -fr usr/share/doc
mkdir -p usr/etc
cp ${BUILDROOT}/patches/system.ctwmrc usr/etc/system.ctwmrc
rm -fr usr/share/examples
