#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#

#
# explicitly force the python version
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

sed -i 's:/usr/bin/env python3:/usr/bin/python3.12:' usr/bin/${ARCH64}/g-ir-annotation-tool
sed -i 's:/usr/bin/env python3:/usr/bin/python3.12:' usr/bin/${ARCH64}/g-ir-scanner
