#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# local package tweaks below
#

#
# the versions must match those in build.sh
# note also that meson builds get done in a 'build' subdirectory
# this assumes you have a sacrificial copy of these built
# without introspection disabled
#
cp ../pango-1.44.7/build/pango/Pango*gir ${DESTDIR}/usr/share/gir-1.0
cp ../pango-1.44.7/build/pango/Pango*typelib ${DESTDIR}/usr/lib/girepository-1.0
cp ../gdk-pixbuf-2.36.12/gdk-pixbuf/GdkPixbuf-2.0.gir ${DESTDIR}/usr/share/gir-1.0
cp ../gdk-pixbuf-2.36.12/gdk-pixbuf/GdkPixbuf-2.0.typelib ${DESTDIR}/usr/lib/girepository-1.0
cp ../atk-2.38.0/build/atk/Atk-1.0.gir ${DESTDIR}/usr/share/gir-1.0
cp ../atk-2.38.0/build/atk/Atk-1.0.typelib ${DESTDIR}/usr/lib/girepository-1.0
cp ../gtk+-3.24.34/gdk/Gdk*gir ${DESTDIR}/usr/share/gir-1.0
cp ../gtk+-3.24.34/gtk/Gtk-3.0.gir ${DESTDIR}/usr/share/gir-1.0
cp ../gtk+-3.24.34/gdk/Gdk*typelib ${DESTDIR}/usr/lib/girepository-1.0
cp ../gtk+-3.24.34/gtk/Gtk-3.0.typelib ${DESTDIR}/usr/lib/girepository-1.0
