#!/bin/sh
#
# the following only make sense for Linux
#
rm -fr etc/init
rm -fr etc/apparmor.d
#
# default customizations
#
gsed -i 's:#greeter-user=lightdm:greeter-user=gdm:' etc/lightdm/lightdm.conf
gsed -i 's:#greeter-session=example-gtk-gnome:greeter-session=lightdm-gtk-greeter:' etc/lightdm/lightdm.conf
gsed -i 's:#minimum-vt=7:minimum-vt=-1:' etc/lightdm/lightdm.conf
#
# user data lives here, create it to keep lightdm quiet
#
mkdir -p var/lib/lightdm-data
#
# and the greeters need the gdm homedir to exist
#
mkdir -p var/lib/gdm
#
# and the default session wrapper must exist
#
mkdir -p usr/sbin
cat > usr/sbin/lightdm-session <<EOF
#!/bin/sh
exec $1
EOF
chmod a+x usr/sbin/lightdm-session
gsed -i 's:#session-wrapper=lightdm-session:session-wrapper=/usr/sbin/lightdm-session:' etc/lightdm/lightdm.conf
#
# and a method script
#
mkdir -p lib/svc/method
cat > lib/svc/method/svc-lightdm <<EOF
#!/bin/sh
/usr/sbin/lightdm &
exit 0
EOF
chmod a+x lib/svc/method/svc-lightdm
#
# and a manifest
#
mkdir -p lib/svc/manifest/application/x11
cat > lib/svc/manifest/application/x11/lightdm.xml <<EOF
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<!--
	Copyright (c) 2006, 2010, Oracle and/or its affiliates. All rights reserved.

 CDDL HEADER START

 The contents of this file are subject to the terms of the
 Common Development and Distribution License (the "License").
 You may not use this file except in compliance with the License.

 You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 or http://www.opensolaris.org/os/licensing.
 See the License for the specific language governing permissions
 and limitations under the License.

 When distributing Covered Code, include this CDDL HEADER in each
 file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 If applicable, add the following below this CDDL HEADER, with the
 fields enclosed by brackets "[]" replaced with your own identifying
 information: Portions Copyright [yyyy] [name of copyright owner]

 CDDL HEADER END

Service manifest for lightdm.

-->

<service_bundle type='manifest' name='lightdm'>

<service
	name='application/x11/lightdm'
	type='service'
	version='1'>

	<create_default_instance enabled='false' />

	<single_instance />

	<dependency name='fs'
		type='service'
		grouping='require_all'
		restart_on='none'>
		<service_fmri value='svc:/system/filesystem/local' />
	</dependency>

	<dependency name='dbus'
		type='service'
		grouping='require_all'
		restart_on='none'>
		<service_fmri value='svc:/system/dbus' />
	</dependency>

	<dependency name='hal'
		type='service'
		grouping='require_all'
		restart_on='none'>
		<service_fmri value='svc:/system/hal' />
	</dependency>

	<exec_method
		type='method'
		name='start'
		exec='/lib/svc/method/svc-lightdm start'
		timeout_seconds='30'/>

	<exec_method
		type='method'
		name='stop'
		exec=':kill'
		timeout_seconds='30' />

	<stability value='Unstable' />

	<template>
		<common_name>
			<loctext xml:lang='C'>
			LightDM display manager
			</loctext>
		</common_name>
		<documentation>
			<manpage title='lightdm' section='1' manpath='/usr/man' />
		</documentation>
	</template>

</service>

</service_bundle>
EOF
