#!/bin/sh
#
# filenames with spaces
#
mv 'usr/versions/python-3.7/lib/python3.7/site-packages/scipy/io/tests/data/Transparent Busy.ani' usr/versions/python-3.7/lib/python3.7/site-packages/scipy/io/tests/data/TransparentBusy.ani
sed -i 's:Transparent Busy.ani:TransparentBusy.ani:' usr/versions/python-3.7/lib/python3.7/site-packages/scipy/io/tests/test_wavfile.py
