#!/bin/sh
#
# fix up sun-color
#
if [ -d usr/gnu/share/terminfo/s ]; then
    cp /usr/share/lib/terminfo/s/sun-color usr/gnu/share/terminfo/s
fi
#
# get the config file to give the correct --libs
#
gsed -i 's:-L\$libdir:\"-L\$libdir -R\$libdir\":' usr/gnu/bin/ncurses6-config
gsed -i 's:-L\$libdir:\"-L\$libdir -R\$libdir\":' usr/gnu/bin/`isainfo -k`/ncurses6-config
