#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# put aalib-config in the 64-bit directory
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

for mfile in aalib-config
do
    if [ -x usr/bin/${mfile} ]; then
	mkdir -p usr/bin/${ARCH64}
	mv usr/bin/${mfile} usr/bin/${ARCH64}/${mfile}
    fi
done
