#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we do all the installation here
#

#
# there's clearly a problem somewhere, as the download frequently stalls
# about 20% of the way through. Doesn't matter whether it's http or https,
# or wget or curl. But if you keep repeating it will eventually work.
#
mkdir -p usr/share/josm
cd usr/share/josm
curl -O https://josm.openstreetmap.de/josm-tested.jar
cd ../../..

mkdir -p usr/bin
cd usr/bin

#
# different architectures have different versions of java available
# the version here must match the depend file(s)
#

case `uname -p` in
sparc)

cat > josm <<_EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
exec /usr/jdk/instances/jdk17/bin/java -jar /usr/share/josm/josm-tested.jar
_EOF
;;

*)
cat > josm <<_EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
exec /usr/jdk/instances/jdk21/bin/java -jar /usr/share/josm/josm-tested.jar
_EOF
;;

esac

chmod a+x josm
cd ../..

mkdir -p usr/share/applications
cd usr/share/applications
cat > josm.desktop <<_EOF
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=JOSM
Comment=Java OpenStreetMap editor
Exec=josm
Icon=josm
Terminal=false
Type=Application
Categories=Application;
_EOF
cd ../../..

mkdir -p usr/share/pixmaps
cd usr/share/pixmaps
wget https://josm.openstreetmap.de/svn/trunk/images/logo.png
mv logo.png josm.png
cd ../../..
