#!/bin/sh
#
VERSION="3.4"
mkdir -p usr/bin
mkdir -p usr/lib/pkgconfig
cd usr/bin
ln -s ../versions/python-${VERSION}/bin/python3 .
ln -s ../versions/python-${VERSION}/bin/python3-config .
ln -s ../versions/python-${VERSION}/bin/pydoc3 .
ln -s ../versions/python-${VERSION}/bin/pyvenv .
ln -s ../versions/python-${VERSION}/bin/idle3 .
cd ../lib
ln -s ../versions/python-${VERSION}/lib/libpython3* .
cd pkgconfig
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python-3.3.pc .
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python3.pc .
cd ../../versions/python-${VERSION}/lib/python${VERSION}/site-packages
tar cf setuptools.tar setuptools
rm -fr setuptools
