#!/bin/sh
#
# create a versioned directory
# put a symlink to firefox in /usr/bin
#
VERSION=45.8.0esr
mkdir -p usr/bin
cd usr/bin
rm -f firefox
ln -s /usr/versions/ff-${VERSION}/bin/firefox .
cd ../..
rm -fr usr/versions/ff-${VERSION}/include
rm -fr usr/versions/ff-${VERSION}/lib/sdk
#
# create a desktop file so we populate the menus
#
mkdir -p usr/share/applications
cp ${BUILDROOT}/patches/browser.desktop usr/share/applications
#
# NOTE: we currently disable updates at build time
# disable autoupdate - see
# https://support.mozilla.org/en-US/questions/944982
#
#cd usr/versions/ff-${VERSION}
#cat > lib/defaults/pref/local-settings.js <<EOF
#pref("general.config.obscure_value", 0);
#pref("general.config.filename", "mozilla.cfg");
#EOF
#cat > mozilla.cfg <<EOF
#lockPref("app.update.auto", false);
#lockPref("app.update.enabled", false);
#lockPref("security.tls.version.min", 1);
#EOF
