#!/bin/sh
#
# fixinstall.64 saved the 64-bit ffi.h for us, now
# we wrap it
#
mv usr/include/SDL2/SDL_config.h usr/include/SDL2/SDL_config-32.h
cp ${BUILDROOT}/patches/SDL_config.h usr/include/SDL2/SDL_config.h
