#!/bin/sh
#

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

rm -f usr/lib/lib*.la
rm -f usr/lib/*/lib*.la

#
# copy the existing libraries for compat
# libgnutlsxx retains its old SONAME, so no need to copy that
# libgnutls-openssl is no longer shipped, and I can find no
# consumers, so no need to copy that either
#
# these come from the 3.3.30 version of the package
#
cp -p /usr/lib/libgnutls.so.28.43.4 usr/lib/libgnutls.so.28.43.4
cp -p /usr/lib/${ARCH64}/libgnutls.so.28.43.4 usr/lib/${ARCH64}/libgnutls.so.28.43.4
cd usr/lib
ln -s libgnutls.so.28.43.4 libgnutls.so.28
cd ${ARCH64}
ln -s libgnutls.so.28.43.4 libgnutls.so.28
