#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
SAVEDIR=`pwd`
TGDIR=tmp-build.$$
mkdir $TGDIR
cd $TGDIR
# unpack the zip file
$THOME/build/unpack JuliaMono-ttf
#
mkdir -p ${DESTDIR}/usr/share/fonts/TrueType/juliamono
mkdir -p ${DESTDIR}/etc/X11/fontpath.d
ln -s ../../../usr/share/fonts/TrueType/juliamono ${DESTDIR}/etc/X11/fontpath.d/juliamono:pri
cp *ttf ${DESTDIR}/usr/share/fonts/TrueType/juliamono
cd ${DESTDIR}/usr/share/fonts/TrueType/juliamono
mkfontscale .
ln fonts.scale fonts.dir
cd $SAVEDIR
rm -fr $TGDIR
