#!/bin/sh
#
# The original solaris had ssh split into 3 packages
# We replicate the split here
#

mv usr .usr

mkdir -p usr/lib/ssh
mkdir -p usr/share/man/man8

mv .usr/lib/ssh/ssh-keysign usr/lib/ssh/ssh-keysign
mv .usr/share/man/man8/ssh-keysign.8 usr/share/man/man8/ssh-keysign.8

rm -fr .usr var etc
