#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# don't ship the update-pciids script; the way to update
# the file is via packaging
#
rm -f usr/share/man/man8/update-pciids.8
rm -f usr/sbin/update-pciids
