#!/bin/sh
#
# Only LTS releases have standard symlinks
#
VERSION=5
#mkdir -p usr/bin
#ln -s ../versions/node-v${VERSION}/bin/node usr/bin/node
#ln -s ../versions/node-v${VERSION}/bin/npm usr/bin/npm
#
# dubious files in 5.6.0
#
find usr/versions/node-v5/lib/node_modules/npm/node_modules -name '*~*' -exec rm {} \;
find usr/versions/node-v5/lib/node_modules/npm/node_modules -name '.*~*' -exec rm {} \;
