#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# have a slightly more relevant config
#
cp ${BUILDROOT}/patches/system.qvwmrc usr/share/qvwm/system.qvwmrc
#cp ${BUILDROOT}/patches/default.qvwm-theme usr/share/qvwm/default.qvwm-theme
#
# these copied from other apps, sometimes converted from png to xpm
#
cp ${BUILDROOT}/patches/qvwm-pixmaps/* usr/share/qvwm/images
#
# fix manpage section
# yes, it's in /usr/man at this point, the default fixit
# will correct that for us
#
sed -i 's: 1x : 1 :' usr/man/man1/qvwm.1x
mv usr/man/man1/qvwm.1x usr/man/man1/qvwm.1
