#!/bin/sh
#
# put command in the default path
#
VERSION=2.6
mkdir -p usr/bin usr/share/man/man8
gunzip usr/versions/ruby-${VERSION}/share/man/man8/facter.8.gz
ln -s ../../usr/versions/ruby-${VERSION}/bin/facter usr/bin/facter
ln -s ../../../../usr/versions/ruby-${VERSION}/share/man/man8/facter.8 usr/share/man/man8
