#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#

#
# Copyright 2025 Peter Tribble
#

prompt=${1//_/__} 
exec /usr/bin/zenity --entry --title "ssh-askpass" \
     --text="$prompt" --hide-text \
     --window-icon=/usr/share/pixmaps/ssh-askpass-zenity.png
