#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# wrapper to start activemq
#
cd /opt/tribblix/activemq/bin
ACTIVEMQ_BASE=/var/activemq
export ACTIVEMQ_BASE
case `uname -p` in
    sparc)
	JAVA_HOME=/usr/jdk/instances/jdk17
	export JAVA_HOME
	;;
    *)
	JAVA_HOME=/usr/jdk/instances/jdk21
	export JAVA_HOME
	;;
esac

bash ./activemq $1
