#!/bin/sh
#
# just name off the primary version
#
VERSION=6.0.44
cd usr/versions
ln -s apache-tomcat-${VERSION} tomcat6
chmod a+x apache-tomcat-${VERSION}/bin/*.sh
rm apache-tomcat-${VERSION}/bin/*.bat
