#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION=1.14
rm -f usr/versions/subversion-${VERSION}/lib/lib*.a
rm -f usr/versions/subversion-${VERSION}/lib/lib*.la
rm -f usr/versions/subversion-${VERSION}/lib/apr-util-1/*.a
rm -f usr/versions/subversion-${VERSION}/lib/apr-util-1/*.la
# make this version the default
mkdir -p usr/bin
cd usr/bin
ln -s ../versions/subversion-${VERSION}/bin/svn* .
