#!/bin/sh
#
# Images has files whose names contain spaces, so we unpack them
# rather than package them
#
VERSION=1.11.12
cd ${BASEDIR}/usr/versions/freeplane-${VERSION}/doc
if [ -f Images.tar ]; then
  /usr/bin/tar xf Images.tar
  /usr/bin/chown -hR root:root Images
  /usr/bin/chmod -R a+rX Images
fi
