#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Images has files whose names contain spaces, so we unpack them
# rather than package them
#
VERSION=1.12.11
cd "${BASEDIR}/usr/versions/freeplane-${VERSION}/doc" || exit 0
if [ -f Images.tar ]; then
  /usr/bin/tar xf Images.tar
  /usr/bin/chown -hR root:root Images
  /usr/bin/chmod -R a+rX Images
fi
