#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Images has files whose names contain spaces, so we unpack them
# rather than package them
#
VERSION=1.12.8
cd ${BASEDIR}/usr/versions/freeplane-${VERSION}/doc
if [ -d Images ]; then
  /usr/bin/rm -fr Images
fi
