#!/bin/ksh
#
# autodepend - automatically generate dependency files
#
# do not just use the output untouched; at least scan it for obvious
# errors and omissions (including the package the target itself is in)
# this is just to help and minimise typing rather than being authoritative
#
# Dependencies on the following are considered fundamental and should
# not normally be recorded for applications
#   TRIBsys-library TRIBsys-lib-math TRIBgcc4runtime SUNWcs
#
# assumes a shared object
#

case $1 in
    -l)
	STYLE=recurse
	shift
	;;
esac

case $# in
0)
	echo "Usage: $0 [-l] target [...]"
	exit 1
	;;
esac

if [ ! -e $1 ]; then
   echo "$1 not found"
   exit 1
fi

#
# for simple cases like this, gnu grep is several times quicker
#
EGREP=/usr/bin/egrep
if [ -x /usr/gnu/bin/egrep ]; then
   EGREP=/usr/gnu/bin/egrep
fi

#
# find shared objects
# look for library followed by a space (the actual file) or 
# by =, which is for a symlink
#
getdeps()
{
for dep in `/usr/bin/dump -Lv $* 2>/dev/null| $EGREP NEEDED | awk '{print $NF}' | sort | uniq | sed 's:\+:\\\\+:g'`
do
  $EGREP "lib/$dep( |=)" /var/sadm/install/contents
done
}

#
# find shared objects
# look for library followed by a space (the actual file) or 
# by =, which is for a symlink
#
getlongdeps()
{
for dep in `/usr/bin/ldd $* 2>/dev/null| $EGREP / | awk '{print $1}' | sort | uniq | sed 's:\+:\\\\+:g'`
do
  $EGREP "lib/$dep( |=)" /var/sadm/install/contents
done
}

case $STYLE in
    'recurse')
	getlongdeps $* | awk '{print "P "$NF}'|sort|uniq| $EGREP -v '^P (TRIBsys-library|TRIBsys-lib-math|TRIBgcc4runtime|SUNWcs|TRIBpkgsrc|TRIBpkgsrc64|TRIBv-thunderbird-45|TRIBv-thunderbird-52|TRIBv-firefox-52|TRIBv-browser-45|TRIBv-browser-52)$'
	exit 0
	;;
esac

getdeps $* | awk '{print "P "$NF}'|sort|uniq| $EGREP -v '^P (TRIBsys-library|TRIBsys-lib-math|TRIBgcc4runtime|SUNWcs|TRIBpkgsrc|TRIBpkgsrc64|TRIBv-thunderbird-45|TRIBv-thunderbird-52|TRIBv-firefox-52|TRIBv-browser-45|TRIBv-browser-52)$'
