#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# lists packages that don't have ZAP_URL set
# also checks that build scripts exist (even as a no-op, they should echo
# why they aren't needed for a package)
#

for PKGI in */pkginfo
do
    PKG=${PKGI%/*}
    PKGHOME=$(/usr/bin/grep '^ZAP_URL' "${PKGI}")
    if [ -z "${PKGHOME}" ]; then
	echo "$PKG does not have ZAP_URL set"
    fi
    if [ ! -x "${PKG}/build.sh" ]; then
	echo "$PKG does not have a build script"
    fi
done
