#!/bin/ksh
#
# check validity of the package names for the given overlay(s)
#

THOME=${THOME:-/packages/localsrc/Tribblix}
#
# xref against this illumos version
#
ILVER=m32
PILVER=32
PKGDIR=${THOME}/pkgs
ARCH="i386"
case $(pwd) in
    *lx)
	ILVER=m32lx
	PILVER=32lx
	;;
    *sparc)
	ILVER=m28.sparc
	PILVER=28
	PKGDIR=${THOME}/pkgs.sparc
	ARCH="sparc"
	;;
esac
IPKGDIR=${THOME}/illumos-pkgs-${ILVER}/pkgs

case $1 in
-a)
    # look for all overlays
    for pkg in *.pkgs
    do
	$0 "${pkg%.pkgs}"
    done
    exit 0
    ;;
-f)
    # useful for overlays.iso
    if [ -f "$2" ]; then
	for pkg in $(<"$2")
	do
	    $0 "$pkg"
	done
    else
	echo "Missing file $2"
    fi
    exit 0
    ;;
esac

case $# in
1)
	OVL="$1"
	;;
*)
	echo "Usage: $0 -a|overlay|-f listfile"
	exit 1
	;;
esac
if [ ! -f "${OVL}.pkgs" ]; then
    echo "ERROR: unable to find overlay $OVL"
    exit 1
fi
for PKGI in $(grep -E -v '^(TRIBrelease-name|TRIBzap|TRIBzap-upgrade)$' "${OVL}.pkgs")
do
  if [ ! -d "${THOME}/build/${PKGI}" ]; then
      if [ ! -f "${IPKGDIR}/${PKGI}.0.${PILVER}.zap" ]; then
	  if [ "${ARCH}" = "sparc" ]; then
	      case $PKGI in
		  SUNW?fb*|SUNWm64*|SUNWopenxsun*|SUNWbge)
		      :
		      ;;
		  *)
		      echo "ERROR: invalid package $PKGI"
		      ;;
	      esac
	  else
	      echo "ERROR: invalid package $PKGI"
	  fi
      fi
  else
      # error if marked for a different arch
      if [ -f "${THOME}/build/${PKGI}/arch.txt" ]; then
	  NARCH=$(<"${THOME}/build/${PKGI}/arch.tx"t)
	  if [ "$NARCH" != "$ARCH" ]; then
	      echo "ERROR: $PKGI is only valid for $NARCH"
	  fi
      fi
      # use a per-arch version if present
      if [ -f "${THOME}/build/${PKGI}/version.$ARCH" ]; then
	  PKGVERS=$(<"${THOME}/build/${PKGI}/version.$ARCH")
      else
	  while read -r line
	  do
	      case $line in
		  VERSION=*)
		      PKGVERS=${line#*=}
		      ;;
	      esac
	  done < "${THOME}/build/${PKGI}/pkginfo"
	  PKGVERS=${PKGVERS//\"/}
      fi
      if [ ! -f "${PKGDIR}/${PKGI}.${PKGVERS}.zap" ]; then
	  echo "ERROR: missing package $PKGI"
      fi
  fi
done
