#!/bin/ksh
#
# catalog format is
#  name|version|dependencies
#
for PKGI in */pkginfo
do
  PKG=${PKGI%/*}
  PKGVERS=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
  DEPLIST=""
  if [ -f ${PKG}/depend ]; then
     DEPLIST=`awk '{printf("%s ", $2)}' ${PKG}/depend`
  fi
  echo "${PKG}|${PKGVERS}|${DEPLIST}|" | sed 's: |:|:'
done
