#!/bin/sh
#
# alias catalog format is
#  alias|pkgname
#
# this script is useful for a manually maintained catalog, like sparc,
# or a previous release
#

PKGDIR="../pkgs"
CATNAME="catalog"
#
# flags
# -p platform (ie sparc)
# -c catalog_filename
#
while getopts "p:c:" opt; do
    case $opt in
    p)
	PLAT="$OPTARG"
	PKGDIR="${PKGDIR}.${PLAT}"
	;;
    c)
	CATNAME="$OPTARG"
	;;
    esac
done
shift $((OPTIND-1))

CFILE="${PKGDIR}/${CATNAME}"

if [ ! -f $CFILE ]; then
    echo "ERROR: $CFILE not found"
    exit 1
fi

#
# assume we're in the build directory
#
for PKG in $(awk -F'|' '{print $1}' $CFILE)
do
    PKGI=${PKG}/alias
    if [ -f ${PKGI}.${PLAT} ]; then	    
	for PALIAS in $(<${PKGI}.${PLAT})
	do
	    echo "${PALIAS}|${PKG}"
	done
    elif [ -f $PKGI ]; then	    
	for PALIAS in $(<${PKGI})
	do
	    echo "${PALIAS}|${PKG}"
	done
    fi
done
