#!/bin/ksh
#
# catalog format is
#  name|version|dependencies
#
PKGDIR=/packages/localsrc/Tribblix/oi-pkgs-0.8/pkgs.repo
PKGVERS="0.8o"
case $# in
1)
	PKGVERS="$1"
	;;
esac

#
# FIXME get dependencies out of the package
#
DEPLIST=""
cd $PKGDIR
for PKGI in *.zap
do
  PKG=${PKGI%.${PKGVERS}.zap}
  echo "${PKG}|${PKGVERS}|${DEPLIST}|" | sed 's: |:|:'
done
