#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# alias catalog format is
#  alias|name
#
THOME=${THOME:-/packages/localsrc/Tribblix}
PKGDIR=${THOME}/illumos-pkgs-m33/pkgs

case $# in
1)
	PKGDIR=$1
	;;
esac

#
cd "$PKGDIR" || exit 1
for ZPKG in *.zap
do
  PNAME=${ZPKG%%.*}
  ANAME=${PNAME#TRIB}
  echo "${ANAME}|${PNAME}"
case $ANAME in
net-*)
  XNAME=${ANAME#net-}
  echo "${XNAME}|${PNAME}"
  ;;
esac
done
