#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# like the catalog, but neatly formatted as html
#
RELVER=m36.1
THOME=${THOME:-/packages/localsrc/Tribblix}
PKGDIR=${THOME}/illumos-pkgs-${RELVER}/pkgs

case $# in
1)
	PKGDIR=$1
	;;
esac

#
# try and work out if we're sparc
#
SSUFFIX=""
case $PKGDIR in
    *.sparc*)
	SSUFFIX=".sparc"
	;;
esac

#
# try and work out the version number
#
NPKGDIR=${PKGDIR%/pkgs}
NPKGDIR=${NPKGDIR%.sparc}
RELVER=$(echo "$NPKGDIR"|awk -F- '{print $NF}')
RELNUM=${RELVER/m/}

#
# updates and variants share the same Tribblix release
#
TRELVER=${RELVER%.*}
TRELVER=${TRELVER%lx}

cat <<EOF
<html>
<Head><title>Tribblix package catalog</title></head>
<body>
<h1>illumos packages for Tribblix</h1>
<dl>
EOF


#
# prefer zap as we can get dependencies, and it's quicker
#
cd "$PKGDIR" || exit 1
for ZPKG in *.zap
do
  DEPLIST=""
  PKG=${ZPKG%.zap}
  PNAME=${ZPKG%%.*}
  PKGVERS=${PKG#*.}
  PKGNAME=$(unzip -p "$ZPKG" "${PNAME}/pkginfo" 2>/dev/null | awk -F= '{if ($1 == "NAME") print $NF}')
  if [ -f catalog ]; then
      DEPLIST=$(grep "^${PKG}|" catalog |awk -F'|' '{print $3}')
  else
      DEPLIST=$(unzip -p "$ZPKG" "${PNAME}/install/depend" 2>/dev/null | grep '^P' | awk '{printf("%s ", $2)}')
  fi
  FMRI=$(unzip -p "$ZPKG" "${PNAME}/pkginfo" 2>/dev/null | grep '^IPS_FMRI' | awk -F'[=@]' '{print $2}')
  echo "<dt><a name=\"${PNAME}\"></a><b>${PNAME}</b></dt>"
  echo "<dd>\n${PKGNAME}\n<ul>\n<li>Version: ${PKGVERS}</li>"
  FMRI=${FMRI/pkg:\/\/on-nightly\//}
  FMRI=${FMRI/pkg:\/\/omnios\//}
  echo "<li>IPS name: ${FMRI}</li>"
  for mypkgdep in $DEPLIST
  do
      if [ -f "${mypkgdep}.0.${RELNUM}.zap" ]; then
	  echo "<li>Requires: <a href=\"#${mypkgdep}\">$mypkgdep</a></li>"
      elif [ -d "${THOME}/build/${mypkgdep}" ]; then
	  echo "<li>Requires: <a href=\"../tribblix-${TRELVER}${SSUFFIX}/#${mypkgdep}\">$mypkgdep</a></li>"
      else
	  echo "<li>Requires: $mypkgdep</li>"
      fi
  done
  echo "</ul></dd>"
done

cat <<EOF
</dl>
<hr>
<p><a href="http://www.tribblix.org/">Tribblix</a></p>
</body>
</html>
EOF
