#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# like the catalog, but neatly formatted as html
#
# derived from the catalog, so can be used for repos that
# aren't up to date with the build tree
#

case $# in
1)
    CATALOG=$1
    ;;
*)
    echo "Usage: $0 catalog-file"
    exit 1
    ;;
esac

if [ ! -f "$CATALOG" ]; then
    echo "Cannot find $CATALOG"
    exit 1
fi

cat <<EOF
<html>
<Head><title>Tribblix package catalog</title></head>
<body>
<h1>Tribblix packages</h1>
<dl>
EOF

while read -r line
do
  #pick first field
  PKG=${line%%\|*}
  #strip off a field
  rline=${line#*\|}
  #pick the second field
  PKGVERS=${rline%%\|*}
  #strip off another field
  rline=${rline#*\|}
  #pick the third field
  DEPLIST=${rline%%\|*}
  PKGI=${PKG}/pkginfo
  if [ -f "${PKGI}" ]; then
    PKGNAME=""
    PKGHOME=""
    while read -r line
    do
	case $line in
	    NAME=*)
		PKGNAME=${line#*=}
		;;
	    ZAP_URL=*)
		PKGHOME=${line#*=}
		;;
	esac
    done < "${PKGI}"
    PKGNAME=${PKGNAME//\"/}
    PKGHOME=${PKGHOME//\"/}
    echo "<dt><a name=\"${PKG}\"></a><b>${PKG}</b></dt>"
    echo "<dd>"
    echo "${PKGNAME}"
    if [ -n "${PKGHOME}" ]; then
	echo " [<a href=\"${PKGHOME}\">Home</a>]"
    fi
    echo "<ul>"
    echo "<li>Version: ${PKGVERS}</li>"
    for mydep in $DEPLIST
    do
        if [ -d "$mydep" ]; then
	    echo "<li>Requires: <a href=\"#${mydep}\">$mydep</a></li>"
        else
	    echo "<li>Requires: $mydep</li>"
        fi
    done
    echo "</ul>"
    echo "</dd>"
  fi
done < "$CATALOG"

cat <<EOF
</dl>
<hr>
<p><a href="http://www.tribblix.org/">Tribblix</a></p>
</body>
</html>
EOF
