#!/bin/ksh
#
# like the catalog, but neatly formatted as html
#
# derived from the catalog, so can be used for repos that
# aren't up to date with the build tree
#

case $# in
1)
    CATALOG=$1
    ;;
*)
    echo "Usage: $0 catalog-file"
    exit 1
    ;;
esac

if [ ! -f "$CATALOG" ]; then
    echo "Cannot find $CATALOG"
    exit 1
fi

cat <<EOF
<html>
<Head><title>Tribblix package catalog</title></head>
<body>
<h1>Tribblix packages</h1>
<dl>
EOF

while read line
do
  #pick first field
  PKG=${line%%\|*}
  #strip off a field
  rline=${line#*\|}
  #pick the second field
  PKGVERS=${rline%%\|*}
  #strip off another field
  rline=${rline#*\|}
  #pick the third field
  DEPLIST=${rline%%\|*}
  #strip off two fields
  rline=${rline#*\|}
  rline=${rline#*\|}
  #pick the 5th field
  PKGCKSUM=${rline%%\|*}
  PKGI=${PKG}/pkginfo
  if [ -f ${PKGI} ]; then
    PKGNAME=""
    PKGHOME=""
    while read line
    do
	case $line in
	    NAME=*)
		PKGNAME=${line#*=}
		;;
	    ZAP_URL=*)
		PKGHOME=${line#*=}
		;;
	esac
    done < ${PKGI}
    PKGNAME=${PKGNAME//\"/}
    PKGHOME=${PKGHOME//\"/}
    echo "<dt><a name=\"${PKG}\"></a><b>${PKG}</b></dt>"
    echo "<dd>"
    echo "${PKGNAME}"
    if [ -n "${PKGHOME}" ]; then
	echo " [<a href=\"${PKGHOME}\">Home</a>]"
    fi
    echo "<ul>"
    echo "<li>Version: ${PKGVERS}</li>"
    echo "<li><a href=\"${PKG}.${PKGVERS}.zap\">Download</a> [MD5: ${PKGCKSUM}]</li>"
    for mydep in $DEPLIST
    do
        if [ -d $mydep ]; then
	    echo "<li>Requires: <a href=\"#${mydep}\">$mydep</a></li>"
        else
	    echo "<li>Requires: $mydep</li>"
        fi
    done
    echo "</ul>"
    echo "</dd>"
  fi
done < $CATALOG

cat <<EOF
</dl>
<hr>
<p><a href="http://www.tribblix.org/">Tribblix</a></p>
</body>
</html>
EOF
