#!/bin/ksh
#
# catalog format is
#  name|version|dependencies|size|md5|
#
PKGDIR=/packages/localsrc/Tribblix/illumos-pkgs-m14/pkgs

case $# in
1)
	PKGDIR=$1
	;;
esac

cat <<EOF
<html>
<Head><title>Tribblix package catalog</title></head>
<body>
<h1>Illumos packages for Tribblix</h1>
<dl>
EOF


#
# prefer zap as we can get dependencies, and it's quicker
#
cd $PKGDIR
for PKGI in *.pkg
do
  DEPLIST=""
  PKG=${PKGI%.pkg}
  ZPKG=${PKG}.zap
  PNAME=${PKGI%%.*}
  if [ -f $ZPKG ]; then
    PKGVERS=`bash zipgrep '^VERSION=' $ZPKG ${PNAME}/pkginfo 2>/dev/null| awk -F= '{print $NF}'`
    PKGNAME=`bash zipgrep '^NAME=' $ZPKG ${PNAME}/pkginfo 2>/dev/null| awk -F= '{print $NF}'`
    DEPLIST=`bash zipgrep '^P' $ZPKG ${PNAME}/install/depend 2>/dev/null |awk '{printf("%s ", $2)}'`
  else
    PKGVERS=`pkginfo -l -d ${PKGI} | grep VERSION: | awk '{print $NF}' | sed 's="==g'`
  fi
  echo "<dt><a name=\"${PNAME}\"></a><b>${PNAME}</b></dt>"
  echo "<dd>"
  echo "${PKGNAME}"
  echo "<ul>"
  echo "<li>Version: ${PKGVERS}</li>"
  echo "<li><a href=\"${PNAME}.${PKGVERS}.zap\">Download</a></li>"
  for mypkgdep in $DEPLIST
  do
      mydep=`/bin/ls -1d ${mypkgdep}.*.zap 2>/dev/null`
      if [ -f $mydep ]; then
	  echo "<li>Requires: <a href=\"#${mypkgdep}\">$mypkgdep</a></li>"
      else
	  echo "<li>Requires: $mypkgdep</li>"
      fi
  done
  echo "</ul>"
  echo "</dd>"
done

cat <<EOF
</dl>
<hr>
<p><a href="http://www.tribblix.org/">Tribblix</a></p>
</body>
</html>
EOF
