#!/bin/ksh
#
# given an existing pkg, convert it into the proper zap file
#
# this is for when something else has already provided an SVR4 package
# in datastream format and we're just importing it
#
case $# in
3)
	PKGNAME="$1"
	BFILE="$2"
	BROOT="$3"
	;;
2)
	PKGNAME="$1"
	BFILE="$2"
	BROOT="/tmp/pct"
	;;
*)
	echo "Usage: $0 pkg_name tmp_dir [output_root]"
	exit 1
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"

#
# sanity check
#
if [ ! -d $BUILD ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi
if [ ! -d $BROOT ]; then
   mkdir -p ${BROOT}
fi
if [ ! -d $BROOT ]; then
   echo "ERROR: unable to find temporary directory $BROOT"
   exit 1
fi
if [ ! -f ${BUILD}/${PKGNAME}/pkginfo ]; then
   echo "ERROR: missing package data"
   echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
   exit 1
fi
if [ ! -f $BFILE ]; then
   echo "ERROR: unable to find input package $BFILE"
   exit 1
fi

PKGVER=`/usr/bin/grep '^VERSION=' ${BUILD}/${PKGNAME}/pkginfo | /usr/bin/awk -F= '{print $2}' | /usr/bin/sed 's:"::g'`

# copy the existing package file to one with the right name
cp ${BFILE}  ${BROOT}/${PKGNAME}.${PKGVER}.pkg
pkgtrans ${BROOT}/${PKGNAME}.${PKGVER}.pkg ${BROOT} ${PKGNAME}
# create the zap file
cd $BROOT
# 7z gives us an extra 2-3% reduction in file size
#zip -9 -q -r ${PKGNAME} ${PKGNAME}
rm -f ${PKGNAME}.${PKGVER}.zap ${PKGNAME}.${PKGVER}.zap.md5 ${PKGNAME}.${PKGVER}.zap.sig
7za a -tzip -mx=9 -mfb=256 ${PKGNAME}.${PKGVER}.zap ${PKGNAME}
chmod a+r ${PKGNAME}.${PKGVER}.zap
cd /
# pregenerate the md5 checksum ready for catalog creation
openssl md5 ${BROOT}/${PKGNAME}.${PKGVER}.zap| /usr/bin/awk '{print $NF}' > ${BROOT}/${PKGNAME}.${PKGVER}.zap.md5
# if the passphrase file exists, sign the package
# otherwise, it will have to be signed manually
if [ -f ${HOME}/Tribblix/Sign.phrase ]; then
    echo ""
    echo "Signing package."
    echo ""
    gpg --detach-sign --no-secmem-warning --passphrase-file ${HOME}/Tribblix/Sign.phrase ${BROOT}/${PKGNAME}.${PKGVER}.zap
    if [ -f ${BROOT}/${PKGNAME}.${PKGVER}.zap.sig ]; then
	echo "Package signed successfully."
	echo ""
    fi
fi
ls -lh ${BROOT}/${PKGNAME}.${PKGVER}.pkg
ls -lh ${BROOT}/${PKGNAME}.${PKGVER}.zap
rm -fr ${BROOT}/${PKGNAME}
