#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# catalog format is
#  name|version|dependencies|size|md5|
#
THOME=${THOME:-/packages/localsrc/Tribblix}
PKGDIR=${THOME}/opensxce-2014
case $# in
1)
	PKGDIR=$1
	;;
esac

#
# prefer zap as we can get dependencies, and it's quicker
#
cd "$PKGDIR" || exit 1
for ZPKG in *.zap
do
  DEPLIST=""
  PNAME=${ZPKG%%.*}
  PF=${ZPKG%.zap}
  PKGVERS=${PF#*.}
  if [ -x /usr/bin/stat ]; then
    PKGSIZE=$(/usr/bin/stat --printf="%s" "${ZPKG}")
  else
    PKGSIZE=$(/bin/ls -l "${ZPKG}" | /usr/bin/awk '{print $5}')
  fi
  if [ "${ZPKG}.md5" -nt "${ZPKG}" ]; then
    PKGMD5=$(<"${ZPKG}.md5")
  else
    PKGMD5=$(openssl md5 "${ZPKG}" | /usr/bin/awk '{print $NF}')
    /bin/rm -f "${ZPKG}.md5"
    echo "$PKGMD5" > "${ZPKG}.md5"
  fi
  DEPLIST=$(unzip -p "$ZPKG" "${PNAME}/install/depend" 2>/dev/null | awk '{if ($1 == "P") printf("%s ", $2)}')
  DEPLIST=${DEPLIST%% }
  echo "${PNAME}|${PKGVERS}|${DEPLIST}|${PKGSIZE}|${PKGMD5}|"
done
