#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# wrapper to build the catalog, index, alias, and list
# files for an illumos repo
#

case $# in
1)
	TARGET="$1"
	;;
*)
	echo "Usage: $0 target_dir"
	exit 1
	;;
esac

if [ ! -d "$TARGET" ]; then
   echo "Cannot find target directory $TARGET"
   exit 1
fi

TESTFILE=$(/bin/ls -1 "${TARGET}"/SUNWcs.*.zap)
if [ ! -f "$TESTFILE" ]; then
   echo "Unable to find any packages in $TARGET"
   exit 1
fi

if [ ! -f "${TESTFILE}.sig" ]; then
   echo "Signing packages"
   ./sign-directory "$TARGET"
fi

echo "Creating catalog"
./create-illumos-catalog "$TARGET" > "$TARGET/catalog"

echo "Creating index.html"
./create-illumos-catalog-html "$TARGET" > "$TARGET/index.html"

echo "Creating aliases"
./create-illumos-aliases "$TARGET" > "$TARGET/aliases"

echo "Creating file list"
./create-file-list "$TARGET"
