#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# convert an svr4 package (in datastream format) into zap format
#
# this is for when something else has already provided an SVR4 package
# in datastream format and we're just importing it
#
case $# in
3)
	PKGNAME="$1"
	BFILE="$2"
	BROOT="$3"
	;;
2)
	PKGNAME="$1"
	BFILE="$2"
	BROOT="/tmp/pct"
	;;
*)
	echo "Usage: $0 pkg_name tmp_dir [output_root]"
	exit 1
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"

#
# sanity check
#
if [ ! -d "$BUILD" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi
if [ ! -d "$BROOT" ]; then
   mkdir -p "${BROOT}"
fi
if [ ! -d "$BROOT" ]; then
   echo "ERROR: unable to find temporary directory $BROOT"
   exit 1
fi
if [ ! -f "${BUILD}/${PKGNAME}/pkginfo" ]; then
   echo "ERROR: missing package data"
   echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
   exit 1
fi
if [ ! -f "$BFILE" ]; then
   echo "ERROR: unable to find input package $BFILE"
   exit 1
fi

PKGVER=$(/usr/bin/grep '^VERSION=' "${BUILD}/${PKGNAME}/pkginfo" | /usr/bin/awk -F= '{print $2}' | /usr/bin/sed 's:"::g')

# copy the existing package file to one with the right name
PNAME="${PKGNAME}.${PKGVER}"
cp "${BFILE}" "${BROOT}/${PNAME}.pkg"
pkgtrans "${BROOT}/${PNAME}.pkg" "${BROOT}" "${PKGNAME}"
# create the zap file
cd "$BROOT" || exit 1
# 7z gives us an extra 2-3% reduction in file size
#zip -9 -q -r ${PKGNAME} ${PKGNAME}
rm -f "${PNAME}.zap" "${PNAME}.zap.md5" "${PNAME}.zap.sig"
7za a -tzip -mx=9 -mfb=256 "${PNAME}.zap" "${PKGNAME}"
chmod a+r "${PNAME}.zap"
cd /
# pregenerate the md5 checksum ready for catalog creation
openssl md5 "${BROOT}/${PNAME}.zap" | /usr/bin/awk '{print $NF}' > "${BROOT}/${PNAME}.zap.md5"
# sign the zap file
"${BUILD}"/sign-file "${BROOT}/${PNAME}.zap"

ls -lh "${BROOT}/${PNAME}.pkg"
ls -lh "${BROOT}/${PNAME}.zap"
rm -fr "${BROOT}/${PKGNAME}"
