#!/bin/ksh
#
# alias catalog format is
#  alias|pkgname
#
# -v to verify there are no duplicates
#

builtin cat

PKGDIR="../pkgs"
case $# in
1)
	PKGDIR=$1
	;;
esac

case $1 in
-v)
  DUPS=`cat */alias|sort|uniq -d`
  if [[ -n $DUPS ]]; then
    echo "ERROR: duplicates found"
    cat */alias|sort|uniq -d
  fi
  exit 0
  ;;
esac

for PKGI in */alias
do
  PKG=${PKGI%/*}
  PKGVERS=`awk -F= '{if ($1 == "VERSION") print $2}' ${PKG}/pkginfo`
  PKGVERS=${PKGVERS//\"/}
  if [ -f ${PKGDIR}/${PKG}.${PKGVERS}.zap ]; then
    for PALIAS in `cat $PKGI`
    do
      echo "${PALIAS}|${PKG}"
    done
  fi
done
