#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# create-file-list
#
# generates a listing of files contained in all packages
# uses the catalog as a source
#

case $# in
1)
    WDIR="$1"
    ;;
*)
    echo "Usage: $0 directory"
    exit 1
    ;;
esac

if [ ! -d "$WDIR" ]; then
    echo "ERROR: directory $WDIR not found"
    exit 1
fi

if [ ! -f "${WDIR}/catalog" ]; then
    echo "ERROR: $WDIR does not contain a catalog"
    exit 1
fi

cd "$WDIR" || exit 1

#
# loop over every zap file in the current catalog
#
rm -f filelist.new
touch filelist.new
awk -F'|' '{print $1,$2}' catalog | while read -r pkgname pkgver
do
    if [ -f "${pkgname}.${pkgver}.zap" ]; then
	#
	# grep / out of the pkgmap file to get the list of paths
	# this also skips the informational files
	# field 2 in the result is the file type
	# field 4 in the result is the file name
	# ignore directories
	# strip any leading / off the names just once afterwards
	#
	unzip -p "${pkgname}.${pkgver}.zap" "${pkgname}/pkgmap" | grep / | awk -v PKG="$pkgname" '{if ($2 != "d") print $4,$2,PKG}' >> filelist.new
    else
	echo "Missing file ${pkgname}.${pkgver}.zap"
    fi
done

#
# strip off the leading /
#
sed -i 's:^/::' filelist.new

#
# the resulting file has 3 fields
# 1 - pathname without the leading /
# 2 - file type
# 3 - package name
#

#
# the file is pretty compressible, which we want to do to minimize
# bandwidth utilization and download times
#
# initial main database: 32M, compressed 1.7M
#
pbzip2 filelist.new
rm -f filelist.bz2
mv filelist.new.bz2 filelist.bz2
ls -lh filelist.bz2
