#!/bin/ksh
#
# catalog format is
#  name|version|dependencies|size|md5|
#
THOME=${THOME:-/packages/localsrc/Tribblix}
PKGDIR=${THOME}/opensxce-2014
case $# in
1)
	PKGDIR=$1
	;;
esac

#
cd $PKGDIR
for ZPKG in *.zap
do
  DEPLIST=""
  PNAME=${ZPKG%%.*}
  PF=${ZPKG%.zap}
  PKGVERS=${PF#*.}
  if [ -x /usr/bin/stat ]; then
    PKGSIZE=$(/usr/bin/stat --printf="%s" ${ZPKG})
  else
    PKGSIZE=$(/bin/ls -l ${ZPKG} | /usr/bin/awk '{print $5}')
  fi
  if [ ${ZPKG}.md5 -nt ${ZPKG} ]; then
    PKGMD5=$(<${ZPKG}.md5)
  else
    PKGMD5=$(openssl md5 ${ZPKG} | /usr/bin/awk '{print $NF}')
    /bin/rm -f ${ZPKG}.md5
    echo $PKGMD5 > ${ZPKG}.md5
  fi
  DEPLIST=$(bash zipgrep '^P' $ZPKG ${PNAME}/install/depend 2>/dev/null |awk '{printf("%s ", $2)}')
  echo "${PNAME}|${PKGVERS}|${DEPLIST}|${PKGSIZE}|${PKGMD5}|" | sed 's: |:|:'
done
