#!/bin/ksh
#
# creates a repo - actually, create a repo directory and keep it up to date
#

DOCHECK="false"
DOUPDATE="false"
BUILDROOT="/packages/localsrc/Tribblix"
PKGDIR="/var/tmp/created-pkgs/pkgs"
PKGBUILD="${BUILDROOT}/build"

case $1 in
-c)
	DOCHECK="true"
	shift
	;;
-u)
	DOUPDATE="true"
	shift
	;;
esac

case $# in
1)
	REPODIR="$1"
	;;
*)
	echo "Usage: $0 [-c | -u] repo_dir"
	exit 1
	;;
esac

#
# FIXME implement check and update
#

if [ -d ${REPODIR} ]; then
   echo "ERROR: repodir must not exist for new creation"
   exit 1
else
   mkdir $REPODIR
fi

if [ ! -d ${REPODIR} ]; then
   echo "ERROR: unable to create ${REPODIR}"
   exit 1
fi

#
# create the catalog file
# FIXME: how to handle the illumos and oi repos?
# FIXME: arch hardcoded for i386
#
${PKGBUILD}/create-oi-catalog > ${REPODIR}/catalog
mkdir -p ${REPODIR}
#
# then find all the packages
#
# if we find a correctly versioned package, then assume it's perfect
# if not, use the unversioned packae as package versions here are made up
#
IFS="|"
cat ${REPODIR}/catalog | while read pkgname pkgvers deplist
do
  pkgfull="${pkgname}.${pkgvers}"
  if [ -f ${PKGDIR}/${pkgfull}.zap ]; then
    if [ "X${DOCHECK}" = "Xfalse" ]; then
      cp -p ${PKGDIR}/${pkgfull}.zap ${REPODIR}/${pkgfull}.zap
    fi
  elif [ -f ${PKGDIR}/${pkgname}.zap ]; then
      if [ "X${DOCHECK}" = "Xfalse" ]; then
        cp -p ${PKGDIR}/${pkgname}.zap ${REPODIR}/${pkgfull}.zap
      fi
  elif [ -f ${PKGDIR}/${pkgname}.pkg ]; then
      if [ "X${DOCHECK}" = "Xfalse" ]; then
        ${PKGBUILD}/pkg2zap ${PKGDIR}/${pkgname}.pkg ${REPODIR}
        mv ${REPODIR}/${pkgname}.zap ${REPODIR}/${pkgfull}.zap
        cp ${REPODIR}/${pkgfull}.zap ${PKGDIR}
      fi
  else
    echo Unable to find package for ${pkgname}
  fi
done
