#!/bin/ksh
#
# like the catalog, but neatly formatted as html
#

builtin cat

PKGDIR="../pkgs"
case $# in
1)
	PKGDIR=$1
	;;
esac

cat <<EOF
<html>
<Head><title>Tribblix package catalog</title></head>
<body>
<h1>Tribblix packages</h1>
<dl>
EOF

for PKGI in */pkginfo
do
  PKG=${PKGI%/*}
  PKGVERS=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI`
  PKGVERS=${PKGVERS//\"/}
  if [ -f ${PKGDIR}/${PKG}.${PKGVERS}.zap ]; then
    PKGNAME=`awk -F= '{if ($1 == "NAME") print $2}' $PKGI`
    PKGNAME=${PKGNAME//\"/}
    PKGHOME=`awk -F= '{if ($1 == "ZAP_URL") print $2}' $PKGI`
    PKGHOME=${PKGHOME//\"/}
    DEPLIST=""
    IDEPLIST=""
    PKGCKSUM=`cat ${PKGDIR}/${PKG}.${PKGVERS}.zap.md5`
    if [ -f ${PKG}/depend ]; then
       DEPLIST=`grep '^P' ${PKG}/depend | awk '{printf("%s ", $2)}'`
       IDEPLIST=`grep '^I' ${PKG}/depend | awk '{printf("%s ", $2)}'`
    fi
    echo "<dt><a name=\"${PKG}\"></a><b>${PKG}</b></dt>"
    echo "<dd>"
    echo "${PKGNAME}"
    if [ -n "${PKGHOME}" ]; then
	echo " [<a href=\"${PKGHOME}\">Home</a>]"
    fi
    echo "<ul>"
    echo "<li>Version: ${PKGVERS}</li>"
    echo "<li><a href=\"${PKG}.${PKGVERS}.zap\">Download</a> [MD5: ${PKGCKSUM}]</li>"
    for mydep in $DEPLIST
    do
        if [ -d $mydep ]; then
	    echo "<li>Requires: <a href=\"#${mydep}\">$mydep</a></li>"
        else
	    echo "<li>Requires: $mydep</li>"
        fi
    done
    for mydep in $IDEPLIST
    do
        if [ -d $mydep ]; then
	    echo "<li>Incompatible with: <a href=\"#${mydep}\">$mydep</a></li>"
        else
	    echo "<li>Incompatible with: $mydep</li>"
        fi
    done
    echo "</ul>"
    echo "</dd>"
  fi
done

cat <<EOF
</dl>
<hr>
<p><a href="http://www.tribblix.org/">Tribblix</a></p>
</body>
</html>
EOF
