#!/bin/ksh
#
# alias catalog format is
#  alias|pkgname
#
# -v to verify there are no duplicates
#

builtin cat

PKGDIR="../pkgs"
case $# in
1)
	PKGDIR=$1
	;;
esac

case $1 in
-v)
  DUPS=`sort */alias|uniq -d`
  if [[ -n $DUPS ]]; then
    echo "ERROR: duplicates found"
    sort */alias|uniq -d
  fi
  exit 0
  ;;
esac

ggrep '^VERSION=' */pkginfo | while read vstring
do
    PKG=${vstring%/*}
    PKGVERS=${vstring##*=}
    PKGVERS=${PKGVERS//\"/}
    if [ -f ${PKGDIR}/${PKG}.${PKGVERS}.zap ]; then
	PKGI=${PKG}/alias
	if [ -f $PKGI ]; then	    
	    for PALIAS in $(<${PKGI})
	    do
		echo "${PALIAS}|${PKG}"
	    done
	fi
    fi
done
