#!/bin/ksh
#
# catalog format is
#  name|version|dependencies|size|md5|
#
RELVER=m20
THOME=${THOME:-/packages/localsrc/Tribblix}
PKGDIR=${THOME}/illumos-pkgs-${RELVER}/pkgs

case $# in
1)
	PKGDIR=$1
	;;
esac

#
# try and work out if we're sparc
#
SSUFFIX=""
case $PKGDIR in
    *.sparc*)
	SSUFFIX=".sparc"
	;;
esac

#
# try and work out the version number
#
NPKGDIR=${PKGDIR%/pkgs}
NPKGDIR=${NPKGDIR%.sparc}
RELVER=`echo $NPKGDIR|awk -F- '{print $NF}'`
RELNUM=`echo $RELVER|sed s:m::`

#
# updates and variants share the same Tribblix release
#
TRELVER=${RELVER%.*}
TRELVER=${TRELVER%lx}

cat <<EOF
<html>
<Head><title>Tribblix package catalog</title></head>
<body>
<h1>Illumos packages for Tribblix</h1>
<dl>
EOF


#
# prefer zap as we can get dependencies, and it's quicker
#
cd $PKGDIR
for ZPKG in *.zap
do
  DEPLIST=""
  PKG=${ZPKG%.zap}
  PNAME=${ZPKG%%.*}
  PKGVERS=${PKG#*.}
  PKGNAME=`bash zipgrep '^NAME=' $ZPKG ${PNAME}/pkginfo 2>/dev/null| awk -F= '{print $NF}'`
  PKGCKSUM=`cat ${ZPKG}.md5`
  if [ -f catalog ]; then
      DEPLIST=`grep "^${PKG}|" catalog |awk -F'|' '{print $3}'`
  else
      DEPLIST=`bash zipgrep '^P' $ZPKG ${PNAME}/install/depend 2>/dev/null |awk '{printf("%s ", $2)}'`
  fi
  FMRI=`bash zipgrep '^IPS_FMRI' $ZPKG ${PNAME}/pkginfo 2>/dev/null |nawk -F'[=@]' '{print $2}'`
  echo "<dt><a name=\"${PNAME}\"></a><b>${PNAME}</b></dt>"
  echo "<dd>\n${PKGNAME}\n<ul>\n<li>Version: ${PKGVERS}</li>"
  FMRI=${FMRI/pkg:\/\/on-nightly\//}
  FMRI=${FMRI/pkg:\/\/omnios\//}
  echo "<li>IPS name: ${FMRI}</li>"
  echo "<li><a href=\"${PNAME}.${PKGVERS}.zap\">Download</a> [MD5: ${PKGCKSUM}]</li>"
  for mypkgdep in $DEPLIST
  do
      if [ -f ${mypkgdep}.0.${RELNUM}.zap ]; then
	  echo "<li>Requires: <a href=\"#${mypkgdep}\">$mypkgdep</a></li>"
      elif [ -d ${THOME}/build/${mypkgdep} ]; then
	  echo "<li>Requires: <a href=\"../tribblix-${TRELVER}${SSUFFIX}/#${mypkgdep}\">$mypkgdep</a></li>"
      else
	  echo "<li>Requires: $mypkgdep</li>"
      fi
  done
  echo "</ul></dd>"
done

cat <<EOF
</dl>
<hr>
<p><a href="http://www.tribblix.org/">Tribblix</a></p>
</body>
</html>
EOF
