#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# this will sign just the current versions of packages
# (otherwise, you could use sign-directory)
#

builtin echo

PKGDIR="../pkgs"
case $# in
1)
	PKGDIR="$1"
	;;
esac

THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"

if [ ! -d "$BUILD" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi

if [ ! -f "${PKGDIR}/catalog" ]; then
    echo "Missing catalog"
    exit 1
fi

awk -F'|' '{print $1,$2}' "${PKGDIR}/catalog" | while read -r PKG PKGVERS
do
  if [ -f "${PKGDIR}/${PKG}.${PKGVERS}.zap" ]; then
    if [ ! -f "${PKGDIR}/${PKG}.${PKGVERS}.zap.sig" ]; then
      "${BUILD}"/sign-file "${PKGDIR}/${PKG}.${PKGVERS}.zap"
    fi
  fi
done
