#!/bin/sh
#
# for a given package, lists its consumers, whether those are run-time
# or build-time dependencies
#

THOME=${THOME:-/packages/localsrc/Tribblix}
BDIR=${THOME}/build
PDIR="/var/sadm/pkg"

STATUS=0

#
# if no arguments, shortcut for the package I'm looking at right now
#
case $# in
    0)
	DIR=$(pwd)
	set -- "${DIR##*/}"
	;;
esac

install_status() {
    pkg=$1
    if [ -f "${PDIR}/${pkg}/pkginfo" ]
    then
	echo "installed"
    else
	echo "not installed"
    fi
}

cd "$BDIR" || exit 1
for dir in "$@"
do
    # remove any trailing / added by tab-completion
    dir=${dir%%/}
    if [ -d "${dir}" ]; then
	echo "Checking $dir ($(install_status $dir))"
	grep -lx "P $dir" */depend* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  run-time ${pkg} ($(install_status $pkg))"
	done
	grep -lx "I $dir" */depend* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  run-incompatible ${pkg} ($(install_status $pkg))"
	done
	grep -lx "$dir" */build_require* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  build-time ${pkg} ($(install_status $pkg))"
	done
	grep -lx "$dir" */build_incompatible* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  build-incompatible ${pkg} ($(install_status $pkg))"
	done
    else
	echo "No such package $dir"
	STATUS=1
    fi
done

exit $STATUS
