#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# for a given package, lists its consumers, whether those are run-time
# or build-time dependencies, or overlays it's a member of
#

THOME=${THOME:-/packages/localsrc/Tribblix}
BDIR=${THOME}/build
OVDIR=${THOME}/overlays
PDIR="/var/sadm/pkg"

STATUS=0

#
# if no arguments, shortcut for the package I'm looking at right now
#
case $# in
    0)
	DIR=$(pwd)
	set -- "${DIR##*/}"
	;;
esac

install_status() {
    pkg=$1
    if [ -f "${PDIR}/${pkg}/pkginfo" ]
    then
	echo "installed"
    else
	echo "not installed"
    fi
}

cd "$BDIR" || exit 1
for dir in "$@"
do
    # remove any trailing / added by tab-completion
    dir=${dir%%/}
    if [ -d "${dir}" ]; then
	echo "Checking $dir ($(install_status "$dir"))"
	grep -lx "P $dir" TRIB*/depend* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  run-time ${pkg} ($(install_status "$pkg"))"
	done
	grep -lx "I $dir" TRIB*/depend* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  run-incompatible ${pkg} ($(install_status "$pkg"))"
	done
	grep -lx "$dir" TRIB*/build_require* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  build-time ${pkg} ($(install_status "$pkg"))"
	done
	grep -lx "$dir" TRIB*/build_incompatible* | while read -r dep
	do
	    pkg=${dep%%/*}
	    echo "  build-incompatible ${pkg} ($(install_status "$pkg"))"
	done
	grep -lx "$dir" ${OVDIR}/*.pkgs | while read -r dep
	do
	    pkg=${dep%.pkgs}
	    pkg=${pkg##*/}
	    echo "  member of overlay ${pkg}"
	done
    else
	echo "No such package $dir"
	STATUS=1
    fi
done

exit $STATUS
