#!/bin/ksh
#
# build some software
#
# assumes ./configure ; make
#

BUILD="/packages/localsrc/Tribblix/build"
GMAKE="/usr/bin/gmake"
WORKING_ROOT=`pwd`

case $# in
    0)
	echo "Usage: $0 [-64|+64] [-gnu] src_name \\"
        echo "  [-S subdir] [-P alt_prefix] [-C configure_args] \\"
	echo "  [-M make_args] [-J parallelism]"
	echo "Arguments must be supplied in the order specified"
	exit 1
	;;
esac

#
# if a dual 32- and 64-bit build is desired, specify -64 *first*
# +64 means just do the 64-bit (useful for testing it in isolation)
# note that +64 will wipe the 32-bit directory
#
DO32="true"
DO64="false"
UNPACK_FLAGS=""
case $1 in
-64)
	DO64="true"
	UNPACK_FLAGS="-64"
	shift
	;;
+64)
	DO64="true"
	DO32="false"
	UNPACK_FLAGS="+64"
	shift
	;;
esac

#
# if /usr/gnu/bin is needed in the PATH (usually, to find GNU gettext)
# then specify -gnu
#
DOGNU="false"
case $1 in
-gnu)
	DOGNU="true"
	shift
	;;
esac

#
# FIXME
# just one package, followed by
# -S subdir
# -P alternate_prefix
# -C configure_args
# -M make_args
# -I install_args [unused]
# -J parallelism
#
IPREFIX="/usr"
CONFARGS=""
MAKEARGS=""
SUBDIR=""
GMAKEFLAGS="-j 4"

THISPKG="$1"
shift
case $1 in
-S)
	shift
	SUBDIR="/$1"
	shift
	;;
esac
case $1 in
-P)
	shift
	IPREFIX="$1"
	shift
	;;
esac
case $1 in
-C)
	shift
	CONFARGS="$1"
	shift
	;;
esac
case $1 in
-M)
	shift
	MAKEARGS="$1"
	shift
	;;
esac
case $1 in
-J)
	shift
	GMAKEFLAGS="-j $1"
	shift
	;;
esac

#
# 64-bit files go in these subdirectories
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

UNPACKER=${BUILD}/unpack
export UNPACKER
for pkg in ${THISPKG}
do
	${BUILD}/unpack ${UNPACK_FLAGS} ${pkg}
	if [ "x$DO64" != "xfalse" ]; then
	    cd ${WORKING_ROOT}
	    cd ${pkg}-64bit${SUBDIR}
	    if [ -x "${BUILD}/patches/${pkg}.preconf" ]; then
		${BUILD}/patches/${pkg}.preconf
	    fi
	    if [ "x$DOGNU" != "xfalse" ]; then
		env PKG_CONFIG_PATH=/usr/lib/${ARCH64}/pkgconfig PATH=/usr/gnu/bin:$PATH LDFLAGS="-m64" CFLAGS="-O -m64 ${TRIBBLIX_CFLAGS}" CXXFLAGS="-O -m64 ${TRIBBLIX_CXXFLAGS}" ./configure --prefix=${IPREFIX} ${CONFARGS} --bindir=${IPREFIX}/bin/${ARCH64} --libdir=${IPREFIX}/lib/${ARCH64}
	    else
		env PKG_CONFIG_PATH=/usr/lib/${ARCH64}/pkgconfig LDFLAGS="-m64" CFLAGS="-O -m64 ${TRIBBLIX_CFLAGS}" CXXFLAGS="-O -m64 ${TRIBBLIX_CXXFLAGS}" ./configure --prefix=${IPREFIX} ${CONFARGS} --bindir=${IPREFIX}/bin/${ARCH64} --libdir=${IPREFIX}/lib/${ARCH64}
	    fi
	    if [ -x "${BUILD}/patches/${pkg}.postconf" ]; then
		${BUILD}/patches/${pkg}.postconf
	    fi
	    ${GMAKE} ${GMAKEFLAGS} ${MAKEARGS}
	fi
	if [ "x$DO32" != "xfalse" ]; then
	    cd ${WORKING_ROOT}
	    cd ${pkg}${SUBDIR}
	    if [ -x "${BUILD}/patches/${pkg}.preconf" ]; then
		${BUILD}/patches/${pkg}.preconf
	    fi
	    if [ "x$DOGNU" != "xfalse" ]; then
		env PATH=/usr/gnu/bin:$PATH CFLAGS="-O ${TRIBBLIX_CFLAGS}" CXXFLAGS="-O ${TRIBBLIX_CXXFLAGS}" ./configure ${CONFARGS} --prefix=${IPREFIX}
	    else
		env CFLAGS="-O ${TRIBBLIX_CFLAGS}" CXXFLAGS="-O ${TRIBBLIX_CXXFLAGS}" ./configure ${CONFARGS} --prefix=${IPREFIX}
	    fi
	    if [ -x "${BUILD}/patches/${pkg}.postconf" ]; then
		${BUILD}/patches/${pkg}.postconf
	    fi
	    ${GMAKE} ${GMAKEFLAGS} ${MAKEARGS}
	fi
done
