#!/bin/ksh
#
# build some software
#
# assumes ./configure ; make
#

BUILD="/packages/localsrc/Tribblix/build"
GMAKE="/usr/bin/gmake"
WORKING_ROOT=`pwd`

case $# in
    0)
	echo "Usage: $0 [-64|+64] [-gnu] src_name \\"
        echo "  [-S subdir] [-P alt_prefix] [-C configure_args] \\"
	echo "  [-M make_args] [-J parallelism] [-L]"
	exit 1
	;;
esac

#
# if a dual 32- and 64-bit build is desired, specify -64 *first*
# +64 means just do the 64-bit (useful for testing it in isolation)
# note that +64 will wipe the 32-bit directory
#
DO32="true"
DO64="false"
UNPACK_FLAGS=""

#
# if /usr/gnu/bin is needed in the PATH (usually, to find GNU gettext)
# then specify -gnu
#
DOGNU="false"

#
# Other arguments are
# package name
# -S subdir
# -P alternate_prefix
# -C configure_args
# +C configure_args [64-bit]
# -E set sysconfdir to arg
# +E set sysconfdir to arg, with 64-bit subdir
# -M make_args
# -I install_args [unused]
# -J parallelism
# -L disable LD_OPTIONS
#
IPREFIX="/usr"
CONFARGS32=""
CONFARGS64=""
ECONFARGS32=""
ECONFARGS64=""
MAKEARGS=""
SUBDIR=""
GMAKEFLAGS="-j 4"
DO_LD="yes"

while [[ $# > 0 ]]; do
case $1 in
-64)
	DO64="true"
	UNPACK_FLAGS="-64"
	shift
	;;
+64)
	DO64="true"
	DO32="false"
	UNPACK_FLAGS="+64"
	shift
	;;
-gnu)
	DOGNU="true"
	shift
	;;
-S)
	shift
	SUBDIR="/$1"
	shift
	;;
-P)
	shift
	IPREFIX="$1"
	shift
	;;
-C)
	shift
	CONFARGS32="$1"
	shift
	;;
+C)
	shift
	CONFARGS64="$1"
	shift
	;;
-E)
	shift
	ECONFARGS32="--sysconfdir=$1"
	ECONFARGS64="--sysconfdir=$1"
	shift
	;;
+E)
	shift
	ECONFARGS32="--sysconfdir=$1"
	shift
	;;
-M)
	shift
	MAKEARGS="$1"
	shift
	;;
-J)
	shift
	GMAKEFLAGS="-j $1"
	shift
	;;
-L)
	shift
	DO_LD=""
	;;
-*)
	echo "Invalid argument $1"
	exit 1
	;;
*)
	THISPKG="$THISPKG $1"
	shift
	;;
esac
done

#
# if we don't have specific 64-bit configure args,
# then use the 32-bit ones
#
if [[ -z $CONFARGS64 ]]; then
    CONFARGS64="$CONFARGS32"
fi

#
# 64-bit files go in these subdirectories
#
case `uname -p` in
sparc)
    ARCH64="sparcv9"
    ;;
i386)
    ARCH64="amd64"
    ;;
esac

#
# if we have a 32-bit ECONFARGS but not a 64-bit one, then
# create a 64-bit one with the architecture subdir
#
if [[ -n $ECONFARGS32 ]]; then
    if [[ -z $ECONFARGS64 ]]; then
	ECONFARGS64="${ECONFARGS32}/${ARCH64}"
    fi
fi

#
# default linker options
#
if [[ -n $DO_LD ]]; then
case `uname -p` in
sparc)
    LD_OPTIONS="-M /usr/lib/ld/map.noexbss -M /usr/lib/ld/map.noexstk -M /usr/lib/ld/map.pagealign -Bdirect -z ignore"
    ;;
i386)
    LD_OPTIONS="-M /usr/lib/ld/map.noexdata -M /usr/lib/ld/map.noexstk -M /usr/lib/ld/map.pagealign -Bdirect -z ignore"
    ;;
esac
export LD_OPTIONS
fi

#
# with -gnu, add /usr/gnu/bin at the head of PATH
#
if [ "x$DOGNU" != "xfalse" ]; then
    TRIBBLIX_PATH=/usr/gnu/bin:$PATH
else
    TRIBBLIX_PATH=$PATH
fi

UNPACKER=${BUILD}/unpack
export UNPACKER
PATCHDIR=${BUILD}/patches
export PATCHDIR
for pkg in ${THISPKG}
do
	${BUILD}/unpack ${UNPACK_FLAGS} ${pkg}
	if [ "x$DO64" != "xfalse" ]; then
	    cd ${WORKING_ROOT}
	    if [ ! -d ${pkg}-64bit ]; then
		echo "Cannot find source directory ${pkg}-64bit"
		exit 1
	    fi
	    if [[ -n $DO_LD ]]; then
		cd ${pkg}-64bit
		touch .tribblix_ldopts
		cat >> .tribblix_ldopts <<EOF
LD_OPTIONS="${LD_OPTIONS}"
export LD_OPTIONS
EOF
		cd ${WORKING_ROOT}
	    fi
	    cd ${pkg}-64bit${SUBDIR}
	    if [ -x "${BUILD}/patches/${pkg}.preconf.64" ]; then
		${BUILD}/patches/${pkg}.preconf.64
	    elif [ -x "${BUILD}/patches/${pkg}.preconf" ]; then
		${BUILD}/patches/${pkg}.preconf
	    fi
	    env PKG_CONFIG_PATH=/usr/lib/${ARCH64}/pkgconfig PATH=/usr/bin/${ARCH64}:$TRIBBLIX_PATH LDFLAGS="-m64 ${TRIBBLIX_LDFLAGS}" CFLAGS="-O -m64 ${TRIBBLIX_CFLAGS}" CXXFLAGS="-O -m64 ${TRIBBLIX_CXXFLAGS}" ./configure --prefix=${IPREFIX} ${CONFARGS64} ${ECONFARGS64} --bindir=${IPREFIX}/bin/${ARCH64} --libdir=${IPREFIX}/lib/${ARCH64}
	    if [ -x "${BUILD}/patches/${pkg}.postconf.64" ]; then
		${BUILD}/patches/${pkg}.postconf.64
	    elif [ -x "${BUILD}/patches/${pkg}.postconf" ]; then
		${BUILD}/patches/${pkg}.postconf
	    fi
	    ${GMAKE} ${GMAKEFLAGS} ${MAKEARGS}
	fi
	if [ "x$DO32" != "xfalse" ]; then
	    cd ${WORKING_ROOT}
	    if [ ! -d ${pkg} ]; then
		echo "Cannot find source directory ${pkg}"
		exit 1
	    fi
	    if [[ -n $DO_LD ]]; then
		cd ${pkg}
		touch .tribblix_ldopts
		cat >> .tribblix_ldopts <<EOF
LD_OPTIONS="${LD_OPTIONS}"
export LD_OPTIONS
EOF
		cd ${WORKING_ROOT}
	    fi
	    cd ${pkg}${SUBDIR}
	    if [ -x "${BUILD}/patches/${pkg}.preconf" ]; then
		${BUILD}/patches/${pkg}.preconf
	    fi
	    env PATH=$TRIBBLIX_PATH LDFLAGS="-m32 ${TRIBBLIX_LDFLAGS}" CFLAGS="-O ${TRIBBLIX_CFLAGS}" CXXFLAGS="-O ${TRIBBLIX_CXXFLAGS}" ./configure ${CONFARGS32} ${ECONFARGS32} --prefix=${IPREFIX}
	    if [ -x "${BUILD}/patches/${pkg}.postconf" ]; then
		${BUILD}/patches/${pkg}.postconf
	    fi
	    ${GMAKE} ${GMAKEFLAGS} ${MAKEARGS}
	fi
done
