#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
awk '
{ $5 = "root"; $6 = "bin" }
{if ($3 == "usr/lib/pkgconfig")  $6 = "other"}
{if ($3 == "usr/lib/amd64/pkgconfig")  $6 = "other"}
{if ($3 == "usr/lib/sparcv9/pkgconfig")  $6 = "other"}
{if ($3 == "usr/share")  $6 = "sys"}
{if ($3 == "usr/lib/devfsadm")  $6 = "sys"}
{if ($3 == "usr/lib/devfsadm/linkmod")  $6 = "sys"}
{if ($1 == "d" && $3 ~ /^usr\/share\/locale/)  $6 = "other"}
{if ($3 == "usr/share/xsessions")  $6 = "other"}
{if ($3 == "usr/share/pixmaps")  $6 = "other"}
{if ($3 == "usr/share/applications")  $6 = "other"}
{if ($3 == "usr/share/doc")  $6 = "other"}
{if ($3 == "usr/share/icons")  $6 = "other"}
{if ($3 == "usr/share/pixmaps/backgrounds")  $6 = "other"}
{if ($3 == "usr/bin/gkrellm")  $6 = "sys"}
{if ($3 == "usr/bin/gkrellmd")  $6 = "sys"}
{if ($3 ~ /^kernel/)  $6 = "sys"}
{if ($3 ~ /^boot/)  $6 = "sys"}
{if ($3 ~ /^usr\/share\/mime\/application/)  $6 = "root"}
{if ($3 == "opt")  $6 = "sys"}
{if ($3 == "usr")  $6 = "sys"}
{if ($3 == "var")  $6 = "sys"}
{if ($3 == "var/lib")  $6 = "other"}
{if ($3 == "var/lib/gdm")  { $6 = "gdm" ; $5 = "gdm" }}
{if ($3 == "var/log")  $6 = "sys"}
{if ($3 == "var/run")  $6 = "sys"}
{if ($3 == "var/run/istat") { $6 = "daemon" ; $5 = "daemon" }}
{if ($3 == "var/cache/istat") { $6 = "daemon" ; $5 = "daemon" }}
{if ($3 == "var/sadm")  $6 = "sys"}
{if ($3 == "var/sadm/license")  $6 = "sys"}
{if ($3 == "sbin")  $6 = "sys"}
{if ($3 == "lib/svc/manifest")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/application")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/application/management")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/application/security")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/application/x11")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/network")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/system")  $6 = "sys"}
{if ($3 == "lib/svc/manifest/system/filesystem")  $6 = "sys"}
{if ($3 == "var/svc")  $6 = "sys"}
{if ($3 == "var/svc/manifest")  $6 = "sys"}
{if ($3 == "var/svc/manifest/network")  $6 = "sys"}
{if ($3 == "var/svc/manifest/site")  $6 = "sys"}
{if ($3 == "var/svc/manifest/application")  $6 = "sys"}
{if ($3 == "etc")  $6 = "sys"}
{if ($3 == "etc/inet")  $6 = "sys"}
{if ($3 == "etc/security")  $6 = "sys"}
{if ($3 == "etc/security/auth_attr.d")  $6 = "sys"}
{if ($3 == "etc/security/exec_attr.d")  $6 = "sys"}
{if ($3 == "etc/security/prof_attr.d")  $6 = "sys"}
{if ($3 == "etc/ssh")  $6 = "sys"}
{if ($3 == "etc/svc")  $6 = "sys"}
{if ($3 == "etc/svc/profile")  $6 = "sys"}
{if ($3 == "etc/X11")  $6 = "sys"}
{if ($3 == "etc/X11/fontpath.d")  $6 = "sys"}
{if ($3 == "etc/zones")  $6 = "sys"}
{if ($3 == "etc/rc0.d")  $6 = "sys"}
{if ($3 == "etc/rc2.d")  $6 = "sys"}
{if ($3 == "etc/rc3.d")  $6 = "sys"}
{if ($3 == "etc/init.d")  $6 = "sys"}
{if ($3 == "usr/share/lib")  $6 = "sys"}
{if ($3 == "usr/share/aclocal")  $6 = "other"}
{if ($3 == "usr/gnu/share")  $6 = "sys"}
{if ($3 == "usr/perl5/site_perl")  $6 = "root"}
{print}
'
