#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# simple wrapper to create ruby module metadata
#
# you may need to modify the depend file
#

#
# by default, package for 3
#

RUBYVER=3
BUILDER=pkg_gem

#
# if just one argument, use it as both the package and gem name
#
case $# in
1)
	pkg_name=$1
	TBALL=$1
	;;
2)
	pkg_name=$1
	TBALL=$2
	;;
*)
	echo "Usage: $0 [pkg_name] gem_name"
	exit 1
	;;
esac

RUBYNAME=TRIB${pkg_name}-ruby-${RUBYVER}

#
# check we're within the SVR4 package name length limit
#
NAMELEN=${#RUBYNAME}
if [ "$NAMELEN" -gt 31 ]; then
    echo "Chosen name exceeds the SVR4 package name length limit (length $NAMELEN)"
    exit 1
fi

if [ -d "$RUBYNAME" ]; then
   echo "$RUBYNAME already exists"
   exit 1
fi

#
# OK, now we can create the package metadata
#

#
mkdir "$RUBYNAME"
echo "P TRIBv-ruby-$RUBYVER" > "$RUBYNAME/depend"
cat > "$RUBYNAME/pkginfo" <<EOF
PKG="${RUBYNAME}"
NAME="Ruby $TBALL"
VERSION="1.0"
EOF
cat > "$RUBYNAME/build.sh" <<EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
\${THOME}/build/$BUILDER $RUBYNAME $TBALL
EOF
chmod a+x "$RUBYNAME/build.sh"

echo "Now check $RUBYNAME/pkginfo and $RUBYNAME/depend"
