#!/bin/ksh
#
# generate a package
#

#
# handle arguments
# -I what to install (normally "install")
#
INSTALLWHAT="install"
while [[ $# > 0 ]]; do
case $1 in
-I)
	INSTALLWHAT=$2
	shift
	shift
	;;
*)
	break
	;;
esac
done

case $# in
0)
	echo "Usage: $0 pkg_name [build_dir ...]"
	exit 1
	;;
*)
	PKGNAME="$1"
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"
BROOT="/tmp/pct"
GMAKE="/usr/bin/gmake"

#
# sanity check
#
if [ ! -d $BUILD ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi
if [ ! -d $BROOT ]; then
   mkdir -p ${BROOT}
fi
if [ ! -d $BROOT ]; then
   echo "ERROR: unable to find temporary directory $BROOT"
   exit 1
fi
if [ ! -x $GMAKE ]; then
   echo "ERROR: unable to find $GMAKE"
   exit 1
fi
if [ ! -f ${BUILD}/${PKGNAME}/pkginfo ]; then
   echo "ERROR: missing package data"
   echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
   exit 1
fi

#
# define and create working location
#
BDIR="${BROOT}/pkg.$$"
rm -fr ${BDIR}
mkdir $BDIR

#
# normally we want the makefiles to use ginstall rather than the
# SVR4 install program
#
MYINSTALL="INSTALL=ginstall"
#
# except for some stupid makefiles that randomly
# violate conventional norms
#
case $2 in
httpd*|doxygen*)
	MYINSTALL=""
	;;
esac

#
# install the package(s) specified to that location
#
case $# in
1)
	if [ -f .tribblix_ldopts ]; then
	    . ./.tribblix_ldopts
	fi
	$GMAKE -k $INSTALLWHAT DESTDIR=$BDIR $MYINSTALL
	if [ -x ${BUILD}/${PKGNAME}/fixinstall ]; then
	    ${BUILD}/${PKGNAME}/fixinstall $BDIR
	fi
	;;
*)
	shift
	for SOFTDIR in $*
	do
	    if [ -d ${SOFTDIR}-64bit ]; then
		cd ${SOFTDIR}-64bit
		if [ -f .tribblix_ldopts ]; then
		    . ./.tribblix_ldopts
		fi
		if [ -f .tribblix_cmake_build ]; then
		    cd build
		fi
		$GMAKE -k $INSTALLWHAT DESTDIR=$BDIR $MYINSTALL
		if [ -x ${BUILD}/${PKGNAME}/fixinstall.64 ]; then
		    ${BUILD}/${PKGNAME}/fixinstall.64 $BDIR
		fi
		if [ -f ../.tribblix_cmake_build ]; then
		    cd ..
		fi
		cd ..
	    fi
	    cd ${SOFTDIR}
	    if [ -f .tribblix_ldopts ]; then
		. ./.tribblix_ldopts
	    fi
	    if [ -f .tribblix_cmake_build ]; then
		cd build
	    fi
	    $GMAKE -k $INSTALLWHAT DESTDIR=$BDIR $MYINSTALL
	    if [ -x ${BUILD}/${PKGNAME}/fixinstall ]; then
		${BUILD}/${PKGNAME}/fixinstall $BDIR
	    fi
	    if [ -f ../.tribblix_cmake_build ]; then
		cd ..
	    fi
	    cd ..
	done
	;;
esac

#
# create the SVR4 package
#
${BUILD}/create_pkg ${PKGNAME} ${BDIR} ${BROOT}

# remove our temporary files
rm -fr ${BDIR}
