#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# does a git clone and saves it as an archive
# unfortunately all version information is lost
#
THOME=${THOME:-/packages/localsrc/Tribblix}
SRCDIR="${THOME}/tarballs"
GIT="/usr/bin/git"

case $# in
    1)
	RURL="$1"
	;;
    *)
	echo "Usage: $0 git-repo"
	exit 1
	;;
esac

RNAME=${RURL##*/}
rm -fr "$RNAME"
$GIT clone "$RURL"
rm -fr "${RNAME}/.git"
rm -f "${SRCDIR}"/"${RNAME}".tar.* "${SRCDIR}/${RNAME}.zip"
tar cf "${SRCDIR}/${RNAME}.tar" "${RNAME}"
pbzip2 "${SRCDIR}/${RNAME}.tar"
rm -fr "${RNAME}"
