#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# clones an overlay repo; copies all the overlays listed in the
# catalog at their current versions
#

SRCDIR="$1"

if [ ! -f "${SRCDIR}/catalog" ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

awk -F'|' '{print $1}' "${SRCDIR}/catalog" | while read -r ovl
do
  if [ ! -f "${SRCDIR}/${ovl}.ovl" ]; then
    echo "ERROR: ${ovl}.ovl missing"
  else
     cp -p "${SRCDIR}/${ovl}.ovl" .
  fi
  if [ ! -f "${SRCDIR}/${ovl}.pkgs" ]; then
    echo "ERROR: ${ovl}.pkgs missing"
  else
     cp -p "${SRCDIR}/${ovl}.pkgs" .
  fi
done
cp "${SRCDIR}/catalog" .
