#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# clones a repo; hardlinks all the packages listed in the
# catalog at their current versions
#

SRCDIR="$1"

if [ ! -f "${SRCDIR}/catalog" ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

awk -F'|' '{print $1,$2}' "${SRCDIR}/catalog" | while read -r pkg ver
do
  if [ ! -f "${SRCDIR}/${pkg}.${ver}.zap" ]; then
    echo "ERROR: ${pkg}.${ver}.zap missing"
  else
     ln "${SRCDIR}/${pkg}.${ver}.zap" .
  fi
  if [ -f "${SRCDIR}/${pkg}.${ver}.zap.sig" ]; then
     ln "${SRCDIR}/${pkg}.${ver}.zap.sig" .
  fi
done
cp "${SRCDIR}/catalog" "${SRCDIR}/aliases" "${SRCDIR}/index.html" "${SRCDIR}/filelist.bz2" .
