#!/bin/sh
#
# clones an overlay repo; copies all the overlays listed in the
# catalog at their current versions
#

SRCDIR="$1"

if [ ! -f ${SRCDIR}/catalog ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

cat ${SRCDIR}/catalog | awk -F'|' '{print $1}' | while read ovl
do
  if [ ! -f ${SRCDIR}/${ovl}.ovl ]; then
    echo "ERROR: ${ovl}.ovl missing"
  else
     cp -p ${SRCDIR}/${ovl}.ovl .
  fi
  if [ ! -f ${SRCDIR}/${ovl}.pkgs ]; then
    echo "ERROR: ${ovl}.pkgs missing"
  else
     cp -p ${SRCDIR}/${ovl}.pkgs .
  fi
done
cp ${SRCDIR}/catalog .
