#!/bin/sh
#
# clones a repo; hardlinks all the packages listed in the
# catalog at their current versions
#

SRCDIR="$1"

if [ ! -f ${SRCDIR}/catalog ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

cat ${SRCDIR}/catalog | awk -F'|' '{print $1,$2}' | while read pkg ver
do
  if [ ! -f ${SRCDIR}/${pkg}.${ver}.zap ]; then
    echo "ERROR: ${pkg}.${ver}.zap missing"
  else
     ln ${SRCDIR}/${pkg}.${ver}.zap .
  fi
  if [ -f ${SRCDIR}/${pkg}.${ver}.zap.sig ]; then
     ln ${SRCDIR}/${pkg}.${ver}.zap.sig .
  fi
done
cp ${SRCDIR}/catalog ${SRCDIR}/aliases ${SRCDIR}/index.html ${SRCDIR}/filelist.bz2 .
