#!/bin/sh
#
# generate a merged list of dependencies for the given overlay(s)
#

#
VERBOSE=""
case $1 in
-v)
    # must come first, and pass it on
    VERBOSE="-v"
    shift
    ;;
esac

case $1 in
-a)
    # look for all overlays
    for pkg in `ls -1 *.pkgs | sed s:.pkgs::`
    do
	$0 $VERBOSE $pkg
    done
    exit 0
    ;;
-f)
    # useful for overlays.iso
    if [ -f $2 ]; then
	for pkg in `cat $2`
	do
	    $0 $VERBOSE $pkg
	done
    else
	echo "Missing file $2"
    fi
    exit 0
    ;;
esac

case $# in
1)
	OVL="$1"
	;;
*)
	echo "Usage: $0 [-v] -a|overlay|-f listfile"
	exit 1
	;;
esac
if [ ! -f "${OVL}.pkgs" ]; then
    echo "ERROR: unable to find overlay $OVL"
    exit 1
fi
TMPF=/tmp/ovtmp.$$
rm -f $TMPF
touch $TMPF
for PKGI in `cat ${OVL}.pkgs`
do
  if [ -f ../build/${PKGI}/depend ]; then
     grep '^P' ../build/${PKGI}/depend >> $TMPF
  fi
  if [ ! -d ../build/${PKGI} ]; then
      if [ -f /var/sadm/pkg/${PKGI}/install/depend ] ; then
	  grep '^P' /var/sadm/pkg/${PKGI}/install/depend >> $TMPF
      fi
  fi
done
#
# fix up errant legacy dependencies
#
sed -i '/TRIBsys-lib-gcc-3-runtime/d' $TMPF
sed -i '/TRIBperl-510/d' $TMPF
sed -i 's:TRIBsys-lib-c++-sunpro:TRIBsys-lib-cpp-sunpro:' $TMPF
##
## This is only useful for debug
##
##echo "Overlay ${OVL} depends on:"
##echo "============================================="
##cat $TMPF|awk '{print $2}' |sort|uniq | /usr/bin/fgrep -v -f ${OVL}.pkgs
#
# find any dependencies that aren't handled by prerequisite overlays
#
touch ${TMPF}.p
for POVL in base `grep '^REQUIRES=' ${OVL}.ovl | awk -F= '{print $2}'`
do
  cat ${POVL}.pkgs >> ${TMPF}.p
  for PPOVL in base `grep '^REQUIRES=' ${POVL}.ovl | awk -F= '{print $2}'`
  do
    cat ${PPOVL}.pkgs >> ${TMPF}.p
    for PPPOVL in base `grep '^REQUIRES=' ${PPOVL}.ovl | awk -F= '{print $2}'`
    do
      cat ${PPPOVL}.pkgs >> ${TMPF}.p
      for PPPPOVL in base `grep '^REQUIRES=' ${PPPOVL}.ovl | awk -F= '{print $2}'`
      do
        cat ${PPPPOVL}.pkgs >> ${TMPF}.p
      done
    done
  done
done
cat ${TMPF}.p |sort|uniq >${TMPF}.t
OUTMISS=`cat $TMPF|awk '{print $2}' |sort|uniq | /usr/bin/fgrep -v -x -f ${OVL}.pkgs| /usr/bin/fgrep -v -x -f ${TMPF}.t`
if [ -n "${OUTMISS}" ]; then
    echo ""
    echo "Missing dependencies in overlay ${OVL}:"
    echo "============================================="
    cat $TMPF|awk '{print $2}' |sort|uniq | /usr/bin/fgrep -v -x -f ${OVL}.pkgs| /usr/bin/fgrep -v -x -f ${TMPF}.t
fi

if [ "X$VERBOSE" = "X-v" ]; then
for ndep in `cat $TMPF|awk '{print $2}' |sort|uniq | /usr/bin/fgrep -v -f ${OVL}.pkgs| /usr/bin/fgrep -v -f ${TMPF}.t`
do
for PKGI in `cat ${OVL}.pkgs`
do
  if [ -f ../build/${PKGI}/depend ]; then
     grep -w $ndep ../build/${PKGI}/depend /dev/null
  fi
  if [ ! -d ../build/${PKGI} ]; then
      if [ -f /var/sadm/pkg/${PKGI}/install/depend ] ; then
	  grep -w $ndep /var/sadm/pkg/${PKGI}/install/depend /dev/null
      fi
  fi
done
done
fi

rm -f $TMPF ${TMPF}.t ${TMPF}.p
