#!/bin/sh
#
# generate a merged list of dependencies for the given overlay
#
case $# in
1)
	OVL="$1"
	;;
*)
	echo "Usage: $0 overlay"
	exit 1
	;;
esac
if [ ! -f "${OVL}.pkgs" ]; then
    echo "ERROR: unable to find overlay $OVL"
    exit 1
fi
TMPF=/tmp/ovtmp.$$
rm -f $TMPF
touch $TMPF
for PKGI in `cat ${OVL}.pkgs`
do
  if [ -f ../build/${PKGI}/depend ]; then
     cat ../build/${PKGI}/depend >> $TMPF
  fi
done
cat $TMPF|awk '{print $2}' |sort|uniq | /usr/bin/fgrep -v -f ${OVL}.pkgs
rm -f $TMPF
