#!/bin/sh
#
# generate a merged list of dependencies for the given overlay(s)
#

THOME=${THOME:-/packages/localsrc/Tribblix}
#
# xref against this illumos catalog
#
ILVER=m28
case `pwd` in
    *lx)
	ILVER=m28lx
	;;
    *sparc)
	ILVER=m20.6.sparc
	;;
esac
CATALOG=${THOME}/illumos-pkgs-${ILVER}/pkgs/catalog

#
VERBOSE=""
case $1 in
-v)
    # must come first, and pass it on
    VERBOSE="-v"
    shift
    ;;
esac

case $1 in
-a)
    # look for all overlays
    for pkg in `ls -1 *.pkgs | sed s:.pkgs::`
    do
	$0 $VERBOSE $pkg
    done
    exit 0
    ;;
-f)
    # useful for overlays.iso
    if [ -f $2 ]; then
	for pkg in `cat $2`
	do
	    $0 $VERBOSE $pkg
	done
    else
	echo "Missing file $2"
    fi
    exit 0
    ;;
esac

case $# in
1)
	OVL="$1"
	;;
*)
	echo "Usage: $0 [-v] -a|overlay|-f listfile"
	exit 1
	;;
esac
if [ ! -f "${OVL}.pkgs" ]; then
    echo "ERROR: unable to find overlay $OVL"
    exit 1
fi
TMPF=/tmp/ovtmp.$$
rm -f $TMPF
touch $TMPF
for PKGI in `cat ${OVL}.pkgs`
do
  if [ -f ../build/${PKGI}/depend ]; then
     grep '^P' ../build/${PKGI}/depend >> $TMPF
  fi
  if [ ! -d ../build/${PKGI} ]; then
      for npkgi in $(awk -v p=$PKGI -F'|' '{if ($1 == p) print $3}' $CATALOG)
      do
	  echo "P $npkgi" >> $TMPF
      done
  fi
done
#
# find any dependencies that aren't handled by prerequisite overlays
#
touch ${TMPF}.p
for POVL in base `awk -F= '{if ($1 == "REQUIRES") print $2}' ${OVL}.ovl`
do
  cat ${POVL}.pkgs >> ${TMPF}.p
  for PPOVL in `awk -F= '{if ($1 == "REQUIRES") print $2}' ${POVL}.ovl`
  do
    cat ${PPOVL}.pkgs >> ${TMPF}.p
    for PPPOVL in `awk -F= '{if ($1 == "REQUIRES") print $2}' ${PPOVL}.ovl`
    do
      cat ${PPPOVL}.pkgs >> ${TMPF}.p
      for PPPPOVL in `awk -F= '{if ($1 == "REQUIRES") print $2}' ${PPPOVL}.ovl`
      do
        cat ${PPPPOVL}.pkgs >> ${TMPF}.p
      done
    done
  done
done
sort -u ${TMPF}.p > ${TMPF}.t
OUTMISS=`awk '{print $2}' $TMPF | sort -u | /usr/bin/fgrep -v -x -f ${OVL}.pkgs| /usr/bin/fgrep -v -x -f ${TMPF}.t`
if [ -n "${OUTMISS}" ]; then
    echo ""
    echo "Missing dependencies in overlay ${OVL}:"
    echo "============================================="
    awk '{print $2}' $TMPF | sort -u | /usr/bin/fgrep -v -x -f ${OVL}.pkgs| /usr/bin/fgrep -v -x -f ${TMPF}.t
fi

if [ "X$VERBOSE" = "X-v" ]; then
for ndep in `awk '{print $2}' $TMPF | sort -u | /usr/bin/fgrep -v -f ${OVL}.pkgs| /usr/bin/fgrep -v -f ${TMPF}.t`
do
for PKGI in `cat ${OVL}.pkgs`
do
  if [ -f ../build/${PKGI}/depend ]; then
     grep -w $ndep ../build/${PKGI}/depend /dev/null
  fi
  if [ ! -d ../build/${PKGI} ]; then
      egrep "( |\|)${ndep}( |\|)" $CATALOG | awk -v p=$PKGI -F'|' '{if ($1 == p) print $1" : " $3}'
  fi
done
done
fi

rm -f $TMPF ${TMPF}.t ${TMPF}.p
