#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# convert an svr4 package (in datastream format) into zap format
#
case $# in
2)
	FPKG="$1"
	BROOT="$2"
	;;
*)
	echo "Usage: $0 input_pkg output_dir"
	exit 2
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"

#
# sanity check
#
if [ ! -d "$BUILD" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi

if [ ! -f "$FPKG" ]; then
   echo "ERROR: input file not found"
   exit 1
fi

if [ "${FPKG:0:1}" != / ]; then
    echo "Input file must have absolute path"
    exit 1
fi

if [ ! -d "$BROOT" ]; then
   echo "ERROR: output directory not found"
   exit 1
fi

# uncompress compressed packages
BPKG=${FPKG##*/}
TDIR=/tmp/pkg2zap.$(date '+%F-%T').$$
rm -fr "$TDIR"
mkdir -p "$TDIR"

case $FPKG in
    *.gz)
	ZPNAME=${BPKG%.gz}
	gzcat "$FPKG" > "${TDIR}/${ZPNAME}"
	FPKG="${TDIR}/${ZPNAME}"
	BPKG=${FPKG##*/}
	;;
    *.bz2)
	ZPNAME=${BPKG%.bz2}
	bzcat "$FPKG" > "${TDIR}/${ZPNAME}"
	FPKG="${TDIR}/${ZPNAME}"
	BPKG=${FPKG##*/}
	;;
esac

pkgtrans "$FPKG" "$TDIR" all
cd "$TDIR" || exit 1
# remove an uncompressed pkg file if there is one
rm -f "$BPKG"

PNAME=${BPKG%.pkg}
# 7z gives us an extra 2-3% reduction in file size
#zip -9 -q -r ${BROOT}/${BPKG%.pkg}.zap *
7za a -tzip -mx=9 -mfb=256 "${BROOT}/${PNAME}.zap" *
chmod a+r "${BROOT}/${PNAME}.zap"
cd /
# pregenerate the md5 checksum ready for catalog creation
openssl md5 "${BROOT}/${PNAME}.zap" | /usr/bin/awk '{print $NF}' > "${BROOT}/${PNAME}.zap.md5"
# sign the zap file
"${BUILD}"/sign-file "${BROOT}/${PNAME}.zap"

#
# clean up
#
rm -fr "$TDIR"
ls -lh "${BROOT}/${PNAME}.zap"
