#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 202 Peter Tribble
#

#
# fix environment
#
LC_ALL=C
export LC_ALL
TZ=UTC
export TZ

#
# package one or more python project(s) that use the old setup.py mechanism
#

while [[ $# -gt 0 ]]; do
case $1 in
    -v)
	SPYVER=$2
	shift
	shift
	;;
    -gnu)
	PATH=/usr/gnu/bin:$PATH
	export PATH
	shift
	;;
    -*)
	echo "ERROR: invalid option $1"
	exit 1
	;;
    *)
	break
	;;
esac
done

case $# in
0|1)
	echo "Usage: $0 pkg_name tar_file"
	exit 1
	;;
*)
	PKGNAME="$1"
	shift
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"
BROOT="/tmp/pct"

#
# verify that our arguments refer to a package and to a file
#
if [ ! -d "$BUILD" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi
if [ ! -f "${BUILD}/${PKGNAME}/pkginfo" ]; then
   echo "ERROR: missing package data"
   echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
   exit 1
fi

#
# sanity check to avoid messing up a repo
#
if [ -d .git ]; then
    echo "ERROR: cannot run in a git repo"
    exit 1
fi

if [ ! -d "$BROOT" ]; then
    mkdir -p "$BROOT"
fi
if [ ! -d "$BROOT" ]; then
   echo "ERROR: unable to find temporary directory $BROOT"
   exit 1
fi

#
# derive the python version from the package name, if we weren't given it
#
if [ -z "$SPYVER" ]; then
    SPYVER=${PKGNAME##*-}
fi
#
# we assume it has to be 3.X
#
case $SPYVER in
    311)
	PYVER=3.11
	;;
    312)
	PYVER=3.12
	;;
    *)
	echo "Unrecognised python version $SPYVER"
	exit 1
	;;
esac

#
# all pythons are 64-bit, so we must always set a 64-bit
# version of PKG_CONFIG_PATH
#
PKG_CONFIG_PATH=/usr/lib/$("${THOME}"/build/getarch)/pkgconfig
#
# if we want to add something to PKG_CONFIG_PATH
#
if [ -n "${TRIBBLIX_PKG_CONFIG_PATH}" ]; then
    PKG_CONFIG_PATH="${TRIBBLIX_PKG_CONFIG_PATH}:${PKG_CONFIG_PATH}"
fi
export PKG_CONFIG_PATH

#
# define and create working location
#
BDIR="${BROOT}/pkg.$$"
rm -fr ${BDIR}

#
# loop over arguments
#
for PFILE in "$@"
do
#
# unpack
#
"${BUILD}/unpack" "${PFILE}"
case $PFILE in
    https://*)
	PFILE=${PFILE##*/}
	PFILE=${PFILE%.git}
	;;
esac
if [ ! -d "${PFILE}" ]; then
    echo "Missing source directory $PFILE"
    exit 1
fi
cd "${PFILE}" || exit 1
if [ ! -f setup.py ]; then
    echo "No setup.py, is this really a python project?"
    exit 1
fi
#
# any preconf actions run here
#
if [ -x "${BUILD}/patches/${PFILE}.preconf" ]; then
    "${BUILD}/patches/${PFILE}.preconf"
fi
#
# build and install using setup.py
#
python${PYVER} setup.py build
python${PYVER} setup.py install --no-compile --root="${BDIR}"
#
# run fixinstall here, while we're still cd'ed into the module
#
if [ -x "${BUILD}/${PKGNAME}/fixinstall" ]; then
    "${BUILD}/${PKGNAME}/fixinstall" $BDIR
fi
cd ..
#
# end loop
#
done

#
# compile separately, to avoid install paths and timestamps ending up
# embedded in pyc files
#
# force unchecked-hash to ensure that nothing, even as root, will ever
# try to recompile and overwrite packaged pyc files
#
python${PYVER} -m compileall -f -p / -s "${BDIR}" --invalidation-mode unchecked-hash "${BDIR}/usr/versions/python-${PYVER}/lib/python${PYVER}/site-packages"

"${BUILD}/create_pkg" "${PKGNAME}" "${BDIR}" "${BROOT}"
cd /

#
# some setup.py packages need to be handled differently
#
badfiles=$(find ${BDIR} -name '*UNKNOWN*')
if [ -n "${badfiles}" ]; then
   echo "ERROR: some files match \"UNKNOWN\", consider using pkg_pep518"
fi

# remove our temporary files
rm -fr "${BDIR}"
