#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# fix environment
#
LC_ALL=C
export LC_ALL
TZ=UTC
export TZ

#
# package one or more python project(s) directly from a downloaded
# wheel (see pkg_pep518 for one that creates the wheel from source)
#

#
# Arguments
# -v - specify version of python (for packages that don't embed the python
#      version in the package name)
#
while getopts "v:" opt; do
    case $opt in
	v)
	    SPYVER="$OPTARG"
	    ;;
	*)
            echo "ERROR: invalid option $OPTARG"
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

case $# in
0|1)
	echo "Usage: $0 pkg_name tar_file"
	exit 1
	;;
*)
	PKGNAME="$1"
	shift
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"
BROOT="/tmp/pct"

#
# verify that our arguments refer to a package
#
if [ ! -d "$BUILD" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi
if [ ! -f "${BUILD}/${PKGNAME}/pkginfo" ]; then
   echo "ERROR: missing package data"
   echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
   exit 1
fi

#
# sanity check to avoid messing up a repo
#
if [ -d .git ]; then
    echo "ERROR: cannot run in a git repo"
    exit 1
fi

if [ ! -d "$BROOT" ]; then
    mkdir -p "$BROOT"
fi
if [ ! -d "$BROOT" ]; then
   echo "ERROR: unable to find temporary directory $BROOT"
   exit 1
fi

#
# derive the python version from the package name, if we weren't given it
#
if [ -z "$SPYVER" ]; then
    SPYVER=${PKGNAME##*-}
fi
#
# we assume it has to be 3.X
#
case $SPYVER in
    312)
	PYVER=3.12
	;;
    313)
	PYVER=3.13
	;;
    314)
	PYVER=3.14
	;;
    *)
	echo "Unrecognised python version $SPYVER"
	exit 1
	;;
esac

#
# define and create working location
#
BDIR="${BROOT}/pkg.$$"
rm -fr ${BDIR}

#
# loop over arguments
#
for PFILE in "$@"
do

if [ ! -f "${THOME}/tarballs/${PFILE}" ]; then
    echo "Missing source wheel $PFILE"
    exit 1
fi
#
# no preconf or fixinstall possible for ready-built wheels
#
#
# use pip to install
#
python${PYVER} -mpip install --no-deps --isolated --no-input --exists-action=a --disable-pip-version-check --no-compile --no-warn-script-location --root="${BDIR}" -I "${THOME}/tarballs/${PFILE}"
#
# end loop
#
done

#
# we delete direct_url.json, as it contains the build location which makes
# the package non-reproducible, and makes a mess of `pip freeze`
#
find "${BDIR}/usr/versions/python-${PYVER}/lib/python${PYVER}/site-packages" -name direct_url.json -exec rm {} \;
sed -i '/\/direct_url.json,sha/d' $(find "${BDIR}/usr/versions/python-${PYVER}/lib/python${PYVER}/site-packages" -name RECORD)

#
# compile separately, to avoid install paths and timestamps ending up
# embedded in pyc files
#
# force unchecked-hash to ensure that nothing, even as root, will ever
# try to recompile and overwrite packaged pyc files
#
python${PYVER} -m compileall -f -p / -s "${BDIR}" --invalidation-mode unchecked-hash "${BDIR}/usr/versions/python-${PYVER}/lib/python${PYVER}/site-packages"

"${BUILD}/create_pkg" "${PKGNAME}" "${BDIR}" "${BROOT}"
cd /

# remove our temporary files
rm -fr "${BDIR}"
