#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# fix environment
#
LC_ALL=C
export LC_ALL
TZ=UTC
export TZ

#
# package something that's already a tarball, assumed to be into
# its named subdirectory of /usr/versions (or /opt/tribblix if the
# -T flag is supplied, or wherever using -P)
#
STD_DESTINATION="usr/versions"
case $1 in
-T)
    STD_DESTINATION="opt/tribblix"
    shift
    ;;
-P)
    STD_DESTINATION="$2"
    shift
    shift
    ;;
esac

case $# in
2)
        SOFTDIR="$2"
        PKGNAME="$1"
	;;
*)
	echo "Usage: $0 [-T] pkg_name file_root"
	exit 1
	;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"
BROOT="/tmp/pct"

if [ ! -d "${BUILD}" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi
if [ ! -d "${BROOT}" ]; then
    mkdir -p "${BROOT}"
fi
if [ ! -d "${BROOT}" ]; then
   echo "ERROR: unable to find temporary directory $BROOT"
   exit 1
fi
if [ ! -f "${BUILD}/${PKGNAME}/pkginfo" ]; then
   echo "ERROR: missing package data"
   echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
   exit 1
fi

#
# sanity check to avoid messing up a repo
#
if [ -d .git ]; then
    echo "ERROR: cannot run in a git repo"
    exit 1
fi

#
# define and create working location
#
BDIR="${BROOT}/pkg.$$"
rm -fr "${BDIR}"
mkdir -p "${BDIR}/${STD_DESTINATION}"
cd "${BDIR}/${STD_DESTINATION}" || exit 1

"${BUILD}/unpack" "${SOFTDIR}"
"${BUILD}/create_pkg" "${PKGNAME}" "${BDIR}" "${BROOT}"
cd /

# remove our temporary files
rm -fr "${BDIR}"
rm -fr "${BROOT}/${PKGNAME}"
