#!/bin/sh
#
# simple wrapper to create a package
#
# you may need to modify the depend file
# and add the ZAP_URL to pkginfo
#

case $1 in
-64)
	XFLAGS="-64 "
	shift
	;;
+64)
	XFLAGS="+64 "
	shift
	;;
-64only)
	XFLAGS="-64only "
	shift
	;;
+64only)
	XFLAGS="+64only "
	shift
	;;
esac

case $# in
2)
	pkg_name=$1
	TBALL=$2
	;;
*)
	echo "Usage: $0 [-64|+64|-64only|+64only] pkg_name tarball_name"
	exit 1
	;;
esac

PNAME=TRIB${pkg_name}

if [ -d "$PNAME" ]; then
   echo "$PNAME already exists"
   exit 1
fi

#
# guess the version from the filename
#
PVER=${TBALL##*-}

#
# OK, now we can create the package metadata
#

mkdir $PNAME
cat > $PNAME/pkginfo <<EOF
PKG="${PNAME}"
NAME="$pkg_name"
VERSION="${PVER}.0"
EOF
cat > $PNAME/build.sh <<EOF
#!/bin/sh
#
\${THOME}/build/dobuild ${XFLAGS}$TBALL
\${THOME}/build/genpkg $PNAME $TBALL
EOF
chmod a+x $PNAME/build.sh

echo "Now check $PNAME/pkginfo"
echo "After building, check $PNAME/depend"
