#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# simple wrapper to create a package
#
# you may need to modify the depend file
# and add the ZAP_URL to pkginfo
#

#
# flags
# -c cmake style (cmbuild)
# -d autoconf style (dobuild, the default)
# -m meson style (mesonbuild)
#
BUILDER="dobuild"
while getopts "cdm" opt; do
    case $opt in
    c)
	BUILDER="cmbuild"
	shift
	;;
    d)
	BUILDER="dobuild"
	shift
	;;
    m)
	BUILDER="mesonbuild"
	shift
	;;
    esac
done

case $1 in
-64)
	XFLAGS="-64 "
	shift
	;;
+64)
	XFLAGS="+64 "
	shift
	;;
-64only)
	XFLAGS="-64only "
	shift
	;;
+64only)
	XFLAGS="+64only "
	shift
	;;
esac

case $# in
2)
	pkg_name=$1
	TBALL=$2
	;;
*)
	echo "Usage: $0 [-c|-d|-m] [-64|+64|-64only|+64only] pkg_name tarball_name"
	exit 1
	;;
esac

case ${pkg_name} in
    TRIB*)
	PNAME=${pkg_name}
	;;
    *)
	PNAME=TRIB${pkg_name}
	;;
esac

if [ -d "$PNAME" ]; then
   echo "$PNAME already exists"
   exit 1
fi

#
# guess the version from the filename
#
PVER=${TBALL##*-}

#
# OK, now we can create the package metadata
#

mkdir "$PNAME"
cat > "$PNAME/pkginfo" <<EOF
PKG="${PNAME}"
NAME="$pkg_name"
VERSION="${PVER}.0"
EOF
cat > "$PNAME/build.sh" <<EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
\${THOME}/build/${BUILDER} ${XFLAGS}$TBALL
\${THOME}/build/genpkg $PNAME $TBALL
EOF
chmod a+x "$PNAME/build.sh"

case $BUILDER in
    cmbuild)
	echo "TRIBcmake" > "$PNAME/build_require"
	;;
    mesonbuild)
	echo "TRIBmeson-python-312" > "$PNAME/build_require"
	echo "TRIBninja" >> "$PNAME/build_require"
	;;
esac

echo "Now check $PNAME/pkginfo"
echo "After building, check $PNAME/depend"
