#!/bin/sh
#
# simple wrapper to create python module metadata
#
# you may need to modify the depend file
#

#
# by default, package for 3.9, other versions optional
#

PY39VER=39
PY39DVER=3.9
PY311VER=311
PY311DVER=3.11

DO39="yes"
DO311="yes"
case $1 in
    -39)
	DO39=""
	shift
	;;
esac
case $1 in
    -311)
	DO311=""
	shift
	;;
esac

case $1 in
    -p)
	BUILDER=pkg_pep518
	shift
	;;
    -s)
	BUILDER=pkg_setup_py
	shift
	;;
    *)
	echo "Usage: $0 [-39|-311] -s|-p pkg_name tarball_name"
	exit 1
	;;
esac

case $# in
2)
	pkg_name=$1
	TBALL=$2
	;;
*)
	echo "Usage: $0 -s|-p pkg_name tarball_name"
	exit 1
	;;
esac

PY39NAME=TRIB${pkg_name}-python-${PY39VER}
PY311NAME=TRIB${pkg_name}-python-${PY311VER}

#
# check we're within the SVR4 package name length limit
# use the 3.11 name, as it's the longest, even if we don't use it
#
NAMELEN=$(echo $PY311NAME|wc -c)
if [ $NAMELEN -gt 31 ]; then
    echo "Chosen name exceeds the SVR4 package name length limit (length $NAMELEN)"
    exit 1
fi

if [ -d "$PY39NAME" ]; then
   echo "$PY39NAME already exists"
   exit 1
fi
if [ -d "$PY311NAME" ]; then
   echo "$PY311NAME already exists"
   exit 1
fi

#
# the pypi name ought to match the tarball name
# with the version number stripped off
#
PNAME=${TBALL%-*}
PVER=${TBALL##*-}

#
# OK, now we can create the package metadata
#

if [ -n "$DO39" ]; then
#
# python 3.9
#
mkdir $PY39NAME
echo "P TRIBv-python-$PY39VER" > $PY39NAME/depend
cat > $PY39NAME/pkginfo <<EOF
PKG="${PY39NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}"
EOF
cat > $PY39NAME/build.sh <<EOF
#!/bin/sh
#
\${THOME}/build/$BUILDER $PY39NAME $TBALL
EOF
chmod a+x $PY39NAME/build.sh
fi

if [ -n "$DO311" ]; then
#
# python 3.11
#
mkdir $PY311NAME
echo "P TRIBv-python-$PY311VER" > $PY311NAME/depend
cat > $PY311NAME/pkginfo <<EOF
PKG="${PY311NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}"
EOF
cat > $PY311NAME/build.sh <<EOF
#!/bin/sh
#
\${THOME}/build/$BUILDER $PY311NAME $TBALL
EOF
chmod a+x $PY311NAME/build.sh
fi
