#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# simple wrapper to create python module metadata
#
# you may need to modify the depend file
#

#
# package for 3.12 by default, but have code for 3.13 and 3.14
#

PY312VER=312
PY313VER=313
PY314VER=314

DO312="yes"
DO313=""
DO314=""

case $1 in
    -p)
	BUILDER=pkg_pep518
	shift
	;;
    -w)
	BUILDER=pkg_wheel
	PKGVERS=$2
	shift
	shift
	;;
    *)
	echo "Usage: $0 -p pkg_name tarball_name"
	echo "       $0 -w pkg_version pkg_name tarball_name"
	exit 1
	;;
esac

case $# in
2)
	pkg_name=$1
	TBALL=$2
	;;
*)
	echo "Usage: $0 -p pkg_name tarball_name"
	echo "       $0 -w pkg_version pkg_name tarball_name"
	exit 1
	;;
esac

PY312NAME=TRIB${pkg_name}-python-${PY312VER}
PY313NAME=TRIB${pkg_name}-python-${PY313VER}
PY314NAME=TRIB${pkg_name}-python-${PY314VER}

#
# check we're within the SVR4 package name length limit
#
NAMELEN=${#PY312NAME}
if [ "$NAMELEN" -gt 31 ]; then
    echo "Chosen name exceeds the SVR4 package name length limit (length $NAMELEN)"
    exit 1
fi

if [ -n "$DO312" ]; then
    if [ -d "$PY312NAME" ]; then
	echo "$PY312NAME already exists"
	exit 1
    fi
fi
if [ -n "$DO313" ]; then
    if [ -d "$PY313NAME" ]; then
	echo "$PY313NAME already exists"
	exit 1
    fi
fi
if [ -n "$DO314" ]; then
    if [ -d "$PY314NAME" ]; then
	echo "$PY314NAME already exists"
	exit 1
    fi
fi

#
# the pypi name ought to match the tarball name
# with the version number stripped off
#
PNAME=${TBALL%-*}
PVER=${TBALL##*-}

#
# for wheels it's a bit more complicated to guess the version from the file
# so we're passed the version explicitly
#
if [ -n "${PKGVERS}" ]; then
    PVER=${PKGVERS}
    PNAME=${TBALL%-${PVER}*}
fi

#
# often, the tarball name uses underscores whereas the project name might have
# regular dashes, so convert
#
PNAME=${PNAME//_/-}

#
# OK, now we can create the package metadata
#

if [ -n "$DO312" ]; then
#
# python 3.12
#
mkdir "$PY312NAME"
echo "P TRIBv-python-$PY312VER" > "$PY312NAME/depend"
cat > "$PY312NAME/pkginfo" <<EOF
PKG="${PY312NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}/"
EOF
cat > "$PY312NAME/build.sh" <<EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
\${THOME}/build/$BUILDER $PY312NAME $TBALL
EOF
chmod a+x "$PY312NAME/build.sh"
fi

if [ -n "$DO313" ]; then
#
# python 3.13
#
mkdir "$PY313NAME"
echo "P TRIBv-python-$PY313VER" > "$PY313NAME/depend"
cat > "$PY313NAME/pkginfo" <<EOF
PKG="${PY313NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}/"
EOF
cat > "$PY313NAME/build.sh" <<EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
\${THOME}/build/$BUILDER $PY313NAME $TBALL
EOF
chmod a+x "$PY313NAME/build.sh"
case $BUILDER in
    pkg_pep518)
	echo "TRIBpip-python-313" > "$PY313NAME/build_require"
	;;
esac
fi

if [ -n "$DO314" ]; then
#
# python 3.14
#
mkdir "$PY314NAME"
echo "P TRIBv-python-$PY314VER" > "$PY314NAME/depend"
cat > "$PY314NAME/pkginfo" <<EOF
PKG="${PY314NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}/"
EOF
cat > "$PY314NAME/build.sh" <<EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
\${THOME}/build/$BUILDER $PY314NAME $TBALL
EOF
chmod a+x "$PY314NAME/build.sh"
case $BUILDER in
    pkg_pep518)
	echo "TRIBpip-python-314" > "$PY314NAME/build_require"
	;;
esac
fi
