#!/bin/sh
#
# simple wrapper to create python module metadata
#
# you may need to modify the depend file
#

PY2VER=27
PY37VER=37
PY37DVER=3.7

case $# in
2)
	pkg_name=$1
	TBALL=$2
	;;
*)
	echo "Usage: $0 pkg_name tarball_name"
	exit 1
	;;
esac

PY2NAME=TRIB${pkg_name}-python-${PY2VER}
PY37NAME=TRIB${pkg_name}-python-${PY37VER}

if [ -d "$PY2NAME" ]; then
   echo "$PY2NAME already exists"
   exit 1
fi
if [ -d "$PY37NAME" ]; then
   echo "$PY37NAME already exists"
   exit 1
fi

#
# the pypi name ought to match the tarball name
# with the version number stripped off
#
PNAME=${TBALL%-*}
PVER=${TBALL##*-}

#
# OK, now we can create the package metadata
#

#
# python 2.7
#
mkdir $PY2NAME
echo "P TRIBv-python-$PY2VER" > $PY2NAME/depend
cat > $PY2NAME/pkginfo <<EOF
PKG="${PY2NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}"
EOF
cat > $PY2NAME/build.sh <<EOF
#!/bin/sh
#
\${THOME}/build/unpack $TBALL
cd $TBALL
python setup.py build
rm -fr /tmp/pil
python setup.py install --root=/tmp/pil
\${THOME}/build/create_pkg $PY2NAME /tmp/pil
cd ..
rm -fr /tmp/pil
EOF
chmod a+x $PY2NAME/build.sh

#
# python 3.7
#
mkdir $PY37NAME
echo "P TRIBv-python-$PY37VER" > $PY37NAME/depend
cat > $PY37NAME/pkginfo <<EOF
PKG="${PY37NAME}"
NAME="Python $PNAME"
VERSION="${PVER}.0"
ZAP_URL="https://pypi.org/project/${PNAME}"
EOF
cat > $PY37NAME/build.sh <<EOF
#!/bin/sh
#
\${THOME}/build/unpack $TBALL
cd $TBALL
/usr/versions/python-${PY37DVER}/bin/python3 setup.py build
rm -fr /tmp/pil
/usr/versions/python-${PY37DVER}/bin/python3 setup.py install --root=/tmp/pil
\${THOME}/build/create_pkg $PY37NAME /tmp/pil
cd ..
rm -fr /tmp/pil
EOF
chmod a+x $PY37NAME/build.sh
