#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# sign all the given zap files
#

builtin echo

case $# in
0)
    echo "Usage: $0 file_name [...]"
    exit 1
    ;;
esac

if [ ! -f "${HOME}/Tribblix/Sign.phrase" ]; then
    echo "Missing passphrase, must sign packages manually"
    exit 1
fi

for PKG in "$@"
do
    if [ -f "${PKG}" ]; then
	echo ""
	echo "Signing ${PKG}"
	echo ""
	gpg --detach-sign --no-secmem-warning --passphrase-file "${HOME}/Tribblix/Sign.phrase" "${PKG}"
	if [ -f "${PKG}.sig" ]; then
	    echo "Package signed successfully."
	    echo ""
	fi
    else
	echo "ERROR: cannot find file $PKG"
    fi
done
