#!/bin/ksh
#
# this will sign every zap file in the given directory
#

builtin echo

case $# in
0)
    echo "Usage: $0 file_name [...]"
    exit 1
    ;;
esac

if [ ! -f ${HOME}/Tribblix/Sign.phrase ]; then
    echo "Missing passphrase, must sign packages manually"
    exit 1
fi

for PKG in $*
do
    if [ -f ${PKG} ]; then
	echo ""
	echo "Signing ${PKG}"
	echo ""
	gpg --detach-sign --no-secmem-warning --passphrase-file ${HOME}/Tribblix/Sign.phrase ${PKG}
	if [ -f ${PKG}.sig ]; then
	    echo "Package signed successfully."
	    echo ""
	fi
    else
	echo "ERROR: cannot find file $PKG"
    fi
done
