#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# this will sign every unsigned zap file in the given directory
#

builtin echo

case $# in
1)
    PKGDIR=$1
    ;;
*)
    echo "Usage: $0 pkg_directory"
    exit 1
    ;;
esac

#
# Default locations
#
THOME=${THOME:-/packages/localsrc/Tribblix}
BUILD="${THOME}/build"

if [ ! -d "$BUILD" ]; then
   echo "ERROR: unable to find build directory $BUILD"
   exit 1
fi

if [ ! -d "${PKGDIR}" ]; then
    echo "Cannot find $PKGDIR"
    exit 1
fi

cd "$PKGDIR" || exit
for PKG in *.zap
do
    if [ ! -f "${PKG}.sig" ]; then
	"${BUILD}"/sign-file "${PKG}"
    fi
done
