#!/bin/ksh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# this will sign every zap file in the given directory
#

builtin echo

case $# in
1)
    PKGDIR=$1
    ;;
*)
    echo "Usage: $0 pkg_directory"
    exit 1
    ;;
esac

if [ ! -f ${HOME}/Tribblix/Sign.phrase ]; then
    echo "Missing passphrase, must sign packages manually"
    exit 1
fi

if [ ! -d ${PKGDIR} ]; then
    echo "Cannot find $PKGDIR"
    exit 1
fi

cd $PKGDIR
for PKG in *.zap
do
    if [ ! -f ${PKG}.sig ]; then
	echo ""
	echo "Signing ${PKG}"
	echo ""
	gpg --detach-sign --no-secmem-warning --passphrase-file ${HOME}/Tribblix/Sign.phrase ${PKG}
	if [ -f ${PKG}.sig ]; then
	    echo "Package signed successfully."
	    echo ""
	fi
    fi
done
