#!/bin/sh
#
# unpack a source tarball, optionally creating a 64-bit build directory
# as well
#
# if a patchlist is found, apply patches from it
#
TOPDIR="/packages/localsrc/Tribblix"

SRCDIR="${TOPDIR}/tarballs"
PATCHDIR="${TOPDIR}/build/patches"

GZCAT="/usr/bin/gzcat"
BZCAT="/usr/bin/bzcat"
XZCAT="/usr/bin/xz"
UNZIP="/usr/bin/unzip"
GPATCH="/usr/bin/gpatch"
ZCAT="/usr/bin/zcat"
LZIP="/usr/bin/lzip"

DO32="true"
DO64="false"
case $1 in
-64)
	DO64="true"
	shift
	;;
+64)
	DO32="false"
	DO64="true"
	shift
	;;
esac

dopatch() {
  if [ -f ${PATCHDIR}/${1}.pls ]; then
      cd ${1}
      cat ${PATCHDIR}/${1}.pls | while read patcharg patchfile
      do
	  ${GPATCH} $patcharg -i ${PATCHDIR}/${patchfile}
      done
      cd ..
  fi
  if [ -f ${PATCHDIR}/${1}.pls.`uname -p` ]; then
      cd ${1}
      cat ${PATCHDIR}/${1}.pls.`uname -p` | while read patcharg patchfile
      do
	  ${GPATCH} $patcharg -i ${PATCHDIR}/${patchfile}
      done
      cd ..
  fi
}

for pkg in $*
do
	/usr/bin/rm -fr ${pkg} ${pkg}-64bit

	for filetype in \
			'.tar.Z' \
			'.tar.gz' \
			'.tgz' \
			'.src.tgz' \
			'.src.tar.gz' \
			'.tar.bz2' \
			'.tbz' \
			'-source.tar.bz2' \
			'.tar.xz' \
			'.source.tar.xz' \
			'.tar.lz' \
			'.tar'
        do
           if [ -f ${SRCDIR}/${pkg}${filetype} ]; then
              gtar axf ${SRCDIR}/${pkg}${filetype}
              dopatch ${pkg}
              if [ "x$DO64" != "xfalse" ]; then
                 mv ${pkg} ${pkg}-64bit
                 if [ "x$DO32" != "xfalse" ]; then
                     gtar axf ${SRCDIR}/${pkg}${filetype}
                     dopatch ${pkg}
                 fi
              fi
           fi
        done

	if [ -f ${SRCDIR}/${pkg}.zip ]; then
	   ${UNZIP} -q ${SRCDIR}/${pkg}.zip
	   dopatch ${pkg}
	   if [ "x$DO64" != "xfalse" ]; then
	      mv ${pkg} ${pkg}-64bit
	      if [ "x$DO32" != "xfalse" ]; then
		  ${UNZIP} -q ${SRCDIR}/${pkg}.zip
		  dopatch ${pkg}
	      fi
	   fi
	fi
done
