#!/bin/sh
#
# verify that packages listed as dependencies actually exist
#

#
# some packages depend explicitly on illumos
# which isn't present here, so try and catch those
# guess the version off the current host
#
ILVER=$(uname -v)
ILVER=${ILVER##tribblix-}
ILREL=${ILVER/m/}

if [ $# -gt 1 ]; then
    echo "Usage: $0 [illumos_version]"
    exit 2
fi

#
# if given an argument, use that as the illumos to check against
#
if [ $# -gt 0 ]; then
    ILVER=$1
    ILVER=${ILVER##tribblix-}
    ILREL=${ILVER/m/}
    ILREL=${ILREL/.sparc/}
fi
if [ ! -d ../illumos-pkgs-${ILVER}/pkgs ]; then
    echo "ERROR: no illumos packages for $ILVER"
    exit 2
fi

#
# just walk through all the depend files
#
for dep in `sort -u */depend | awk '{print $2}'`
do
    if [ ! -d $dep ]; then
	if [ ! -f ../illumos-pkgs-${ILVER}/pkgs/${dep}.0.${ILREL}.zap ]; then
	    echo "Missing dependency $dep"
	    grep -x "P ${dep}" */depend
	fi
    fi
done

#
# and build_require
#
for dep in `sort -u */build_require`
do
    if [ ! -d $dep ]; then
	if [ ! -f ../illumos-pkgs-${ILVER}/pkgs/${dep}.0.${ILREL}.zap ]; then
	    echo "Missing build_require $dep"
	    grep -x "${dep}" */build_require
	fi
    fi
done

#
# and check for blank lines
#
for dep in `grep '^[ ]*$' */depend */build_require`
do
    echo "Blank line in $dep"
done
