#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# verify there are no duplicate aliases
#
DUPS=$(sort */alias|uniq -d)
if [[ -n $DUPS ]]; then
    echo "ERROR: duplicates found for x86"
    sort */alias|uniq -d
fi

#
# now the platform variants
#
# what we have to do is remove the vanilla alias file from the list if
# there's a platform-specific one
#
PLATFORMS=$(ls -1d */alias.* | awk -F. '{print $NF}' | sort -u)
for PLAT in $PLATFORMS
do
    # exclude alias files for which there's a platform-specific one
    SRCH=$(echo */alias.$PLAT | sed -e s:\.${PLAT}::g -e 's: :|:g')
    # exclude alias files that don't apply to this platform
    LS2=$(ggrep -vl $PLAT */arch.txt)
    SRCH2=$(echo $LS2 | sed -e s:/arch.txt:/alias:g -e 's: :|:g')
    # simple grep is fine, the string is intrinsically anchored by the
    # leading TRIB prefix and the /alias on the end
    CFILES=$(ls -1d */alias | gegrep -v -e "(${SRCH})" -e "(${SRCH2})")
    DUPS=$(sort $CFILES */alias.${PLAT}|uniq -d)
    if [[ -n $DUPS ]]; then
	echo "ERROR: duplicates found for ${PLAT}"
	sort $CFILES */alias.${PLAT}|uniq -d
    fi
done

#
# now check there aren't any platform alias files if the platform is
# excluded by arch.txt
#
for PLAT in $PLATFORMS
do
    LS2=$(ggrep -vl "$PLAT" */arch.txt)
    for file in $LS2
    do
	if [ -f "${file/arch.txt/alias}.${PLAT}" ]; then
	    echo "ERROR: ${file/arch.txt/alias}.${PLAT} conflicts with arch.txt"
	fi
    done
done
