#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

#
# verify that packages listed as dependencies actually exist
#

#
# some packages depend explicitly on illumos
# which isn't present here, so try and catch those
# guess the version off the current host
#
ILVER=$(uname -v)
ILVER=${ILVER##tribblix-}
ILREL=${ILVER/m/}

if [ $# -gt 1 ]; then
    echo "Usage: $0 [illumos_version]"
    exit 2
fi

#
# if given an argument, use that as the illumos to check against
#
if [ $# -gt 0 ]; then
    ILVER=$1
    ILVER=${ILVER##tribblix-}
    ILREL=${ILVER/m/}
    ILREL=${ILREL/.sparc/}
fi
if [ ! -d "../illumos-pkgs-${ILVER}/pkgs" ]; then
    echo "ERROR: no illumos packages for $ILVER"
    exit 2
fi

#
# just walk through all the depend files
# if we can't find a dependency here, look for it in illumos
# and then in the old legacy opensxce
#
for dep in $(sort -u ./*/depend* | awk '{print $2}')
do
    if [ ! -d "$dep" ]; then
	if [ ! -f "../illumos-pkgs-${ILVER}/pkgs/${dep}.0.${ILREL}.zap" ]; then
	    if [ ! -f "../opensxce-pkgs/pkgs/${dep}.2014.zap" ]; then
		echo "Missing dependency $dep"
		grep -x "P ${dep}" ./*/depend*
	    fi
	fi
    fi
done

#
# and build_require
#
for dep in $(sort -u ./*/build_require*)
do
    if [ ! -d "$dep" ]; then
	if [ ! -f "../illumos-pkgs-${ILVER}/pkgs/${dep}.0.${ILREL}.zap" ]; then
	    echo "Missing build_require $dep"
	    grep -x "${dep}" ./*/build_require*
	fi
    fi
done

#
# and check for blank lines
#
for dep in $(grep '^[ ]*$' ./*/depend* ./*/build_require*)
do
    echo "Blank line in $dep"
done

#
# and malformed depend files
#
grep -v '^[PI] ' ./*/depend*
