#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# verifies a repo; specifically that all the packages listed in the
# catalog are present
#
# fields in catalog:
#  1 name
#  2 version
#  3 dependencies
#  4 size
#  5 checksum
#

STYLE=quick

case $1 in
    -v)
	STYLE=long
	;;
esac

if [ ! -f catalog ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

case $STYLE in
    quick)
awk -F'|' '{print $1,$2}' catalog | while read -r pkg ver
do
  if [ ! -f "${pkg}.${ver}.zap" ]; then
      echo "ERROR: ${pkg}.${ver}.zap missing"
  else
    if [ ! -f "${pkg}.${ver}.zap.sig" ]; then
	echo "ERROR: ${pkg}.${ver}.zap.sig missing"
    fi
  fi
done
;;

    long)
awk -F'|' '{print $1,$2,$4,$5}' catalog | while read -r pkg ver psize psum
do
  if [ ! -f "${pkg}.${ver}.zap" ]; then
    echo "ERROR: ${pkg}.${ver}.zap missing"
  else
    if [ ! -f "${pkg}.${ver}.zap.sig" ]; then
	echo "ERROR: ${pkg}.${ver}.zap.sig missing"
    fi
    fsize=$(/bin/ls -l "${pkg}.${ver}.zap" | /usr/bin/awk '{print $5}')
    if [ "X$psize" != "X$fsize" ]; then
      echo "ERROR: ${pkg}.${ver}.zap has the wrong size"
    else
      PKGMD5=$(/usr/bin/openssl md5 "${pkg}.${ver}.zap" | /usr/bin/awk '{print $NF}')
      if [ "X$PKGMD5" != "X$psum" ]; then
        echo "ERROR: ${pkg}.${ver}.zap has the wrong checksum"
      fi
    fi
  fi
done
;;

esac
