#!/bin/sh
#
# verifies a repo; specifically that all the packages listed in the
# catalog are present
#
# fields in catalog:
#  1 name
#  2 version
#  3 dependencies
#  4 size
#  5 checksum
#

STYLE=quick

case $1 in
    -v)
	STYLE=long
	;;
esac

if [ ! -f catalog ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

case $STYLE in
    quick)
cat catalog | awk -F'|' '{print $1,$2}' | while read pkg ver
do
  if [ ! -f ${pkg}.${ver}.zap ]; then
    echo "ERROR: ${pkg}.${ver}.zap missing"
  fi
done
;;

    long)
cat catalog | awk -F'|' '{print $1,$2,$4,$5}' | while read pkg ver psize psum
do
  if [ ! -f ${pkg}.${ver}.zap ]; then
    echo "ERROR: ${pkg}.${ver}.zap missing"
  else
    fsize=`/bin/ls -l ${pkg}.${ver}.zap | /usr/bin/awk '{print $5}'`
    if [ "X$psize" != "X$fsize" ]; then
      echo "ERROR: ${pkg}.${ver}.zap has the wrong size"
    else
      PKGMD5=`/usr/bin/openssl md5 ${pkg}.${ver}.zap| /usr/bin/awk '{print $NF}'`
      if [ "X$PKGMD5" != "X$psum" ]; then
        echo "ERROR: ${pkg}.${ver}.zap has the wrong checksum"
      fi  
    fi
  fi
done
;;

esac

if [ -f catalog.sig ]; then
    cat catalog | awk -F'|' '{print $1,$2}' | while read pkg ver
    do
	if [ ! -f ${pkg}.${ver}.zap.sig ]; then
	    echo "ERROR: ${pkg}.${ver}.zap.sig missing"
	fi
    done
fi
