#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# verifies an overlay repo
#

if [ ! -f catalog ]; then
   echo "No catalog. Is this a repo?"
   exit 1
fi

#
# check that all overlays listed in the catalog exist and are at the
# correct version
#
awk -F'|' '{print $1, $2}' catalog | while read -r pkg iver
do
  if [ ! -f "${pkg}.pkgs" ]; then
    echo "ERROR: ${pkg}.pkgs missing"
  fi
  if [ -f "${pkg}.ovl" ]; then
      nver=$(grep '^VERSION=' "${pkg}.ovl")
      nver=${nver##*=}
      if [ "X${nver}" != "X${iver}" ]; then
	  echo "ERROR: $pkg is at the wrong version"
      fi
  else
      echo "ERROR: ${pkg}.ovl missing"
  fi
done

#
# check that every .ovl file has a .pkgs file, and vice versa
#
for file in *.ovl
do
    pkg=${file%.ovl}.pkgs
    if [ ! -f "${pkg}" ]; then
	echo "ERROR: no $pkg for $file"
    fi
done
for file in *.pkgs
do
    ovl=${file%.pkgs}.ovl
    if [ ! -f "${ovl}" ]; then
	echo "ERROR: no $ovl for $file"
    fi
done

#
# check that every required overlay exists
#
for req in $(grep REQUIRES= *.ovl | awk -F= '{print $NF}')
do
    if [ ! -f "${req}.ovl" ]; then
	echo "ERROR: Missing dependency ${req}"
    fi
done

#
# and for circular dependencies
#
# note that we only detect direct circular dependencies, where two
# overlays depend on each other
#
# print the dependencies both forwards and backwards, and a circular
# dependency will then be repeated
#
CIRCDEP=$(grep REQUIRES= *.ovl | awk -F'[\.=]' '{print $1,$NF"\n"$NF,$1}' | sort | uniq -d)
if [ -n "${CIRCDEP}" ]; then
    echo "ERROR: circular dependency"
    echo "${CIRCDEP}"
fi
