#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# verify a catalog
# really for a manually maintained catalog, like sparc,
# to catch packages that have been removed
#
case $# in
    1)
	CFILE=$1
	;;
    *)
	echo "Usage: $0 catalog"
	exit 1
	;;
esac

if [ ! -f "$CFILE" ]; then
    echo "ERROR: $CFILE not found"
    exit 1
fi

#
# assume we're in the build directory
#
awk -F'|' '{print $1}' "$CFILE" | while read -r pkg
do
    if [ ! -d "$pkg" ]; then
	echo "WARN: missing package $pkg"
    fi
done
