#!/bin/ksh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# convert a zap format package to an svr4 package (in datastream format)
#
case $# in
2)
	FPKG="$1"
	BROOT="$2"
	;;
*)
	echo "Usage: $0 input_pkg output_dir"
	exit 2
	;;
esac

if [ ! -f "$FPKG" ]; then
   echo "ERROR: input file not found"
   exit 1
fi

if [ "${FPKG:0:1}" != / ]; then
    echo "Input file must have absolute path"
    exit 1
fi

if [ ! -d "$BROOT" ]; then
   echo "ERROR: output directory not found"
   exit 1
fi

#
BPKG=${FPKG##*/}
PNAME=${BPKG%.zap}
TDIR=/tmp/zap2pkg.$(date '+%F-%T').$$
rm -fr "$TDIR"
mkdir -p "$TDIR"

cd "$TDIR" || exit 1
unzip "$FPKG"
pkgtrans . "${BROOT}"/"${PNAME}".pkg all
chmod a+r "${BROOT}"/"${PNAME}".pkg

#
# clean up
#
cd /
rm -fr "$TDIR"
ls -lh "${BROOT}"/"${PNAME}".pkg
