#!/bin/sh
#
VERSION="3.7"

#
# first strip out the tests
#
TESTDIR=/tmp/ptest.$$
rm -fr $TESTDIR
mkdir -p $TESTDIR
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/sqlite3/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/sqlite3/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/tkinter/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/tkinter/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-tk/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/lib-tk/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib2to3/tests | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/lib2to3/tests
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/json/tests | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/json/tests
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/idlelib/idle_test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/idlelib/idle_test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/email/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/email/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/ctypes/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/ctypes/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/distutils/tests | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/distutils/tests
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_ctypes_test.so | ( cd $TESTDIR ; tar xf -)
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_testcapi.so | ( cd $TESTDIR ; tar xf -)
rm -f usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_ctypes_test.so
rm -f usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_testcapi.so
#
# having copied them off, package them
#
$THOME/build/create_pkg TRIBv-python-37-tests $TESTDIR
rm -fr $TESTDIR

mkdir -p usr/bin
mkdir -p usr/lib/pkgconfig
cd usr/versions/python-${VERSION}/bin
ln -s python${VERSION} python
cd ../../../..
mkdir -p usr/share/man/man1
cd usr/share/man/man1
ln -s ../../../../usr/versions/python-${VERSION}/share/man/man1/python${VERSION}.1 .
ln -s ../../../../usr/versions/python-${VERSION}/share/man/man1/python3.1 .
cd ../../../..
cd usr/bin
#
# symlinks for this specific version
#
ln -s ../../usr/versions/python-${VERSION}/bin/python${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/python${VERSION}-config .
ln -s ../../usr/versions/python-${VERSION}/bin/pydoc${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/pyvenv-${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/idle${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/pip${VERSION} .
#
# symlinks for general version
#
ln -s ../../usr/versions/python-${VERSION}/bin/python3 .
ln -s ../../usr/versions/python-${VERSION}/bin/python3-config .
ln -s ../../usr/versions/python-${VERSION}/bin/pydoc3 .
ln -s ../../usr/versions/python-${VERSION}/bin/pyvenv .
ln -s ../../usr/versions/python-${VERSION}/bin/idle3 .
ln -s ../../usr/versions/python-${VERSION}/bin/pip3 .
cd ../lib
ln -s ../versions/python-${VERSION}/lib/libpython3* .
cd pkgconfig
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python-${VERSION}.pc .
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python3.pc .
cd ../../versions/python-${VERSION}/lib/python${VERSION}/site-packages
tar cf setuptools.tar setuptools
rm -fr setuptools
