#!/bin/sh
#
VERSION="3.7"
mkdir -p usr/bin
mkdir -p usr/lib/pkgconfig
cd usr/versions/python-${VERSION}/bin
ln -s python${VERSION} python
cd ../../../..
cd usr/bin
#
# symlinks for specific version
#
ln -s ../../usr/versions/python-${VERSION}/bin/python${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/python${VERSION}-config .
ln -s ../../usr/versions/python-${VERSION}/bin/pydoc${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/pyvenv-${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/idle${VERSION} .
ln -s ../../usr/versions/python-${VERSION}/bin/pip${VERSION} .
#
# symlinks for general version
#
ln -s ../../usr/versions/python-${VERSION}/bin/python3 .
ln -s ../../usr/versions/python-${VERSION}/bin/python3-config .
ln -s ../../usr/versions/python-${VERSION}/bin/pydoc3 .
ln -s ../../usr/versions/python-${VERSION}/bin/pyvenv .
ln -s ../../usr/versions/python-${VERSION}/bin/idle3 .
cd ../lib
ln -s ../versions/python-${VERSION}/lib/libpython3* .
cd pkgconfig
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python-${VERSION}.pc .
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python3.pc .
cd ../../versions/python-${VERSION}/lib/python${VERSION}/site-packages
tar cf setuptools.tar setuptools
rm -fr setuptools
