#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#

VERSION=2.5.10

mkdir -p usr/bin usr/share/man/man1
cd usr/bin
ln -s ../../usr/versions/sbcl-${VERSION}/bin/sbcl .
cd ../..
cd usr/share/man/man1
ln -s ../../../../usr/versions/sbcl-${VERSION}/share/man/man1/sbcl.1 .
