#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add a convenience link
#
PYVERS=3.12
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/linkchecker .
cd ../..
rm -fr usr/versions/python-${PYVERS}/share/man/de
mkdir -p usr/share/man/man1
cd usr/share/man/man1
ln -s ../../../../usr/versions/python-3.12/share/man/man1/linkchecker.1 .
cd ../../../..
mkdir -p usr/share/man/man5
cd usr/share/man/man5
ln -s ../../../../usr/versions/python-3.12/share/man/man5/linkcheckerrc.5 .
