#!/bin/sh
#
# we build the system off in /usr/version, but some of it must live
# in normal paths
#
mkdir -p usr/share
mv usr/versions/lumina/share/applications usr/share
mv usr/versions/lumina/share/icons usr/share
mv usr/versions/lumina/share/xsessions usr/share

#
# use a common place for desktop backgrounds
#
mv usr/share/wallpapers usr/share/backgrounds
sed -i s:usr/share/wallpapers:usr/share/backgrounds: usr/versions/lumina/share/lumina-desktop/luminaDesktop.conf

#
# use applications that we actually ship, if we can
#
sed -i s:chromium-browser:palemoon: usr/versions/lumina/share/lumina-desktop/luminaDesktop.conf
sed -i s:org.kde.falkon:netsurf-gtk: usr/versions/lumina/share/lumina-desktop/luminaDesktop.conf
sed -i s:qterminal:sakura: usr/versions/lumina/share/lumina-desktop/luminaDesktop.conf
sed -i s:okular:org.gnome.Evince: usr/versions/lumina/share/lumina-desktop/luminaDesktop.conf
sed -i s:trojita:claws-mail: usr/versions/lumina/share/lumina-desktop/luminaDesktop.conf

#
# the backgrounds are massive, tidy them a bit
#
cd usr/share/backgrounds
for dir in *
do
    if [ -d $dir ]; then
	cd $dir
	for file in *jpg
	do
	    convert $file -strip -quality 75 zaptmp.jpg
	    mv zaptmp.jpg $file
	done
	cd ..
    fi
done
