#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up a bit
#
rm -f usr/lib/imlib2/loaders/*.la
rm -f usr/lib/imlib2/filters/*.la
rm -f usr/lib/*/imlib2/loaders/*.la
rm -f usr/lib/*/imlib2/filters/*.la
