#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
PYVERS=3.12
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/* .
cd ../..
#
mv usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/etc etc
rm -fr etc/fail2ban/action.d/__pycache__
#
cp ${BUILDROOT}/patches/fail2ban/paths-tribblix.conf etc/fail2ban
