#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# the project is called djview, the desktop file calls it djview4
# so install the binary under that name
#
ln usr/bin/djview usr/bin/djview4
#
# there is no prospect of the firefox plugin working
#
rm -fr usr/lib/mozilla
rmdir usr/lib
