#!/bin/sh
#
# setuptools has files whose names contain spaces, so we unpack them
# rather than package them
#
cd ${BASEDIR}/usr/versions/python-3.5/lib/python3.5/site-packages
if [ -d setuptools ]; then
  /usr/bin/rm -fr setuptools
fi
