#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# remove this, as it's most likely from the old v2 version that we still
# ship for binary compatibility, whereas everything else is from v3
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
rm -f usr/bin/${ARCH64}/libassuan-config
