#!/bin/sh
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# remove errant requirement on iconv
#
if [ -f usr/lib/pkgconfig/libarchive.pc ]; then
    sed -i 's:iconv ::' usr/lib/pkgconfig/libarchive.pc
fi
sed -i 's:iconv ::' usr/lib/${ARCH64}/pkgconfig/libarchive.pc
