#!/bin/sh
#
# Only LTS releases have standard symlinks
#
VERSION=18
mkdir -p usr/bin
ln -s ../versions/node-v${VERSION}/bin/node usr/bin/node
ln -s ../versions/node-v${VERSION}/bin/npm usr/bin/npm
ln -s ../versions/node-v${VERSION}/bin/npx usr/bin/npx
ln -s ../versions/node-v${VERSION}/bin/corepack usr/bin/corepack

#
# we don't have systemtap
#
rm -fr usr/versions/node-v${VERSION}/share/systemtap
