#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up
#
rm -fr usr/share/afterstep_old
#
# customize settings
#
gsed -i '/urxvt/d' usr/share/afterstep/wharf
gsed -i '/aterm/d' usr/share/afterstep/wharf
gsed -i '/ETerm/d' usr/share/afterstep/wharf
gsed -i '/rxvt/d' usr/share/afterstep/wharf
gsed -i -e 's:nautilus:thunar:' -e 's:Nautilus:Thunar:' -e 's:--no-desktop::' usr/share/afterstep/wharf
gsed -i '/TermTabs/d' usr/share/afterstep/autoexec

gsed -i s:/usr/local/share:/usr/share: usr/bin/makeastheme.pl
gsed -i s:/usr/local/share:/usr/share: usr/bin/installastheme.pl

#
# fix up manpage issues
#
cd usr/share/man

#
# the development functions are unlikely to be terribly useful
#
rm -fr man3

#
# the others have the wrong filenames
#
cd man1
for file in *.1x
do
    mv $file `echo $file | sed 's:.1x:.1:'`
done
