#!/bin/sh
#
# clean up
#
rm -fr usr/share/afterstep_old
#
# customize settings
#
gsed -i '/urxvt/d' usr/share/afterstep/wharf
gsed -i '/aterm/d' usr/share/afterstep/wharf
gsed -i '/ETerm/d' usr/share/afterstep/wharf
gsed -i '/rxvt/d' usr/share/afterstep/wharf
gsed -i -e 's:nautilus:thunar:' -e 's:Nautilus:Thunar:' -e 's:--no-desktop::' usr/share/afterstep/wharf
gsed -i '/TermTabs/d' usr/share/afterstep/autoexec

case `uname -p` in
sparc)
    ARCH64="sparcv9"
    ;;
i386)
    ARCH64="amd64"
    ;;
esac

#
# no need to ship duplicate perl scripts
#
/bin/rm -f usr/bin/${ARCH64}/*.pl

gsed -i s:/usr/local/share:/usr/share: usr/bin/makeastheme.pl
gsed -i s:/usr/local/share:/usr/share: usr/bin/installastheme.pl
