#!/bin/sh
#
VERSION=2.13.13
mkdir -p usr/bin
ln -s ../../usr/versions/scala-${VERSION}/bin/scala usr/bin/
ln -s ../../usr/versions/scala-${VERSION}/bin/scalap usr/bin/
ln -s ../../usr/versions/scala-${VERSION}/bin/scalac usr/bin/
ln -s ../../usr/versions/scala-${VERSION}/bin/scaladoc usr/bin/
mkdir -p usr/share/man/man1
ln -s ../../../../usr/versions/scala-${VERSION}/man/man1/scala.1 usr/share/man/man1
ln -s ../../../../usr/versions/scala-${VERSION}/man/man1/scalac.1 usr/share/man/man1
ln -s ../../../../usr/versions/scala-${VERSION}/man/man1/scalap.1 usr/share/man/man1
ln -s ../../../../usr/versions/scala-${VERSION}/man/man1/scaladoc.1 usr/share/man/man1
cd usr/versions/scala-${VERSION}
rm bin/*.bat
