#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
mkdir -p ${DESTDIR}/usr/share/man/man1
cp xphoon.man ${DESTDIR}/usr/share/man/man1/xphoon.1
