#!/bin/sh
#
# put the unpackageable files in the place that packaging expects
#
cd ${BASEDIR:-/}
mv 'usr/versions/node-v10/lib/node_modules/npm/node_modules/ajv/lib/$data.js' usr/versions/node-v10/lib/node_modules/npm/node_modules/ajv/lib/XXXdata.js
mv 'usr/versions/node-v10/lib/node_modules/npm/node_modules/ajv/lib/refs/$data.json' usr/versions/node-v10/lib/node_modules/npm/node_modules/ajv/lib/refs/XXXdata.json
