#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
rm -f usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/*.la
rm -f usr/lib/*/gdk-pixbuf-2.0/2.10.0/loaders/*.la
rm -f usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/*.a
rm -f usr/lib/*/gdk-pixbuf-2.0/2.10.0/loaders/*.a
