#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# replace the 32-bit binary with the 64-bit one
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

if [ -x usr/bin/${ARCH64}/curl ]; then
  mv usr/bin/${ARCH64}/curl usr/bin/curl
fi

#
# add wcurl
#
mkdir -p usr/bin
curl -fLO https://github.com/curl/wcurl/releases/latest/download/wcurl
mv wcurl usr/bin/wcurl
chmod 755 usr/bin/wcurl
mkdir -p usr/share/man/man1
curl -fLO https://github.com/curl/wcurl/releases/latest/download/wcurl.1
mv wcurl.1 usr/share/man/man1/wcurl.1
chmod 0644 usr/share/man/man1/wcurl.1

#
# In 8.11.0 the shipped pc files blindly referred to requirements that do not
# and will not ever exist
#
#sed -i s:ldap,:: usr/lib/pkgconfig/libcurl.pc
#sed -i s:ldap,:: usr/lib/*/pkgconfig/libcurl.pc
