#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
PYVERS=3.12
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/* .
cd ../..
mkdir -p usr/share/man/man1
mv usr/versions/python-${PYVERS}/share/man/man1/* usr/share/man/man1
rmdir usr/versions/python-${PYVERS}/share/man/man1
rmdir usr/versions/python-${PYVERS}/share/man
#
# shell completions
#
mkdir -p usr/share
mv usr/versions/python-${PYVERS}/share/bash-completion usr/share
mv usr/versions/python-${PYVERS}/share/fish usr/share
mv usr/versions/python-${PYVERS}/share/zsh usr/share
