#!/bin/sh
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# we never shipped .la files before, don't do so now
#
rm -f usr/lib/lib*.la
rm -f usr/lib/${ARCH64}/lib*.la

rm -f usr/bin/pngfix usr/bin/png-fix-itxt
rm -f usr/bin/${ARCH64}/pngfix usr/bin/${ARCH64}/png-fix-itxt
