#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
awk '
{if ($3 ~ /^var\/dnsmasq/) { $6 = "dnsmasq" ; $5 = "dnsmasq" }}
{print}
'
