#!/bin/sh
#
# pkgproto generates garbage when fed hard links, so a symlink is just as good
#
VERSION=1.9.11
mkdir -p usr/bin
ln -s ../versions/apache-ant-${VERSION}/bin/ant usr/bin/ant
#
rm usr/versions/apache-ant-${VERSION}/bin/*.bat
rm usr/versions/apache-ant-${VERSION}/bin/*.cmd
