#!/bin/sh
mkdir -p usr/share/man/man3
mv usr/man/man3/*.3 usr/share/man/man3
rmdir usr/man/man3 usr/man
#
rm -fr usr/share/doc
rm -fr usr/share/rrdtool
rm -f usr/lib/librrd.la
rm -f usr/lib/*/librrd.la
#
# fix perl location
#
mkdir -p usr/perl5/site_perl
rm usr/lib/perl/5.34.0/*-solaris-thread-multi-64/perllocal.pod
mv usr/lib/perl/5.34.0 usr/perl5/site_perl
rmdir usr/lib/perl
