#!/bin/sh
mkdir -p usr/share/man/man3
mv usr/man/man3/*.3 usr/share/man/man3
rmdir usr/man/man3 usr/man
#
rm -fr usr/share/doc
rm -fr usr/share/rrdtool
rm -f usr/lib/*.la
#
# this is where our python really lives
#
mkdir -p usr/versions/python-2.7/lib/python2.7/site-packages
mv usr/lib/python2.7/site-packages/* usr/versions/python-2.7/lib/python2.7/site-packages
rmdir usr/lib/python2.7/site-packages
rmdir usr/lib/python2.7
#
# ditto perl
#
mkdir -p usr/perl5/site_perl
rm usr/lib/perl/5.22.0/i86pc-solaris-thread-multi-64int/perllocal.pod
mv usr/lib/perl/5.22.0 usr/perl5/site_perl
