#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we use the "normal" (not "large") SCOWL lists
#
mkdir -p usr/share/hunspell
cd usr/share/hunspell
#
# download
#
wget https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/hunspell-en_CA-2020.12.07.zip
wget https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/hunspell-en_AU-2020.12.07.zip
wget https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/hunspell-en_US-2020.12.07.zip
wget https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/hunspell-en_GB-ise-2020.12.07.zip
wget https://sourceforge.net/projects/wordlist/files/speller/2020.12.07/hunspell-en_GB-ize-2020.12.07.zip
#
# unpack
#
unzip -q hunspell-en_AU-2020.12.07.zip
unzip -q hunspell-en_CA-2020.12.07.zip
unzip -q hunspell-en_GB-ise-2020.12.07.zip
unzip -q hunspell-en_GB-ize-2020.12.07.zip
unzip -q hunspell-en_US-2020.12.07.zip
rm -f *.zip
#
# symlinks
#
# for british english, prefer "ise"
#
ln -s en_GB-ise.aff en_GB.aff
ln -s en_GB-ise.dic en_GB.dic
#
# these aliases derived from the OI list
#
ln -s en_US.aff en_PH.aff
ln -s en_US.dic en_PH.dic
for alt in en_AG en_BS en_BW en_BZ en_DK en_GH en_HK en_IE en_IN en_JM en_NA en_NG en_NZ en_SG en_TT en_ZA en_ZW
do
    ln -s en_GB.aff ${alt}.aff
    ln -s en_GB.dic ${alt}.dic
done
