#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION=3.2.1
mv "usr/versions/testssl.sh-${VERSION}" usr/versions/testssl.sh
#
# cleanup
#
rm -f usr/versions/testssl.sh/etc/DST*
rm -f usr/versions/testssl.sh/bin/openssl.*
rm -f usr/versions/testssl.sh/Docker*
rm -fr usr/versions/testssl.sh/.git*
rm -fr usr/versions/testssl.sh/t
chmod -R a+rX usr/versions/testssl.sh
#
# manual
#
mkdir -p usr/share/man/man1
mv usr/versions/testssl.sh/doc/testssl.1 usr/share/man/man1
rm -f usr/versions/testssl.sh/doc/testssl.1.*
rmdir usr/versions/testssl.sh/doc
#
# wrapper
#
mkdir -p usr/bin
cp "${BUILDROOT}/patches/testssl.sh" usr/bin/testssl.sh
chmod a+x usr/bin/testssl.sh
