#!/bin/sh
mkdir -p etc/zap
#
# this should be the current version
#
cat > etc/zap/version.current <<EOF
m15
EOF
#
# this should initially include only the current version
# and then be updated for all later versions
#
# ideally, add the new release to the old version just before making
# a release
#
case `uname -p` in
sparc)
cat > etc/zap/version.list <<EOF
m15|http://pkgs.tribblix.org/tribblix-m15.sparc/TRIBzap.0.0.15.0.zap|Milestone 15
EOF
;;
i386)
cat > etc/zap/version.list <<EOF
m15|http://pkgs.tribblix.org/tribblix-m15/TRIBzap.0.0.15.0.zap|Milestone 15
EOF
;;
esac
