#!/bin/sh
mkdir -p etc/zap
#
# this should be the current version
#
cat > etc/zap/version.current <<EOF
m16
EOF
#
# this should initially include only the current version
# and then be updated for all later versions
#
# add the new release to the old version just before making
# a release, then respin this one for the release itself
#
case `uname -p` in
sparc)
cat > etc/zap/version.list <<EOF
m16|http://pkgs.tribblix.org/tribblix-m16.sparc/TRIBzap.0.0.16.0.zap|Milestone 16
m17|http://pkgs.tribblix.org/tribblix-m17.sparc/TRIBzap.0.0.17.0.zap|Milestone 17
EOF
;;
i386)
cat > etc/zap/version.list <<EOF
m16|http://pkgs.tribblix.org/tribblix-m16/TRIBzap.0.0.16.0.zap|Milestone 16
m17|http://pkgs.tribblix.org/tribblix-m17/TRIBzap.0.0.17.0.zap|Milestone 17
EOF
;;
esac
