#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION=6

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

rm -fr usr/versions/Qt-${VERSION}/doc
rm -fr usr/versions/Qt-${VERSION}/examples

#
# fix up any pkgconfig files
#

mkdir -p usr/lib/${ARCH64}/pkgconfig

cd usr/lib/${ARCH64}/pkgconfig
ln -s ../../../versions/Qt-${VERSION}/lib/${ARCH64}/pkgconfig/* .
cd ../../../versions/Qt-${VERSION}/lib/${ARCH64}/pkgconfig
gsed -i -e 's: -L${libdir}: -L${libdir} -R${libdir}:' *
cd ../../../../../..
