#!/bin/sh
VERSION=6

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

rm -fr usr/versions/Qt-${VERSION}/doc
rm -fr usr/versions/Qt-${VERSION}/examples

exit 0

#
# there don't appear to be any pkgconfig files in Qt6
#

mkdir -p usr/lib/pkgconfig
#mkdir -p usr/lib/${ARCH64}/pkgconfig

cd usr/lib/pkgconfig
ln -s ../../versions/Qt-${VERSION}/lib/pkgconfig/* .
cd ../../versions/Qt-${VERSION}/lib/pkgconfig
gsed -i -e 's: -L/usr/versions/Qt-6/lib: -L/usr/versions/Qt-6/lib -R/usr/versions/Qt-6/lib:g' -e 's: -L/usr/sfw/lib::g' -e 's: -L/usr/openwin/lib::g' -e 's: -L${libdir}: -L${libdir} -R${libdir}:' *
cd ../../../../..

exit 0

cd usr/lib/${ARCH64}/pkgconfig
ln -s ../../../versions/Qt-${VERSION}/lib/${ARCH64}/pkgconfig/* .
cd ../../../versions/Qt-${VERSION}/lib/${ARCH64}/pkgconfig
gsed -i -e 's: -L/usr/versions/Qt-6/lib: -L/usr/versions/Qt-6/lib -R/usr/versions/Qt-6/lib:g' -e 's: -L/usr/sfw/lib::g' -e 's: -L/usr/openwin/lib::g' -e 's: -L${libdir}: -L${libdir} -R${libdir}:' *
cd ../../../../../..

