#!/bin/sh
rm -f `find . -name '*.la'`
#
# there are static modules, so the filenames don't start with lib
#
rm -f `find . -name '*.a'`
#
# we don't need the apr build pieces
#
rm -fr opt/tribblix/nxlog/lib/pkgconfig
rm -f opt/tribblix/nxlog/lib/apr.exp
rm -fr opt/tribblix/nxlog/include/apr-1
rmdir opt/tribblix/nxlog/include
rm -fr opt/tribblix/nxlog/build-1
rm -f opt/tribblix/nxlog/bin/apr-1-config
