#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# don't ship documentation
#
/usr/bin/rm -fr usr/share/doc
#
# this will remove the directory if it's empty
# if there are manpages, then it will have no effect
#
/usr/bin/rmdir usr/share
