#!/bin/sh
#
# check out the haplo plugin tool
#
mkdir -p usr/bin
mkdir -p usr/versions


cd usr/versions

#
# this is the tool itself
#
git clone https://github.com/haplo-org/haplo-plugin-tool

#
# we need a copy of hsvt for the build
#
git clone https://github.com/haplo-org/haplo-safe-view-templates
cd haplo-safe-view-templates
mvn package
cd ..

cd haplo-plugin-tool
./fetch_rhino.sh
#./build_haplo_templates.sh `pwd`/../haplo
#
# use the master copy from hsvt instead
#
cp ../haplo-safe-view-templates/target/hsvt-0.1-SNAPSHOT.jar lib/haplo-templates.jar

cd ..
chmod a+x haplo-plugin-tool/bin/haplo-plugin
rm -fr haplo-plugin-tool/.git
rm -f haplo-plugin-tool/.gitignore
#
# it really is jruby we want
#
sed -i 's:#!/usr/bin/env ruby:#!/usr/bin/env jruby:' haplo-plugin-tool/bin/haplo-plugin

#
# delete the temporary hsvt checkout
#
rm -fr haplo-safe-view-templates

cd ../bin

#
# a symlink doesn't work because the script resolves it
#

cat > haplo-plugin <<_EOF
#!/bin/sh
exec /usr/versions/haplo-plugin-tool/bin/haplo-plugin "\$@"
_EOF
chmod a+x haplo-plugin
