#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# these libraries are private and have been deprecated
#
rm -f usr/lib/libbind9.a
rm -f usr/lib/libdns.a
rm -f usr/lib/libirs.a
rm -f usr/lib/libisc.a
rm -f usr/lib/libisccc.a
rm -f usr/lib/libisccfg.a
rm -f usr/lib/*/libbind9.a
rm -f usr/lib/*/libdns.a
rm -f usr/lib/*/libirs.a
rm -f usr/lib/*/libisc.a
rm -f usr/lib/*/libisccc.a
rm -f usr/lib/*/libisccfg.a
#
rm -f usr/lib/*/bind/filter-a.la usr/lib/*/bind/filter-aaaa.la
