#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we don't want to package sudoers, because then that would
# (a) lead to package validation errors, and
# (b) overwrite changes on update
#
# so we delete it from the package and copy it in postinstall
#
rm -f etc/sudoers
rm -f usr/libexec/sudo/*.la
#
# but we do drop in a custom config to work around the pty issue
#
mkdir -p etc/sudoers.d
cp ${BUILDROOT}/patches/sudo.config etc/sudoers.d/_illumos_nopty
chmod 0444 etc/sudoers.d/_illumos_nopty
