#!/sbin/sh
#
# put an unpackaged sudoers file in place
#
if [ -f ${BASEDIR}/etc/sudoers ]; then
    /usr/bin/chown root:root ${BASEDIR}/etc/sudoers
    exit 0
fi
if [ -f ${BASEDIR}/etc/sudoers.dist ]; then
    cp -p ${BASEDIR}/etc/sudoers.dist ${BASEDIR}/etc/sudoers
fi
