#!/bin/sh
#
# most of the documentation is install guides for other platforms, which
# is of no use to us
#
rm -fr usr/share/doc

rm -f usr/lib/*.la
#
# this is where our python really lives
#
mkdir -p usr/versions/python-2.7/lib/python2.7
mv usr/lib/python2.7/site-packages usr/versions/python-2.7/lib/python2.7
rmdir usr/lib/python2.7
#
# places where suricata stores data
#
mkdir -p var/lib/suricata/rules
mkdir -p var/log/suricata/certs
mkdir -p var/log/suricata/files
mkdir -p etc/suricata
