#!/bin/sh
#
# most of the documentation is install guides for other platforms, which
# is of no use to us
#
rm -fr usr/share/doc

rm -f usr/lib/*.la
#
# this is where our python really lives
#
mkdir -p usr/versions/python-3.9/lib/python3.9
mv usr/lib/python3.9/site-packages usr/versions/python-3.9/lib/python3.9
rmdir usr/lib/python3.9
#
# places where suricata stores data
#
mkdir -p var/lib/suricata/rules
mkdir -p var/log/suricata/certs
mkdir -p var/log/suricata/files
mkdir -p etc/suricata
