#!/bin/sh
#
# add a g-prefixed link
#
rm -f usr/gnu/lib/charset.alias
rmdir usr/gnu/lib
mkdir -p usr/bin/amd64
cd usr/bin
ln -s ../gnu/bin/grep ggrep
ln -s ../gnu/bin/egrep gegrep
ln -s ../gnu/bin/fgrep gfgrep
cd amd64
ln -s ../../gnu/bin/amd64/grep ggrep
ln -s ../../gnu/bin/amd64/egrep gegrep
ln -s ../../gnu/bin/amd64/fgrep gfgrep
