#!/bin/sh
#
# updates bump the SONAME, ship a copy of the old version for compat
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

cp -p /usr/lib/${ARCH64}/libjson-c.so.2.* usr/lib/${ARCH64}
cd usr/lib/${ARCH64}
ln -s libjson-c.so.2.* libjson-c.so.2
