#!/bin/sh
PYVERS=2.7

mkdir -p usr/bin
mkdir -p usr/share/man/man1
mkdir -p usr/share/man/man5

cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/pgpool .
cd ../..

cd usr/share/man/man1
ln -s ../../../../usr/versions/python-${PYVERS}/share/man/man1/pgpool.1 .
cd ../../../..

cd usr/share/man/man5
ln -s ../../../../usr/versions/python-${PYVERS}/share/man/man5/pgpool.5 .
cd ../../../..

mkdir -p var/pgpool
