#!/bin/sh
#
# clean up the junk
#
VERSION=1.12
rm -fr usr/versions/go-${VERSION}/pkg/bootstrap
rm -fr usr/versions/go-${VERSION}/pkg/obj/go-build
rmdir usr/versions/go-${VERSION}/pkg/obj
rm -fr usr/versions/go-${VERSION}/test
rm -f usr/versions/go-${VERSION}/favicon.ico
rm -f usr/versions/go-${VERSION}/robots.txt
