#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#

#
# chcon is selinux, which isn't relevant for us
#
rm -f usr/gnu/bin/chcon
rm -f usr/gnu/bin/*/chcon
rm -f usr/gnu/share/man/man1/chcon.1
rm -f usr/gnu/bin/runcon
rm -f usr/gnu/bin/*/runcon
rm -f usr/gnu/share/man/man1/runcon.1

#
# add g prefixes in /usr/bin, and other convenience links
#
rm -f usr/gnu/lib/charset.alias
rm -f usr/gnu/lib/*/charset.alias
rmdir usr/gnu/lib
rmdir usr/gnu/*/lib
mkdir -p usr/bin
cd usr/bin
ln -s ../gnu/bin/[ .
ln -s ../gnu/bin/printenv .
ln -s ../gnu/bin/md5sum .
ln -s ../gnu/bin/md5sum gmd5sum
ln -s ../gnu/bin/readlink .
ln -s ../gnu/bin/stat .
ln -s ../gnu/bin/install ginstall
ln -s ../gnu/bin/tac .
ln -s ../gnu/bin/sha*sum .
ln -s ../gnu/bin/date gdate
