#!/bin/sh
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ARCH32="sparcv7"
  ;;
i386)
  ARCH64="amd64"
  ARCH32="i86"
  ;;
esac
#
# chcon is selinux, which isn't relevant for us
#
rm -f usr/gnu/bin/chcon
rm -f usr/gnu/bin/*/chcon
rm -f usr/gnu/share/man/man1/chcon.1
rm -f usr/gnu/bin/runcon
rm -f usr/gnu/bin/*/runcon
rm -f usr/gnu/share/man/man1/runcon.1
#
# want a 64-bit date if we can, so isaexec it
#
mkdir -p usr/gnu/bin/${ARCH32}
mv usr/gnu/bin/date usr/gnu/bin/${ARCH32}

#
# add g prefixes in /usr/bin, and other convenience links
#
rm -f usr/gnu/lib/charset.alias
rm -f usr/gnu/lib/*/charset.alias
rmdir usr/gnu/lib
rmdir usr/gnu/*/lib
mkdir -p usr/bin
cd usr/bin
ln -s ../gnu/bin/[ .
ln -s ../gnu/bin/printenv .
ln -s ../gnu/bin/md5sum .
ln -s ../gnu/bin/md5sum gmd5sum
ln -s ../gnu/bin/readlink .
ln -s ../gnu/bin/stat .
ln -s ../gnu/bin/install ginstall
ln -s ../gnu/bin/tac .
ln -s ../gnu/bin/sha*sum .
ln -s ../gnu/bin/date gdate
