#!/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2023 Peter Tribble
#


export TERM=sun
export PATH=/usr/bin:/usr/openwin/bin:/usr/X11/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib:/usr/openwin/lib:/usr/openwin/server/lib:/usr/X11/lib:/usr/lib/xorg
export FONTLIST="/usr/X11/lib/X11/fonts/100dpi,/usr/X11/lib/X11/fonts/75dpi,/usr/X11/lib/X11/fonts/misc,/usr/X11/lib/X11/fonts/Type1"


exec /usr/openwin/bin/openXsun -defdepth 24 -fp $FONTLIST $@ &> /tmp/Xsun_errors.log
