#!/bin/sh
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# for binary compatibility, ship older libs
#
# the main TRIBimage-libtiff package ships libtiff 4
#
mkdir -p usr/lib/${ARCH64}
cp -a /usr/lib/libtiff.so.3* usr/lib
cp -a /usr/lib/${ARCH64}/libtiff.so.3* usr/lib/${ARCH64}
