#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
exit 0
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-3.12/bin/* .
cd ../..
mkdir -p usr/share/man/man1
mv usr/versions/python-3.12/man/man1/* usr/share/man/man1
rmdir usr/versions/python-3.12/man/man1
rmdir usr/versions/python-3.12/man

