#!/bin/sh
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
rmdir usr/ssl/certs
ln -s /etc/ssl/certs usr/ssl
#
# put manpages somewhere sane
#
mkdir usr/share
mv usr/ssl/man usr/share
#
# we no longer fiddle the manpage suffix, but some man pages conflict
#
mv usr/share/man/man1/errstr.1 usr/share/man/man1/openssl-errstr.1
mv usr/share/man/man1/passwd.1 usr/share/man/man1/openssl-passwd.1
#
# we should have a 64-bit opensslconf.h saved, now fix it to be dual-arch
#
mv usr/include/openssl/opensslconf.h usr/include/openssl/opensslconf-32.h
cp ${BUILDROOT}/patches/opensslconf.h usr/include/openssl/opensslconf.h
#
# libraries expect to live in /lib
#
mv usr/lib/64 usr/lib/${ARCH64}
mkdir -p lib/${ARCH64}
mv usr/lib/lib*so* lib
mv usr/lib/${ARCH64}/lib*so* lib/${ARCH64}
#
# the files live under /lib, symlinks under usr/lib
#
cd usr/lib
ln -s ../../lib/libssl.so* .
ln -s ../../lib/libcrypto.so* .
cd ${ARCH64}
ln -s ../../../lib/${ARCH64}/libssl.so* .
ln -s ../../../lib/${ARCH64}/libcrypto.so* .
