#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#

#
# if we're not openssl 3.0, then remove the openssl 1.1.1
# includes and man pages
#
if [ ! -f ${DESTDIR}/usr/include/openssl/sslerr_legacy.h ]; then
    rm -fr ${DESTDIR}/usr/include
    rm -fr ${DESTDIR}/usr/share/man
fi
