#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add a convenience link
#
PYVERS=3.12
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/test
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/sbom4python .
