#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# put in the regular path
#
PYVERS=3.12
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/* .
cd ../..
mkdir -p usr/share/man/man1
cd usr/share/man/man1
ln -s ../../../../usr/versions/python-3.12/share/man/man1/*.1 .
