#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# this is legacy compat and confuses current builds
#
rm -f usr/lib/${ARCH64}/cmake/Arrow/arrow-config.cmake
