#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# see /lib/svc/method/input-method-cache
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
mkdir -p usr/etc/${ARCH64}/gtk-2.0
#
# clean up
# (in 2 steps just in case something gets added later)
#
rm -fr usr/share/gtk-2.0/demo
rmdir usr/share/gtk-2.0
