#!/bin/sh
#
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-3.9/bin/* .
cd ../..
mkdir -p usr/share/man/man1
mv usr/versions/python-3.9/man/man1/* usr/share/man/man1
rmdir usr/versions/python-3.9/man/man1
rmdir usr/versions/python-3.9/man

