#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# need to put the manifest under var for sparse-root zone support
#
mkdir -p var/svc/manifest/network
cp ${BUILDROOT}/patches/zabbix-agent.xml var/svc/manifest/network
#
# the zabbixa home directory must exist
#
mkdir -p var/empty
#
# add some extra monitors
#
gsed -i 's:# Include=/usr/local/etc/zabbix_agentd.conf.d/\*.conf:Include=/etc/zabbix_agentd.conf.d/\*.conf:' etc/zabbix_agentd.conf
cp ${BUILDROOT}/patches/zabbix-zfs.conf etc/zabbix_agentd.conf.d/zfs.conf
cp ${BUILDROOT}/patches/zabbix-smf.conf etc/zabbix_agentd.conf.d/smf.conf
