#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
/bin/rm -fr usr/perl5/5.34/lib
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/perl5/5.34/bin/pg_format .
cd ../..
mkdir -p usr/share/man/man1
cd usr/share/man/man1
ln -s ../../../../usr/perl5/5.34/man/man1/pg_format.1 .
