#!/bin/sh
/bin/rm -fr usr/perl5/5.22.0/lib
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/perl5/5.22.0/bin/pg_format .
cd ../..
mkdir -p usr/share/man/man1
cd usr/share/man/man1
ln -s ../../../../usr/perl5/5.22.0/man/man1/pg_format.1 .
