#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# just name off the primary version
#
VERSION=9.0.113
cd usr/versions
ln -s apache-tomcat-${VERSION} tomcat9
chmod a+x apache-tomcat-${VERSION}/bin/*.sh
rm apache-tomcat-${VERSION}/bin/*.bat
