#!/bin/sh
#
# just name off the primary version
#
VERSION=9.0.88
cd usr/versions
ln -s apache-tomcat-${VERSION} tomcat9
chmod a+x apache-tomcat-${VERSION}/bin/*.sh
rm apache-tomcat-${VERSION}/bin/*.bat
