#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
cd usr/share/gc
rm -f README.DGUX386 README.Mac README.MacOSX README.OS2
rm -f README.amiga README.arm.cross README.cmake README.darwin
rm -f README.ews4800 README.hp README.linux README.rs6000
rm -f README.sgi README.uts README.win32 README.win64
