#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add a gm4 link
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
mkdir -p usr/bin/${ARCH64}
ln -s ../gnu/bin/m4 usr/bin/gm4
# some things (eg bison) might reference the 64-bit path explicitly
# so make sure it resolves
ln -s ../../gnu/bin/m4 usr/bin/${ARCH64}/gm4
