#!/bin/sh
#
# just name off the primary version
#
VERSION=7.0.90
cd usr/versions
ln -s apache-tomcat-${VERSION} tomcat7
chmod a+x apache-tomcat-${VERSION}/bin/*.sh
rm apache-tomcat-${VERSION}/bin/*.bat
