#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up the junk
#
VERSION=1.26
rm -fr usr/versions/go-${VERSION}/pkg/bootstrap
rm -fr usr/versions/go-${VERSION}/pkg/obj/go-build
rmdir usr/versions/go-${VERSION}/pkg/obj
rm -fr usr/versions/go-${VERSION}/test
rm -f usr/versions/go-${VERSION}/favicon.ico
rm -f usr/versions/go-${VERSION}/robots.txt

# not default yet
exit 0
mkdir -p usr/bin
cd usr/bin
ln -s ../versions/go-${VERSION}/bin/* .
