#!/bin/sh
#
# create a versioned directory
# put a symlink to firefox in /usr/bin
# disable autoupdate - see
# https://support.mozilla.org/en-US/questions/944982
#
VERSION=29.0
mkdir -p usr/bin
cd usr/versions
mkdir firefox-${VERSION}
mv firefox firefox-${VERSION}
mkdir -p usr/bin
cd ../../usr/bin
ln -s ../versions/firefox-${VERSION}/firefox/firefox .
cd ../versions/firefox-${VERSION}/firefox
rm -fr depend
mkdir depend
ln -s /usr/bin /usr/lib depend
cat > defaults/pref/local-settings.js <<EOF
pref("general.config.obscure_value", 0);
pref("general.config.filename", "mozilla.cfg");
EOF
cat > mozilla.cfg <<EOF
lockPref("app.update.auto", false);
lockPref("app.update.enabled", false); 
EOF
