#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fixinstall.64 saved the 64-bit gmp.h for us, now
# we wrap it
#
mv usr/include/gmp.h usr/include/gmp-32.h
cp ${BUILDROOT}/patches/gmp.h usr/include/gmp.h
