#!/bin/sh
#
# clean up and put a wrapper in the regular path
#
rm -fr usr/versions/prowler/.git*
rm -f usr/versions/prowler/.dockerignore
mkdir -p usr/bin
cat > usr/bin/prowler <<EOF
#!/bin/sh
env PATH=/usr/gnu/bin:$PATH /usr/versions/prowler/prowler "\$@"
EOF
chmod a+x usr/bin/prowler
