#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we don't ship .la files for base libraries
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.la'`
#
# don't ship documentation
#
/usr/bin/rm -fr usr/share/doc
#
# this will remove the directory if it's empty
# if there are manpages, then it will have no effect
#
/usr/bin/rmdir usr/share
