#!/bin/sh
#
# just name off the primary version
#
VERSION=1.6.2
mkdir -p usr/bin
rm -f usr/versions/projectlibre-${VERSION}/projectlibre.bat
cat > usr/bin/projectlibre <<EOF
#!/bin/sh
exec /usr/versions/projectlibre-${VERSION}/projectlibre.sh "\$@"
EOF
chmod a+x usr/bin/projectlibre
