#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# just name off the primary version
#
VERSION=1.9.3
mkdir -p usr/bin
rm -f usr/versions/projectlibre-${VERSION}/projectlibre.bat
cat > usr/bin/projectlibre <<EOF
#!/bin/sh
exec /usr/versions/projectlibre-${VERSION}/projectlibre.sh "\$@"
EOF
chmod a+x usr/bin/projectlibre
chmod a+x usr/versions/projectlibre-${VERSION}/projectlibre.sh
