#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# filenames with spaces
#
rm -fr usr/versions/ruby-3/lib/ruby/vendor_ruby/gems/3.2.0/gems/mini_portile2-2.8.7/test
# this is already supplied (but an older version) by ruby itself
rm -f usr/versions/ruby-3/bin/racc
