#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
PYVERS=3.12
#
# clean up tests, some files have interesting names
#
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/pelican/tests
#
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/pelican* .
