#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION=1.4.1
mkdir -p usr/bin
mkdir -p usr/share/pixmaps
mkdir -p usr/share/applications

cat > usr/bin/jdiskreport <<_EOF
#!/bin/sh
java -jar /usr/versions/jdiskreport-${VERSION}/jdiskreport-${VERSION}.jar
_EOF
chmod a+x usr/bin/jdiskreport

unzip -d . usr/versions/jdiskreport-${VERSION}/jdiskreport-${VERSION}.jar com/jgoodies/jdiskreport/resources/images/logo_64x64.png
mv com/jgoodies/jdiskreport/resources/images/logo_64x64.png usr/share/pixmaps/jdiskreport.png
rm -fr com

cat > usr/share/applications/jdiskreport.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=JDiskReport
Comment=Display disk usage
Exec=jdiskreport
Icon=jdiskreport
Terminal=false
Type=Application
Categories=System;Utility;
EOF
