#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION=2beta5
mkdir -p usr/bin
mkdir -p usr/share/pixmaps
mkdir -p usr/share/applications

mkdir -p usr/versions/jdiskreport
cd usr/versions/jdiskreport
curl -O https://www.jgoodies.com/download/jdiskreport2/jdiskreport-${VERSION}.jar
cd ../../..

case `uname -p` in
sparc)

cat > usr/bin/jdiskreport <<_EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
/usr/jdk/instances/jdk17/bin/java "\$@" -jar /usr/versions/jdiskreport/jdiskreport-${VERSION}.jar
_EOF
;;

*)

cat > usr/bin/jdiskreport <<_EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
/usr/jdk/instances/jdk21/bin/java "\$@" -jar /usr/versions/jdiskreport/jdiskreport-${VERSION}.jar
_EOF
;;

esac

chmod a+x usr/bin/jdiskreport

unzip -d . usr/versions/jdiskreport/jdiskreport-${VERSION}.jar com/jgoodies/jdiskreport/gui/application/resources/images/jdiskreport-64x64.png
mv com/jgoodies/jdiskreport/gui/application/resources/images/jdiskreport-64x64.png usr/share/pixmaps/jdiskreport.png
rm -fr com

cat > usr/share/applications/jdiskreport.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=JDiskReport
Comment=Display disk usage
Exec=jdiskreport
Icon=jdiskreport
Terminal=false
Type=Application
Categories=System;Utility;
EOF
