#!/bin/sh
#

#
# this is the directory tree for data and logs
#
mkdir -p var/elasticsearch/logs
mkdir -p var/elasticsearch/data
mkdir -p var/elasticsearch/scripts

#
# need to put the manifest under var for sparse-root zone support
#
mkdir -p var/svc/manifest/network
cp ${BUILDROOT}/patches/elasticsearch.xml var/svc/manifest/network

cd opt/tribblix
#
# Normalize the directory name
#
VERSION="5.6.13"
mv elasticsearch-${VERSION} elasticsearch

#
# clean up files that are meant for windows
#
rm -f elasticsearch/bin/*.bat
rm -f elasticsearch/bin/*.exe

#
# fix the configuration
#
cat >> elasticsearch/config/elasticsearch.yml <<EOF
#
# default data locations for ES on Tribblix
#
path.data: /var/elasticsearch/data
path.logs: /var/elasticsearch/logs
path.scripts: /var/elasticsearch/scripts
EOF
