#!/bin/sh
#
VERSION=3.2.1
mkdir -p usr/bin
ln -s ../../usr/versions/scala3-${VERSION}/bin/scala usr/bin/
ln -s ../../usr/versions/scala3-${VERSION}/bin/scalac usr/bin/
ln -s ../../usr/versions/scala3-${VERSION}/bin/scaladoc usr/bin/
#mkdir -p usr/share/man/man1
#ln -s ../../../../usr/versions/scala3-${VERSION}/man/man1/scala.1 usr/share/man/man1
#ln -s ../../../../usr/versions/scala3-${VERSION}/man/man1/scalac.1 usr/share/man/man1
cd usr/versions/scala3-${VERSION}
rm bin/*.bat
