#!/bin/sh
#
VERSION=3.3.1
mkdir -p usr/bin
ln -s ../../usr/versions/scala3-${VERSION}/bin/scala usr/bin/
ln -s ../../usr/versions/scala3-${VERSION}/bin/scalac usr/bin/
ln -s ../../usr/versions/scala3-${VERSION}/bin/scaladoc usr/bin/
cd usr/versions/scala3-${VERSION}
rm bin/*.bat
