#!/bin/sh
#
VERSION=24.0
mkdir -p usr/bin
cd usr/versions
mkdir firefox-${VERSION}
mv firefox firefox-${VERSION}
mkdir -p usr/bin
cd ../../usr/bin
ln -s ../versions/firefox-${VERSION}/firefox/firefox .
cd ../versions/firefox-${VERSION}/firefox
rm -fr depend
mkdir depend
ln -s /usr/bin /usr/lib depend
