#!/bin/sh
#
# we ship old and new versions of JasPer, but really we only want the shared
# libraries from the old version for binary compatibility
#
# we mangled the configure to install with a .19001 prefix, so we can easily
# identify what needs to be cleaned up
#
rm -fr usr/man.19001
rm -fr usr/include.19001
rm -f usr/bin/*.19001
rm -f usr/bin/*/*.19001
