#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we don't ship .la files for base libraries
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.la'`
#
# libdir puts the libraries where we want them
# now move the pkgconfig files back to a more predictable location
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

mkdir -p usr/lib/${ARCH64}
if [ -d usr/lib/xorg/pkgconfig ]; then
    mv usr/lib/xorg/pkgconfig usr/lib
fi
mv usr/lib/xorg/${ARCH64}/pkgconfig usr/lib/${ARCH64}

#
# don't ship documentation
#
/usr/bin/rm -fr usr/share/doc
#
# this will remove the directory if it's empty
# if there are manpages, then it will have no effect
#
if [ -d usr/share ]; then
    /usr/bin/rmdir usr/share
fi

#
# remove static archives
#
rm -f usr/lib/xorg/lib*.a
rm -f usr/lib/xorg/*/lib*.a

#
# tweak for sparc Xsun
#
case `uname -p` in
sparc)
    mkdir -p usr/openwin/server/lib
    ln -s ../../../../usr/lib/xorg/libXfont.so.1 usr/openwin/server/lib
    ;;
esac
