#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
awk '
{if ($3 ~ /^opt\/tribblix\/clamav\/var/) { $6 = "clamav" ; $5 = "clamav" }}
{print}
'
