#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up other platforms
# links into normal PATH
#
VERSION=4.0.29
rm usr/versions/groovy-${VERSION}/bin/*.bat
mkdir -p usr/bin
cd usr/bin
ln -s ../versions/groovy-${VERSION}/bin/* .
