#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION=1.10.15
mkdir -p usr/bin
ln -s ../versions/apache-ant-${VERSION}/bin/ant usr/bin/ant
#
# add extras, ivy now comes with jsch too
#
${THOME}/build/unpack apache-ivy-2.5.3-bin-with-deps
cp apache-ivy-2.5.3/ivy-2.5.3.jar usr/versions/apache-ant-${VERSION}/lib
cp apache-ivy-2.5.3/lib/*.jar usr/versions/apache-ant-${VERSION}/lib
rm -fr apache-ivy-2.5.3
mkdir -p svnant-1.3.1
cd svnant-1.3.1
${THOME}/build/unpack svnant-1.3.1
cd ..
cp svnant-1.3.1/lib/svnant.jar usr/versions/apache-ant-${VERSION}/lib
cp svnant-1.3.1/lib/svnClientAdapter.jar usr/versions/apache-ant-${VERSION}/lib
rm -fr svnant-1.3.1
#
# clean up
#
rm usr/versions/apache-ant-${VERSION}/bin/*.bat
rm usr/versions/apache-ant-${VERSION}/bin/*.cmd
