#!/bin/sh
#
VERSION=1.10.12
mkdir -p usr/bin
ln -s ../versions/apache-ant-${VERSION}/bin/ant usr/bin/ant
#
# add extras
#
${THOME}/build/unpack apache-ivy-2.5.0-bin-with-deps
cp apache-ivy-2.5.0/ivy-2.5.0.jar usr/versions/apache-ant-${VERSION}/lib
cp apache-ivy-2.5.0/lib/*.jar usr/versions/apache-ant-${VERSION}/lib
rm -fr apache-ivy-2.5.0
mkdir -p svnant-1.3.1
cd svnant-1.3.1
${THOME}/build/unpack svnant-1.3.1
cd ..
cp svnant-1.3.1/lib/svnant.jar usr/versions/apache-ant-${VERSION}/lib
cp svnant-1.3.1/lib/svnClientAdapter.jar usr/versions/apache-ant-${VERSION}/lib
rm -fr svnant-1.3.1
# jsch is already supplied via ivy
#cp ${THOME}/tarballs/jsch-0.1.55.jar usr/versions/apache-ant-${VERSION}/lib
#
# clean up
#
rm usr/versions/apache-ant-${VERSION}/bin/*.bat
rm usr/versions/apache-ant-${VERSION}/bin/*.cmd
