#!/bin/sh
#
VERSION=1.10.6
mkdir -p usr/bin
ln -s ../versions/apache-ant-${VERSION}/bin/ant usr/bin/ant
#
rm usr/versions/apache-ant-${VERSION}/bin/*.bat
rm usr/versions/apache-ant-${VERSION}/bin/*.cmd
