#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# solaris auths
#
mkdir -p etc/security/auth_attr.d
mkdir -p etc/security/prof_attr.d
cat > etc/security/auth_attr.d/trousers <<EOF
solaris.smf.value.tcsd:::Change TPM Administration value properties::
solaris.smf.manage.tcsd:::Manage TPM Administration service states::
EOF
cat > etc/security/prof_attr.d/trousers <<EOF
TPM Administration::::auths=solaris.smf.manage.tcsd,solaris.smf.value.tcsd
EOF

#
# install service manifest and method
#
mkdir -p lib/svc/method
cp ${BUILDROOT}/patches/trousers/tcsd.sh lib/svc/method/tcsd.sh
chmod 555 lib/svc/method/tcsd.sh

mkdir -p lib/svc/manifest/application/security
cp ${BUILDROOT}/patches/trousers/tcsd.xml lib/svc/manifest/application/security/tcsd.xml
chmod 444 lib/svc/manifest/application/security/tcsd.xml
