#!/bin/sh
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# remove la files, safe as OI never shipped them either
#
/bin/rm usr/lib/libtspi.la
/bin/rm usr/lib/${ARCH64}/libtspi.la

#
# solaris auths
#
mkdir -p etc/security/auth_attr.d
mkdir -p etc/security/prof_attr.d
cat > etc/security/auth_attr.d/trousers <<EOF
solaris.smf.value.tcsd:::Change TPM Administation value properties::
solaris.smf.manage.tcsd:::Manage TPM Administration service states::
EOF
cat > etc/security/prof_attr.d/trousers <<EOF
TPM Administration::::auths=solaris.smf.manage.tcsd,solaris.smf.value.tcsd
EOF

#
# this is a horrid assumption, that we have an old version of trousers
# installed and copy its manifest and method
#
if [ -f /lib/svc/method/tcsd.sh ]; then
  mkdir -p lib/svc/method
  cat /lib/svc/method/tcsd.sh | sed s:/usr/lib/tcsd:/usr/sbin/tcsd: > lib/svc/method/tcsd.sh
  chmod 555 lib/svc/method/tcsd.sh
fi
if [ -f /lib/svc/manifest/application/security/tcsd.xml ]; then
  mkdir -p lib/svc/manifest/application/security
  cp -p /lib/svc/manifest/application/security/tcsd.xml lib/svc/manifest/application/security
fi
