#!/bin/sh
#
# Yurk; why doesn't the installer do this?
#

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

if [ ! -f usr/etc/pango/pango.modules ]; then
    mkdir -p usr/etc/pango
    env LD_LIBRARY_PATH=./usr/lib ./usr/bin/pango-querymodules > usr/etc/pango/pango.modules
fi

#
# pango.modules embeds the actual full paths to files, so the 64-bit
# version needs a different file
#
if [ ! -f usr/etc/${ARCH64}/pango/pango.modules ]; then
    mkdir -p usr/etc/${ARCH64}/pango
    env LD_LIBRARY_PATH=./usr/lib/${ARCH64} ./usr/bin/${ARCH64}/pango-querymodules > usr/etc/${ARCH64}/pango/pango.modules
fi
