#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
awk '
{if ($3 ~ /^usr\/bin\/Xorg/) { $5 = "root" ; $4 = "04555" }}
{print}
'
