#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
NPWD=`pwd`
NVER=`basename $NPWD`
case $NPWD in
*-64bit)
    echo "skip 64-bit fix"
    ;;
*)
    mkdir -p ${DESTDIR}/usr/share/man/man1
    cp man/scanpci.1 ${DESTDIR}/usr/share/man/man1/scanpci.1
    mkdir -p ${DESTDIR}/usr/bin
    cp scanpci/.libs/scanpci ${DESTDIR}/usr/bin
    ;;
esac
