#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# put commands in the default path
#
VERSION=3
# exit 0
mkdir -p usr/bin usr/share/man/man1
ln -s ../../usr/versions/ruby-${VERSION}/bin/ruby usr/bin/ruby
ln -s ../../usr/versions/ruby-${VERSION}/bin/erb usr/bin/erb
ln -s ../../usr/versions/ruby-${VERSION}/bin/irb usr/bin/irb
ln -s ../../usr/versions/ruby-${VERSION}/bin/gem usr/bin/gem
ln -s ../../usr/versions/ruby-${VERSION}/bin/ri usr/bin/ri
ln -s ../../usr/versions/ruby-${VERSION}/bin/rake usr/bin/rake
ln -s ../../usr/versions/ruby-${VERSION}/bin/rdoc usr/bin/rdoc
ln -s ../../usr/versions/ruby-${VERSION}/bin/bundle usr/bin/bundle
ln -s ../../usr/versions/ruby-${VERSION}/bin/bundler usr/bin/bundler
ln -s ../../../../usr/versions/ruby-${VERSION}/share/man/man1/ruby.1 usr/share/man/man1
ln -s ../../../../usr/versions/ruby-${VERSION}/share/man/man1/erb.1 usr/share/man/man1
ln -s ../../../../usr/versions/ruby-${VERSION}/share/man/man1/irb.1 usr/share/man/man1
ln -s ../../../../usr/versions/ruby-${VERSION}/share/man/man1/ri.1 usr/share/man/man1
