#!/bin/sh
#
# we've never shipped la files for libffi so it's safe to delete them
#
rm usr/lib/lib*.la
rm usr/lib/amd64/lib*.la
#
# symlink previous library version for app compatibility
#
cd usr/lib
ln -s libffi.so.6.0.1 libffi.so.5
cd amd64
ln -s libffi.so.6.0.1 libffi.so.5
#
# don't duplicate the includes
#
rm -fr libffi-3.0.13
ln -s ../libffi-3.0.13 .
