#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# fixinstall.64 saved the 64-bit ffi.h for us, now
# we wrap it
#
mv usr/include/ffi.h usr/include/ffi-32.h
cp ${BUILDROOT}/patches/ffi.h usr/include/ffi.h
#
# symlink previous library version for app compatibility
#
cd usr/lib
ln -s libffi.so.6.0.4 libffi.so.5
cd $ARCH64
ln -s libffi.so.6.0.4 libffi.so.5
