#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add a g-prefixed link
#
rm -f usr/gnu/lib/charset.alias
rmdir usr/gnu/lib
mkdir -p usr/bin
mkdir -p usr/share/man/man1
cd usr/bin
ln -s ../gnu/bin/make gmake
cd ../..
cd usr/share/man/man1
ln -s ../../../gnu/share/man/man1/make.1 gmake.1
