#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
/bin/rm -fr usr/perl5/5.34/lib
#
# put the commands in the normal path so users can find them
#
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/perl5/5.34/bin/* .
cd ../..
