#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
rm -f usr/lib/xfce4/panel/plugins/lib*.la
rm -f usr/lib/tumbler-1/plugins/tumbler*.la
rm -f usr/lib/tumbler-1/plugins/cache/tumbler-xdg-cache.la
rm -f usr/lib/thunarx-3/thunar*.la
rm -f usr/lib/gio/modules/libxfconfgsettingsbackend.la
rm -f usr/lib/*/xfce4/panel/plugins/lib*.la
rm -f usr/lib/*/tumbler-1/plugins/tumbler*.la
rm -f usr/lib/*/tumbler-1/plugins/cache/tumbler-xdg-cache.la
rm -f usr/lib/*/thunarx-3/thunar*.la
rm -f usr/lib/*/gio/modules/libxfconfgsettingsbackend.la

#
# get all the icons in place
# assumes the gnome icon theme is installed
#
mkdir -p usr/share/icons/hicolor/16x16/apps
mkdir -p usr/share/icons/hicolor/24x24/apps
mkdir -p usr/share/icons/hicolor/48x48/apps
mkdir -p usr/share/icons/hicolor/16x16/actions
mkdir -p usr/share/icons/hicolor/24x24/actions
mkdir -p usr/share/icons/hicolor/48x48/actions
mkdir -p usr/share/icons/hicolor/16x16/places
mkdir -p usr/share/icons/hicolor/24x24/places
mkdir -p usr/share/icons/hicolor/48x48/places
mkdir -p usr/share/icons/hicolor/16x16/devices
mkdir -p usr/share/icons/hicolor/24x24/devices
mkdir -p usr/share/icons/hicolor/48x48/devices
mkdir -p usr/share/icons/hicolor/16x16/categories
mkdir -p usr/share/icons/hicolor/24x24/categories
mkdir -p usr/share/icons/hicolor/48x48/categories
mkdir -p usr/share/icons/hicolor/16x16/mimetypes
mkdir -p usr/share/icons/hicolor/24x24/mimetypes
mkdir -p usr/share/icons/hicolor/48x48/mimetypes

#
# remember where we are so it's easier to get back to square one
#
MYDIR=`/bin/pwd`

SIZE="16x16"
cd usr/share/icons/hicolor/${SIZE}/apps
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-theme.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-wallpaper.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-keyboard.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-system-windows.png .
ln -s ../../../gnome/${SIZE}/apps/web-browser.png .
ln -s ../../../gnome/${SIZE}/apps/utilities-terminal.png .
ln -s ../../../gnome/${SIZE}/apps/system-file-manager.png .
ln -s ../../../gnome/${SIZE}/apps/file-manager.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/actions
ln -s ../../../gnome/${SIZE}/actions/gtk-remove.png
ln -s ../../../gnome/${SIZE}/actions/gtk-fullscreen.png
ln -s ../../../gnome/${SIZE}/actions/system-log-out.png
ln -s ../../../gnome/${SIZE}/actions/gtk-help.png
ln -s ../../../gnome/${SIZE}/actions/gtk-find.png
ln -s ../../../gnome/${SIZE}/actions/gtk-quit.png
ln -s ../../../gnome/${SIZE}/actions/gtk-refresh.png
ln -s ../../../gnome/${SIZE}/actions/gtk-execute.png
ln -s ../../../gnome/${SIZE}/actions/insert-link.png
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/places
ln -s ../../../gnome/${SIZE}/places/user-desktop.png .
ln -s ../../../gnome/${SIZE}/places/folder.png .
ln -s ../../../gnome/${SIZE}/places/inode-directory.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/devices
ln -s ../../../gnome/${SIZE}/devices/video-display.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/categories
ln -s ../../../gnome/${SIZE}/categories/applications-system.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-system.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-desktop-peripherals.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-desktop.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/mimetypes
ln -s ../../../gnome/${SIZE}/mimetypes/application-x-executable.png .
ln -s ../../../gnome/${SIZE}/mimetypes/x-office-calendar.png office-calendar.png

SIZE="24x24"
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/apps
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-accessibility.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-wallpaper.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-theme.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-keyboard.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-system-windows.png .
ln -s ../../../gnome/${SIZE}/apps/web-browser.png .
ln -s ../../../gnome/${SIZE}/apps/utilities-terminal.png .
ln -s ../../../gnome/${SIZE}/apps/system-file-manager.png .
ln -s ../../../gnome/${SIZE}/apps/file-manager.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/actions
ln -s ../../../gnome/${SIZE}/actions/gtk-remove.png
ln -s ../../../gnome/${SIZE}/actions/system-log-out.png
ln -s ../../../gnome/${SIZE}/actions/gtk-fullscreen.png
ln -s ../../../gnome/${SIZE}/actions/gtk-help.png
ln -s ../../../gnome/${SIZE}/actions/gtk-find.png
ln -s ../../../gnome/${SIZE}/actions/gtk-quit.png
ln -s ../../../gnome/${SIZE}/actions/gtk-refresh.png
ln -s ../../../gnome/${SIZE}/actions/gtk-execute.png
ln -s ../../../gnome/${SIZE}/actions/insert-link.png
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/places
ln -s ../../../gnome/${SIZE}/places/user-desktop.png .
ln -s ../../../gnome/${SIZE}/places/folder.png .
ln -s ../../../gnome/${SIZE}/places/inode-directory.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/devices
ln -s ../../../gnome/${SIZE}/devices/video-display.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/categories
ln -s ../../../gnome/${SIZE}/categories/applications-system.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-system.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-desktop-peripherals.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-desktop.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/mimetypes
ln -s ../../../gnome/${SIZE}/mimetypes/application-x-executable.png .
ln -s ../../../gnome/${SIZE}/mimetypes/x-office-calendar.png office-calendar.png

SIZE="48x48"
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/apps
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-accessibility.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-wallpaper.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-theme.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-desktop-keyboard.png .
ln -s ../../../gnome/${SIZE}/apps/preferences-system-windows.png .
ln -s ../../../gnome/${SIZE}/apps/web-browser.png .
ln -s ../../../gnome/${SIZE}/apps/utilities-terminal.png .
ln -s ../../../gnome/${SIZE}/apps/system-file-manager.png .
ln -s ../../../gnome/${SIZE}/apps/file-manager.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/actions
ln -s ../../../gnome/${SIZE}/actions/gtk-remove.png
ln -s ../../../gnome/${SIZE}/actions/system-log-out.png
ln -s ../../../gnome/${SIZE}/actions/gtk-fullscreen.png
ln -s ../../../gnome/${SIZE}/actions/gtk-help.png
ln -s ../../../gnome/${SIZE}/actions/gtk-find.png
ln -s ../../../gnome/${SIZE}/actions/gtk-quit.png
ln -s ../../../gnome/${SIZE}/actions/gtk-refresh.png
ln -s ../../../gnome/${SIZE}/actions/gtk-execute.png
ln -s ../../../gnome/${SIZE}/actions/insert-link.png
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/places
ln -s ../../../gnome/${SIZE}/places/user-desktop.png .
ln -s ../../../gnome/${SIZE}/places/folder.png .
ln -s ../../../gnome/${SIZE}/places/inode-directory.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/devices
ln -s ../../../gnome/${SIZE}/devices/video-display.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/categories
ln -s ../../../gnome/${SIZE}/categories/applications-system.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-system.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-desktop-peripherals.png .
ln -s ../../../gnome/${SIZE}/categories/preferences-desktop.png .
cd $MYDIR
cd usr/share/icons/hicolor/${SIZE}/mimetypes
ln -s ../../../gnome/${SIZE}/mimetypes/application-x-executable.png .
ln -s ../../../gnome/${SIZE}/mimetypes/x-office-calendar.png office-calendar.png

#
# ugly fix to pass timezone to the panel clock
# and for it to display it
#
cd $MYDIR
cd usr/etc/xdg/xfce4
mv xinitrc tt1
head -80 tt1 > xinitrc
echo eval \`grep \'^TZ=\' /etc/default/init\` >> xinitrc
echo export TZ >> xinitrc
tail +80 tt1 >> xinitrc
rm tt1
cd $MYDIR
cd usr/share ; ln -s lib/zoneinfo .
