#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# the repo itself lives here (although it's usually a zfs dataset)
#
mkdir -p var/repo

#
# where the dehydrated well known location is
#
mkdir -p var/dehydrated/acme-challenge/pkgs.tribblix.org

#
# where the ssl certificates themselves live
#
mkdir -p var/sslcerts/pkgs.tribblix.org
echo "pkgs.tribblix.org" > var/sslcerts/pkgs.tribblix.org/domains.txt
cp ${BUILDROOT}/patches/repo-dehydrated.config var/sslcerts/pkgs.tribblix.org/config

#
# this is the starting nginx configuration
#
mkdir -p opt/tribblix/nginx/sites-enabled
cp ${BUILDROOT}/patches/pkgs.tribblix.org.conf opt/tribblix/nginx/sites-enabled/pkgs.tribblix.org.conf

#
# these are the helper scripts
#
mkdir -p opt/tribblix/repo/scripts
cp ${BUILDROOT}/patches/repo-ipxe.sh opt/tribblix/repo/scripts/repo-ipxe
