#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.la'`
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.a'`
#
# our Xorg is older, so need this fix, see report in
# https://github.com/tribblix/build/issues/17#issuecomment-3434605990
#
sed -i 's:GPUDevice:#GPUDevice:' etc/X11/xrdp/xorg.conf 
