#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   mkdir -p ${DESTDIR}
fi

cd ../serf-1.3.8
scons PREFIX=${DESTDIR}/usr/versions/subversion-1.9 install
