#!/bin/sh
#
# pkgproto generates garbage when fed hard links, so a symlink is just as good
#
VERSION=24.5
rm usr/versions/emacs-${VERSION}/bin/emacs
ln -s emacs-${VERSION} usr/versions/emacs-${VERSION}/bin/emacs 
