#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# the man pages come in a separate download
#
# sparc downrev due to rust dependency
#
case `uname -p` in
sparc)
  GITVER=2.54.0
  ;;
i386)
  GITVER=2.55.0
  ;;
esac


mkdir -p usr/share/man
cd usr/share/man
${BUILDROOT}/unpack git-manpages-${GITVER}
chmod a+rx .
cd ../../..
#
# it doesn't know where perl is
#
mkdir -p usr/perl5/site_perl/$(${THOME}/build/getperlver)
mv usr/share/perl5/* usr/perl5/site_perl/$(${THOME}/build/getperlver)
rmdir usr/share/perl5
