#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# the man pages come in a separate download
#
mkdir -p usr/share/man
cd usr/share/man
${BUILDROOT}/unpack git-manpages-2.51.0
chmod a+rx .
cd ../../..
#
# it doesn't know where perl is
#
mkdir -p usr/perl5/site_perl/5.34
mv usr/share/perl5/* usr/perl5/site_perl/5.34
rmdir usr/share/perl5
