#!/bin/sh
#
# swatches has files whose names contain spaces, so we unpack them
# rather than package them
#
cd ${BASEDIR}/usr/share/scribus
if [ -f swatches.tar ]; then
  /usr/bin/tar xf swatches
  /usr/bin/chown -hR root:root swatches
  /usr/bin/chmod -R a+rX swatches
fi
