diff -wpruN '--exclude=*.orig' a~/makefile.common a/makefile.common
--- a~/makefile.common	1970-01-01 00:00:00
+++ a/makefile.common	1970-01-01 00:00:00
@@ -1,10 +1,10 @@
 MKDIR = mkdir -p
 
-DEST_HOME=/usr/local
-DEST_BIN=$(DEST_HOME)/bin
-DEST_SHARE=$(DEST_HOME)/lib/p7zip
-DEST_SHARE_DOC=$(DEST_HOME)/share/doc/p7zip
-DEST_MAN=$(DEST_HOME)/man
+#DEST_HOME=/usr/local
+#DEST_BIN=$(DEST_HOME)/bin
+#DEST_SHARE=$(DEST_HOME)/lib/p7zip
+#DEST_SHARE_DOC=$(DEST_HOME)/share/doc/p7zip
+#DEST_MAN=$(DEST_HOME)/man
 
 .PHONY: default all all2 7za 7zG 7zFM sfx 7z 7zr Client7z common common7z LangAndHelp tar_bin depend test test_7z test_7zr test_7zG test_Client7z LzmaCon test_LzmaCon  all_test app cppcheck lzham test_lib other
 
