#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# These are old closed binaries from DevPro
# They used to be supplied as part of the make package, but that is now
# delivered by illumos, with just make, so the old as and sccs bits that
# used to be part of that package are now in their own packages
#
# The tarball was created on an older system, we just unpack it here
#
case `uname -p` in
    i386)
	tar xf ${BUILDROOT}/patches/binary-sccs-files.tar
	;;
    sparc)
	tar xf ${BUILDROOT}/patches/binary-sccs-files.sparc.tar
	;;
esac
