#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# just clone the repo
#
mkdir -p usr/versions
cd usr/versions
git clone https://github.com/opendtrace/toolkit
cd toolkit
git checkout illumos
cd ..
mv toolkit dtrace-toolkit
ln -s dtrace-toolkit DTT
rm -fr dtrace-toolkit/.git
