#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# remove everything except the qt gui
#

mv usr/bin/wireshark .
mv usr/share/applications/org.wireshark.Wireshark.desktop .
rm -fr usr
mkdir -p usr/bin
mv wireshark usr/bin/wireshark
mkdir -p usr/share/applications
mv org.wireshark.Wireshark.desktop usr/share/applications/org.wireshark.Wireshark.desktop
