#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# The original solaris had ssh split into 3 packages
# We replicate the split here, although TRIBnet-ssh-ssh-key and
# ssh-keysign are now deprecated
#

mv usr .usr

mkdir -p usr/sbin
mkdir -p usr/lib/ssh
mkdir -p usr/share/man/man8
mkdir -p usr/share/man/man5

mv .usr/lib/ssh/sftp-server usr/lib/ssh/sftp-server
mv .usr/sbin/sshd usr/sbin/sshd
mv .usr/share/man/man8/sftp-server.8 usr/share/man/man8/sftp-server.8
mv .usr/share/man/man8/sshd.8 usr/share/man/man8/sshd.8
mv .usr/share/man/man5/sshd_config.5 usr/share/man/man5/sshd_config.5

rm -f etc/ssh/moduli
rm -f etc/ssh/ssh_config

rm -fr .usr

#
# Now add the SMF services
#
mkdir -p lib/svc/manifest/network
mkdir -p lib/svc/method
cp ${BUILDROOT}/patches/openssh-ssh.xml lib/svc/manifest/network/ssh.xml
cp ${BUILDROOT}/patches/openssh-method lib/svc/method/sshd
chmod 444 lib/svc/manifest/network/ssh.xml
chmod 555 lib/svc/method/sshd
