#!/bin/sh
rm -f usr/lib/libcanberra-0.30/*.la
rm -f usr/lib/*/libcanberra-0.30/*.la
rm -f usr/lib/gtk-3.0/modules/*.la
rm -f usr/lib/*/gtk-3.0/modules/*.la
rm -fr usr/share/gdm
rm -fr usr/share/gnome
