#!/bin/sh
PYVERS=3.7

mkdir -p usr/bin

cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/pg_activity .
cd ../..

mkdir -p usr/share/man/man1
mv usr/versions/python-${PYVERS}/share/man/man1/pg_activity.1 usr/share/man/man1
rmdir usr/versions/python-${PYVERS}/share/man/man1
rmdir usr/versions/python-${PYVERS}/share/man
rmdir usr/versions/python-${PYVERS}/share
