#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
rm -f usr/lib/*/mate-settings-daemon/lib*.la
rm -f usr/lib/mate-settings-daemon/lib*.la
rm -f usr/lib/*/mate-settings-daemon/lib*.a
rm -f usr/lib/mate-settings-daemon/lib*.a
