#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# palettes has files whose names contain spaces, so we unpack them
# rather than package them
#
cd ${BASEDIR}/usr/versions/Umlet
if [ -d palettes ]; then
  /usr/bin/rm -fr palettes
fi
