#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we don't ship .la files for base libraries
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.la'`
#
# or static libraries by default
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.a'`
#
# don't ship documentation
#
/usr/bin/rm -fr usr/share/doc
#
# this will remove the directory if it's empty
# if there are manpages, then it will have no effect
#
/usr/bin/rmdir usr/share
#
# workarounds for applications we don't have
#
rm -f etc/drirc
rmdir etc
#
# we now have to shuffle a bunch of stuff around
# this is all tied up with TRIBsvc-opengl-ogl-select
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# headers
#
mv usr/include/GL usr/include/mesa
mkdir -p usr/include/GL/internal
cd usr/include/GL
ln -s ../mesa/osmesa.h osmesa.h
cd internal
ln -s ../../mesa/internal/dri_interface.h dri_interface.h
cd ..
ln -s ../mesa/GLw* .
ln -s ../mesa/glu.h .
cd ../../..
#
# libraries really end up in /usr/lib/mesa
#
mkdir -p usr/lib/mesa/${ARCH64}
mv usr/lib/${ARCH64}/lib* usr/lib/mesa/${ARCH64}
mv usr/lib/lib* usr/lib/mesa
rm -f usr/lib/64
ln -s ${ARCH64} usr/lib/mesa/64
#
# but there's a population in /usr/lib/GL
#
mkdir -p usr/lib/GL/${ARCH64}
cd usr/lib/GL
ln -s ../mesa/libglapi.so* .
ln -s ../mesa/libgbm.so* .
ln -s ../mesa/libGLU.so* .
ln -s ../mesa/libGLw.so* .
cd ${ARCH64}
ln -s ../../mesa/${ARCH64}/libglapi.so* .
ln -s ../../mesa/${ARCH64}/libgbm.so* .
ln -s ../../mesa/${ARCH64}/libGLU.so* .
ln -s ../../mesa/${ARCH64}/libGLw.so* .
cd ../../../..
#
# and some symlinks in the default places
#
cd usr/lib
ln -s GL/libGLU* .
ln -s GL/libGLw* .
ln -s GL/libglapi.* .
ln -s GL/libgbm.* .
cd ${ARCH64}
ln -s ../GL/${ARCH64}/libGLU* .
ln -s ../GL/${ARCH64}/libGLw* .
ln -s ../GL/${ARCH64}/libglapi.* .
ln -s ../GL/${ARCH64}/libgbm.* .
cd ../../..
