#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fix default applications
#
sed -i s:firefox:palemoon: etc/pekwm/vars
sed -i s:worker:Thunar: etc/pekwm/vars
sed -i s:xedit:emacs: etc/pekwm/vars
sed -i s:+sb:-sb: etc/pekwm/vars
#
# add some themes
#
cd usr/share/pekwm/themes
#
# http://box-look.org/content/show.php/Win7?content=162490
#
${BUILDROOT}/unpack pekwm-theme-win7
chmod -R a+r win7
#
# http://box-look.org/content/show.php/Menda+Pekwm+Theme?content=170660
#
${BUILDROOT}/unpack Menda-Pekwm-Theme-master
mv Menda-Pekwm-Theme-master/Menda Menda
rm -fr Menda-Pekwm-Theme-master
chmod -R a+r Menda
#
# https://www.box-look.org/p/1172379
#
${BUILDROOT}/unpack Curvy
chmod -R a+r Curvy
