#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#

#
# stupid libtool embeds the relative build-time pathname of the library
# in the binaries, so we need to fix that
#
cd usr/bin
elfedit -e 'dyn:value -dynndx -s 1 libaudiofile.so' sfinfo
elfedit -e 'dyn:value -dynndx -s 1 libaudiofile.so' sfconvert
