#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
mkdir -p usr/lib/X11
cd usr/lib/X11
cp ${BUILDROOT}/patches/mkcookie.c .
gcc -m64 -O -DTCPCONN -DUNIXCONN -DIPv6 -c mkcookie.c
gcc -m64 -o mkcookie mkcookie.o -lsocket -lnsl -lXau
rm -f mkcookie.o mkcookie.c
