#!/bin/sh
#
rm -fr usr/share/gtk-doc


#
# we need to install poppler-data as well
#

DESTDIR=`pwd`

TPOPDIR=/tmp/pop.$$
mkdir $TPOPDIR
cd $TPOPDIR

${BUILDROOT}/unpack poppler-data-0.4.7
cd poppler-data-0.4.7
TBINDIR=/tmp/bin.$$
mkdir $TBINDIR
ln -s /usr/bin/ginstall ${TBINDIR}/install
env PATH=${TBINDIR}:$PATH gmake DESTDIR=${DESTDIR} prefix=/usr install
rm -fr ${TBINDIR}

cd /
rm -fr $TPOPDIR
