#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
/bin/rm -f usr/gnu/lib/charset.alias
/bin/rm -fr usr/gnu/share/doc
mkdir -p usr/share
mv usr/gnu/share/aclocal usr/share
rm -f usr/gnu/lib/lib*.la
rm -f usr/gnu/lib/*/lib*.la
