#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add the default skin, without which things will fail
#
mkdir -p usr/share/mplayer/skins
cd usr/share/mplayer/skins
${BUILDROOT}/unpack Blue-1.12
ln -s Blue default
