#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# remove static plugins
#
/usr/bin/rm -f usr/lib/xrdp/lib*.a
#
# don't ship keys, create them on install
#
/usr/bin/rm -f etc/xrdp/cert.pem
/usr/bin/rm -f etc/xrdp/key.pem
