#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# this part of dbus ships just the libraries and headers
#
rm -fr usr/share
rm -fr etc
rm -fr usr/bin
rm -f usr/lib/dbus-daemon
rm -f usr/lib/dbus-daemon-launch-helper
