#!/bin/sh
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
PREFIX=usr/versions/openssl-3
rmdir ${PREFIX}/ssl/certs
ln -s /etc/ssl/certs ${PREFIX}/ssl
#
# we don't want the html docs
#
rm -fr ${PREFIX}/share/doc
#
# no static libraries
#
rm -f ${PREFIX}/lib/lib*.a
rm -f ${PREFIX}/lib/${ARCH64}/lib*.a
#
# FIXME do we need to relocate the manpage directory?
#
#
# there are almost 3500 symlinks here, cut the clutter
#
rm -fr ${PREFIX}/share/man/man3
#
# we no longer fiddle the manpage suffix, but some man pages conflict
#
# FIXME - what we want to do is remove anything in man1 that's a symlink
# to openssl-cmds.1ossl, because those are the short names that will
# create conflicts
#
mv ${PREFIX}/share/man/man1/errstr.1 ${PREFIX}/share/man/man1/openssl-errstr.1
mv ${PREFIX}/share/man/man1/passwd.1 ${PREFIX}/share/man/man1/openssl-passwd.1
mv ${PREFIX}/share/man/man1/rehash.1 ${PREFIX}/share/man/man1/openssl-rehash.1
rm ${PREFIX}/share/man/man1/openssl-c_rehash.1
#
# we should have a 64-bit configuration.h saved, now fix it to be dual-arch
#
mv ${PREFIX}/include/openssl/configuration.h ${PREFIX}/include/openssl/configuration-32.h
cp ${BUILDROOT}/patches/openssl-configuration.h ${PREFIX}/include/openssl/configuration.h
#
# FIXME that's it for non-release
#
exit 0
#
# libraries expect to live in /lib
#
mv usr/lib/64 usr/lib/${ARCH64}
mkdir -p lib/${ARCH64}
mv usr/lib/lib*so* lib
mv usr/lib/${ARCH64}/lib*so* lib/${ARCH64}
#
# save copies of the openssl 1.1 libraries
# which most applications are initially linked against
# so they continue to work
#
# the assumption here is that the legacy 1.0 version is shipped
# in a separate compat package
#
cp -p /lib/libssl.so.1.1 lib/libssl.so.1.1
cp -p /lib/libcrypto.so.1.1 lib/libcrypto.so.1.1
cp -p /lib/${ARCH64}/libssl.so.1.1 lib/${ARCH64}/libssl.so.1.1
cp -p /lib/${ARCH64}/libcrypto.so.1.0.0 lib/${ARCH64}/libcrypto.so.1.1
#
# and we need to keep the 1.1 engines
#
mkdir -p usr/lib/engines-1.1
mkdir -p usr/lib/${ARCH64}/engines-1.1
cp -p /usr/lib/engines-1.1/* usr/lib/engines-1.1
cp -p /usr/lib/${ARCH64}/engines-1.1/* usr/lib/${ARCH64}/engines-1.1
#
# the files live under /lib, symlinks under /usr/lib
# this will also generate the compat symlinks in /usr/lib
#
cd usr/lib
ln -s ../../lib/libssl.so* .
ln -s ../../lib/libcrypto.so* .
cd ${ARCH64}
ln -s ../../../lib/${ARCH64}/libssl.so* .
ln -s ../../../lib/${ARCH64}/libcrypto.so* .
