#!/bin/sh
#
# pkgproto generates garbage when fed hard links, so a symlink is just as good
#
VERSION=9.2.7.0
#
# jruby 9k was a bit broken on solarish systems and gem hasn't always
# worked right so wasn't always the default
#
mkdir -p usr/bin
ln -s ../../usr/versions/jruby-${VERSION}/bin/jruby usr/bin/
ln -s ../../usr/versions/jruby-${VERSION}/bin/jrubyc usr/bin/
ln -s ../../usr/versions/jruby-${VERSION}/bin/jgem usr/bin/
ln -s ../../usr/versions/jruby-${VERSION}/bin/jirb usr/bin/

cd usr/versions/jruby-${VERSION}
rm bin/*.bat
rm bin/jruby.sh bin/jruby.bash bin/jruby200.sh
rm bin/*.exe
rm bin/*.dll
rm -fr lib/ruby/stdlib/ffi/platform/*linux
rm -fr lib/ruby/stdlib/ffi/platform/*darwin
rm -fr lib/ruby/stdlib/ffi/platform/*cygwin
rm -fr lib/ruby/stdlib/ffi/platform/*windows
rm -fr lib/ruby/stdlib/ffi/platform/*bsd
rm -fr lib/ruby/stdlib/ffi/platform/*aix
rm -fr lib/ruby/stdlib/ffi/platform/*gnu
rm -fr lib/jni/*Windows
rm -fr lib/jni/*Linux
rm -fr lib/jni/*BSD
rm -fr lib/jni/*AIX
rm -fr lib/jni/Darwin
#
# We need to fix the jruby script as the Solaris/illumos
# basename in /usr/bin is utter bilge. Either the xpg4 or
# the gnu version is fine, both are in the base overlay.
#
gsed -i 's:basename:/usr/xpg4/bin/basename:g' bin/jruby
#
# build nailgun
#
if [ -f tool/nailgun/configure ]; then
    cd tool/nailgun
    ./configure
    make
    if [ -f ng ]; then
	mv ng ../../bin
    fi
    rm -f config.log
    rm -f config.status
    rm -f ng.exe
    rm -f Makefile
fi
