#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
PYVERS=3.11
#
# clean up tests, some files have interesting names
#
rm -fr usr/versions/python-3.11/lib/python3.11/site-packages/pelican/tests
#
# add a convenience link
#
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/pelican* .
