#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
awk '
{if ($3 ~ /^opt\/tribblix\/rabbitmq\/var/) { $6 = "rabbitmq" ; $5 = "rabbitmq" }}
{if ($3 ~ /^opt\/tribblix\/rabbitmq\/etc/) { $6 = "rabbitmq" ; $5 = "rabbitmq" }}
{print}
'
