#!/bin/sh
#
# replace the 32-bit binary with the 64-bit one
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

if [ -x usr/bin/${ARCH64}/plaympeg ]; then
  mv usr/bin/${ARCH64}/plaympeg usr/bin/plaympeg
fi
