#!/bin/sh
#
# plaympeg is the name used by smpeg, for smpeg2 use the name
# plaympeg2 so as not to conflict
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

mv usr/bin/plaympeg usr/bin/plaympeg2
mv usr/bin/$ARCH64/plaympeg usr/bin/$ARCH64/plaympeg2
mv usr/share/man/man1/plaympeg.1 usr/share/man/man1/plaympeg2.1
