#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# we don't ship .la files for base libraries
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.la'`
#
# don't ship documentation
#
/usr/bin/rm -fr usr/share/doc
#
# this will remove the directory if it's empty
# if there are manpages, then it will have no effect
#
/usr/bin/rmdir usr/share

#
# only ship the 64-bit binaries
#
if [ -d usr/bin/${ARCH64} ]; then
    cd usr/bin/${ARCH64}
    mv * ..
    cd ..
    rmdir ${ARCH64}
    cd ../..
fi
