#!/bin/sh
rm -fr usr/share/doc/ImageMagick-*/www
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ARCH32="sparcv7"
  ;;
i386)
  ARCH64="amd64"
  ARCH32="i86"
  ;;
esac
#
rm -f usr/lib/lib*.la
rm -f usr/lib/${ARCH64}/lib*.la

#
# we need to ship 32-bit libraries, but aren't interested in
# 32-bit binaries, so drop those entirely and ship 64-bit by default
#
for imbin in animate compare composite conjure convert display identify import mogrify montage stream
do
    rm -f usr/bin/$imbin
    mv usr/bin/${ARCH64}/$imbin usr/bin/$imbin
done
#
# we need to ship the existing 32-bit config scripts
#
