#!/bin/sh
rm -fr usr/share/doc/ImageMagick-*/www
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ARCH32="sparcv7"
  ;;
i386)
  ARCH64="amd64"
  ARCH32="i86"
  ;;
esac
#
rm -f usr/lib/lib*.la
rm -f usr/lib/${ARCH64}/lib*.la

#
# we need to ship 32-bit libraries, but aren't interested
# in 32-bit binaries, so drop those entirely
#
rm -f usr/bin/animate
rm -f usr/bin/compare
rm -f usr/bin/composite
rm -f usr/bin/conjure
rm -f usr/bin/convert
rm -f usr/bin/display
rm -f usr/bin/identify
rm -f usr/bin/import
rm -f usr/bin/mogrify
rm -f usr/bin/montage
rm -f usr/bin/stream
#
# we need to ship the existing 32-bit config scripts
#
# we still isaexec the 64-bit binaries for now
#
