#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# add a g-prefixed link
#
rm -f usr/gnu/lib/charset.alias
rmdir usr/gnu/lib
rmdir usr/gnu/var
mkdir -p usr/bin
cd usr/bin
ln -s ../gnu/bin/find gfind
ln -s ../gnu/bin/xargs gxargs
