#!/bin/sh
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
nawk '
{if ($3 ~ /^usr\/libexec\/s-nail-dotlock/) { $6 = "root" ; $5 = "root" ; $4 = "04111" }}
{print}
'
