#!/bin/sh
#
# just name off the primary version
#
VERSION=8.0.26
cd usr/versions
ln -s apache-tomcat-${VERSION} tomcat8
chmod a+x apache-tomcat-${VERSION}/bin/*.sh
rm apache-tomcat-${VERSION}/bin/*.bat
