#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# The original solaris had ssh split into 3 packages
# We replicate the split here, although TRIBnet-ssh-ssh-key and
# ssh-keysign are now deprecated
#

# remove files that used to be shipped in TRIBnet-ssh-ssh-key
rm -f usr/lib/ssh/ssh-keysign
rm -f usr/share/man/man8/ssh-keysign.8

# remove files from TRIBsvc-net-ssh
rm -f etc/ssh/sshd_config
rm -f usr/lib/ssh/sftp-server
rm -f usr/sbin/sshd
rm -f usr/share/man/man8/sftp-server.8
rm -f usr/share/man/man8/sshd.8
rm -f usr/share/man/man5/sshd_config.5
rm -fr var

cp ${BUILDROOT}/patches/ssh-askpass-zenity usr/lib/ssh/ssh-askpass
chmod 555 usr/lib/ssh/ssh-askpass
mkdir -p usr/share/pixmaps
cp ${BUILDROOT}/patches/ssh-askpass-zenity.png usr/share/pixmaps
chmod 444 usr/share/pixmaps/ssh-askpass-zenity.png
