#!/bin/sh
#
# The original solaris had ssh split into 3 packages
# We replicate the split here
#

# remove files from TRIBnet-ssh-ssh-key
rm -f usr/bin/ssh-keygen
rm -f usr/bin/ssh-keyscan
rm -f usr/lib/ssh/ssh-keysign
rm -f usr/share/man/man1/ssh-keygen.1
rm -f usr/share/man/man1/ssh-keyscan.1
rm -f usr/share/man/man8/ssh-keysign.8

# remove files from TRIBsvc-net-ssh
rm -f etc/ssh/sshd_config
rm -f usr/lib/ssh/sftp-server
rm -f usr/sbin/sshd
rm -f usr/share/man/man8/sftp-server.8
rm -f usr/share/man/man8/sshd.8
rm -f usr/share/man/man5/sshd_config.5
rm -fr var

cp ${BUILDROOT}/patches/ssh-askpass-zenity usr/lib/ssh/ssh-askpass
chmod 555 usr/lib/ssh/ssh-askpass
mkdir -p usr/share/pixmaps
cp ${BUILDROOT}/patches/ssh-askpass-zenity.png usr/share/pixmaps
chmod 444 usr/share/pixmaps/ssh-askpass-zenity.png

#
# temporary fix for compatibility with older clients that just have dsa keys
#
cat >> etc/ssh/ssh_config <<EOF
PubkeyAcceptedKeyTypes +ssh-dss
EOF
