#!/bin/sh
#
# put in the regular path
#
PYVERS=3.8
mkdir -p usr/bin
cd usr/bin
chmod a+x ../../usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/checkdmarc.py
ln -s ../../usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/checkdmarc.py checkdmarc
