#!/bin/sh
#
# put python in the right place
#
mkdir -p usr/versions/python-3.11/lib/python3.11
mv usr/lib/python3.11/site-packages usr/versions/python-3.11/lib/python3.11
rmdir usr/lib/python3.11
rmdir usr/lib
