#!/bin/sh
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
nawk '
{if ($3 ~ /^var\/log\/shibboleth/) { $6 = "shibd" ; $5 = "shibd" }}
{if ($3 ~ /^var\/run\/shibboleth/) { $6 = "shibd" ; $5 = "shibd" }}
{if ($3 ~ /^var\/cache\/shibboleth/) { $6 = "shibd" ; $5 = "shibd" }}
{print}
'
