#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# need to put the manifest under var for sparse-root zone support
#
mkdir -p var/svc/manifest/network
cp ${BUILDROOT}/patches/haproxy2.xml var/svc/manifest/network
cp ${BUILDROOT}/patches/svc-haproxy opt/tribblix/haproxy/sbin
chmod 755 opt/tribblix/haproxy/sbin/svc-haproxy
#
mkdir -p etc/security/auth_attr.d
cp ${BUILDROOT}/patches/haproxy-auth_attr etc/security/auth_attr.d/haproxy2
mkdir -p etc/security/prof_attr.d
cp ${BUILDROOT}/patches/haproxy-prof_attr etc/security/prof_attr.d/haproxy2
#
# we don't ship a configuration (which would go in /etc/haproxy.cfg)
# but this is where the pid file is expected to end up
#
mkdir -p var/haproxy
