#!/bin/sh
#
# put in the regular path
#
VERSION=3.2
mkdir usr/bin
cd usr/bin
ln -s ../versions/cmake-${VERSION}/bin/c* .
cd ../versions/cmake-${VERSION}/bin
strip c*
cd ../share/cmake-3.2/Help/generator
for file in *
do
    nfile=`echo $file | sed 's: :_:g'`
    mv "$file" $nfile
done
