#!/bin/sh
#
# was originally 1.5.0 but now everything is updated we can just ship 1.5.4
#
mkdir -p usr/share/jfreechart-1.5.4
cp ${THOME}/tarballs/jfreechart-1.5.4.jar usr/share/jfreechart-1.5.4

cd usr/share/jfreechart-1.5.4
wget https://www.gnu.org/licenses/lgpl-3.0-standalone.html
