#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
mkdir -p usr/share/jfreechart-1.5.6
cp ${THOME}/tarballs/jfreechart-1.5.6.jar usr/share/jfreechart-1.5.6

cd usr/share/jfreechart-1.5.6
wget https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
