#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
mkdir -p usr/share/jfreechart-1.5.5
cp ${THOME}/tarballs/jfreechart-1.5.5.jar usr/share/jfreechart-1.5.5

cd usr/share/jfreechart-1.5.5
wget https://www.gnu.org/licenses/lgpl-3.0-standalone.html
