#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#

#
# the node build should populate ../node-vxxx-32
# we should be the 64-bit build
#
NPWD=`/bin/pwd`
NVER=`basename $NPWD`
if [ -d ../${NVER}-32 ]; then
    mkdir -p ${DESTDIR}/usr/versions/node-v4/bin/i86
    mkdir -p ${DESTDIR}/usr/versions/node-v4/bin/amd64
    mv ${DESTDIR}/usr/versions/node-v4/bin/node ${DESTDIR}/usr/versions/node-v4/bin/amd64
    cp ../${NVER}-32/out/Release/node ${DESTDIR}/usr/versions/node-v4/bin/i86
fi
