#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# traditionally the file name was just libz.so.1 rather than .1.x.y
#
rm lib/libz.so.1
mv lib/libz.so.1.* lib/libz.so.1
cd lib
rm libz.so
ln -s libz.so.1 libz.so
cd ..
rm lib/${ARCH64}/libz.so.1
mv lib/${ARCH64}/libz.so.1.* lib/${ARCH64}/libz.so.1
cd lib/${ARCH64}
rm libz.so
ln -s libz.so.1 libz.so
cd ../..
#
# the installation and build correctly puts the libs in /lib instead of
# /usr/lib so they are in the root archive because wget will need them if
# we are net booting, add symlinks into /usr
#
mkdir -p usr/lib/${ARCH64}
cd usr/lib
ln -s ../../lib/libz.so* .
cd ${ARCH64}
ln -s ../../../lib/${ARCH64}/libz.so* .
