#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fixes up prototype files, by setting the correct permissions
# for existing directories
#
awk '
{if ($3 ~ /^var\/forgejo/) { $6 = "forgejo" ; $5 = "forgejo" }}
{print}
'
