#!/bin/sh
#
# aside from being large, these are filenames with spaces
#
rm -fr usr/versions/python-3.11/lib/python3.11/site-packages/ansible_collections/cisco/intersight/misc
rm -fr usr/versions/python-3.11/lib/python3.11/site-packages/ansible_collections/cisco/ucs/misc
