#!/bin/sh
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# for binary compatibility, ship older libs
# and related files
#
# the main TRIBimage-libpng package ships libpng14 in compatibility mode
#
mkdir -p usr/lib/${ARCH64}
cp -a /usr/lib/libpng.so.2* usr/lib
cp -a /usr/lib/${ARCH64}/libpng.so.2* usr/lib/${ARCH64}
cp -a /usr/lib/libpng.so.3* usr/lib
cp -a /usr/lib/${ARCH64}/libpng.so.3* usr/lib/${ARCH64}
cp -a /usr/lib/libpng10.so* usr/lib
cp -a /usr/lib/${ARCH64}/libpng10.so* usr/lib/${ARCH64}
cp -a /usr/lib/libpng12.so* usr/lib
cp -a /usr/lib/${ARCH64}/libpng12.so* usr/lib/${ARCH64}
mkdir -p usr/lib/pkgconfig
mkdir -p usr/lib/${ARCH64}/pkgconfig
cp -p /usr/lib/pkgconfig/libpng10.pc usr/lib/pkgconfig
cp -p /usr/lib/${ARCH64}/pkgconfig/libpng10.pc usr/lib/${ARCH64}/pkgconfig
cp -p /usr/lib/pkgconfig/libpng12.pc usr/lib/pkgconfig
cp -p /usr/lib/${ARCH64}/pkgconfig/libpng12.pc usr/lib/${ARCH64}/pkgconfig
mkdir -p usr/bin/${ARCH64}
cp -p /usr/bin/libpng10-config usr/bin
cp -p /usr/bin/${ARCH64}/libpng10-config usr/bin/${ARCH64}
cp -p /usr/bin/libpng12-config usr/bin
cp -p /usr/bin/${ARCH64}/libpng12-config usr/bin/${ARCH64}
mkdir -p usr/include
cp -pr /usr/include/libpng10 usr/include
cp -pr /usr/include/libpng12 usr/include
