#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# remove localized man pages
#
rm -fr usr/share/man/*/man1
rmdir usr/share/man/*
#
# this package also owns /bin/vi, which I point at the
# traditional (but xpg6) vi
#
cd usr/bin
ln -s ../xpg6/bin/edit vi
cd ../..
#
# icons and desktop integration are shipped by the gtk2 version
# of the package
#
rm -fr usr/share/icons
rm -fr usr/share/applications
