#!/bin/sh
#
# remove localized man pages
#
rm -fr usr/share/man/*/man1
rmdir usr/share/man/*
#
# this package also owns /bin/vi, which I point at the
# traditional (but xpg6) vi
#
cd usr/bin
ln -s ../xpg6/bin/edit vi
