#!/bin/sh
#
mkdir -p usr/bin
mkdir -p usr/lib/pkgconfig
cd usr/bin
ln -s ../versions/python-3.3.2/bin/python3 .
ln -s ../versions/python-3.3.2/bin/python3-config .
ln -s ../versions/python-3.3.2/bin/pydoc3 .
ln -s ../versions/python-3.3.2/bin/pyvenv .
ln -s ../versions/python-3.3.2/bin/idle3 .
cd ../lib
ln -s ../versions/python-3.3.2/lib/libpython3* .
cd pkgconfig
ln -s ../../versions/python-3.3.2/lib/pkgconfig/python-3.3.pc .
ln -s ../../versions/python-3.3.2/lib/pkgconfig/python3.pc .
