#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# this recreates the contents of the package
#
mkdir -p usr/share
cd usr/share
${THOME}/build/unpack apache-xmlrpc-3.1.3-bin
rm -fr apache-xmlrpc-3.1.3/docs
mv apache-xmlrpc-3.1.3/lib/* apache-xmlrpc-3.1.3
rmdir apache-xmlrpc-3.1.3/lib
