#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# as of v6, the main prog doesn't need to be setuid, but the auth helper does
#
chmod 4511 usr/libexec/xscreensaver/xscreensaver-auth

#
# fireworkx keeps on dumping core
#
rm -f usr/libexec/xscreensaver/fireworkx
rm -f usr/share/man/man6/fireworkx.6
rm -f usr/share/xscreensaver/config/fireworkx.xml

#
# mapscroller requires perl modules that we either don't install by
# default, or ship at all
#
rm -f usr/libexec/xscreensaver/mapscroller
rm -f usr/libexec/xscreensaver/mapscroller.pl
rm -f usr/share/man/man6/mapscroller.6
rm -f usr/share/xscreensaver/config/mapscroller.xml

#
# we don't ship the command, nor should we
#
rm -f usr/share/man/man1/xscreensaver-systemd.1
rm -f usr/share/man/man6/xscreensaver-systemd.6
rm -f usr/share/xscreensaver/xscreensaver.service
