#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# these not only look wrong, they conflict with other packages
#
PYVERS=3.12
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/test
rm -fr usr/versions/python-${PYVERS}/lib/python${PYVERS}/site-packages/tools
