#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# 64-bit binaries by default
#
mv usr/bin/${ARCH64}/* usr/bin
rmdir usr/bin/${ARCH64}
