#!/bin/sh
#
${BUILDROOT}/unpack clojure-tools-1.9.0.297
#
# that ended up in clojure-tools, so move it
#
mkdir -p usr/versions/clojure-190/lib/libexec
mkdir -p usr/versions/clojure-190/bin
sed -i -e 's@PREFIX@/usr/versions/clojure-190/lib@g' clojure-tools/clojure
mv clojure-tools/clojure usr/versions/clojure-190/bin
#
# skip clj, as it requires rlwrap
#
#mv clojure-tools/clj usr/versions/clojure-190/bin
mv clojure-tools/clojure-tools-1.9.0.297.jar usr/versions/clojure-190/lib/libexec
mv clojure-tools/deps.edn clojure-tools/example-deps.edn usr/versions/clojure-190/lib
rm -rf clojure-tools
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/clojure-190/bin/clojure .
