#!/bin/sh
#
# move the python stuff to the right place
#
mkdir -p usr/versions/python-3.9/lib/python3.9
mv usr/lib/python3.9/site-packages usr/versions/python-3.9/lib/python3.9
rmdir usr/lib/python3.9
rm -fr usr/share/doc
rm -f usr/lib/lib*.la
rm -f usr/lib/*/lib*.la
