#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# some files have "odd" names incompatible with SVR4 packaging
#
mv usr/share/samba/setup/cn=samba.ldif usr/share/samba/setup/cn-samba.ldif
#
# this is a Solaris base command
#
mv usr/bin/profiles usr/bin/smbprofiles
mv usr/share/man/man1/profiles.1 usr/share/man/man1/smbprofiles.1
#
# and this conflicts with our smbd manual
#
mv usr/share/man/man8/smbd.8 usr/share/man/man8/samba-smbd.8
#
# this is where our perl really lives
#
if [ -d usr/share/perl5 ]; then
    mkdir -p usr/perl5/5.34/lib
    mv usr/share/perl5/* usr/perl5/5.34/lib
    rmdir usr/share/perl5
fi
