#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
    i386)
	mkdir -p usr/lib/brand/bhyve
	mkdir -p usr/share/man/man7
	cd usr/lib/brand/bhyve
	cp -p ${BUILDROOT}/patches/bhyve/* .
	mv bhyve.7 ../../../share/man/man7
	;;
esac
