#!/bin/sh
#
VERSION=3.6.2
#
# default
#
mkdir -p usr/bin
ln -s ../versions/apache-maven-${VERSION}/bin/mvn usr/bin/mvn
#
# no need for windows batch files
#
rm -f usr/versions/apache-maven-${VERSION}/bin/mvn.cmd
rm -f usr/versions/apache-maven-${VERSION}/bin/mvnDebug.cmd
#
# jansi native doesn't supply any platforms that we can use
#
rm -fr usr/versions/apache-maven-${VERSION}/lib/jansi-native
#
# mvn is bash, not sh
#
gsed -i s:/bin/sh:/usr/bin/bash: usr/versions/apache-maven-${VERSION}/bin/mvn
