#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  OBJDIR32=SunOS5.11_gcc_OPT.OBJ
  OBJDIR64=SunOS5.11_gcc_64_OPT.OBJ
  ;;
i386)
  ARCH64="amd64"
  NSARCH=`uname -m`
  OBJDIR32=SunOS5.11_${NSARCH}_gcc_OPT.OBJ
  OBJDIR64=SunOS5.11_${NSARCH}_gcc_64_OPT.OBJ
  ;;
esac

if [ ! -d "${DESTDIR}" ]; then
   mkdir -p ${DESTDIR}
fi

#
# local package tweaks below
#

#
# the assumption here is that 'make install' just fell flat on its face
# so we just copy the files we need
#
# also assume we're in the nss directory that the build ran from
#
# the commented out symlinks are shipped in the nspr package, which this
# package depends on
#
mkdir -p ${DESTDIR}/usr/lib/mps/${ARCH64}
#ln -s ${ARCH64} ${DESTDIR}/usr/lib/mps/64
mkdir -p ${DESTDIR}/usr/lib/mps/secv1/${ARCH64}
#ln -s ${ARCH64} ${DESTDIR}/usr/lib/mps/secv1/64
mkdir -p ${DESTDIR}/usr/include/mps
mkdir -p ${DESTDIR}/usr/lib/pkgconfig
mkdir -p ${DESTDIR}/usr/lib/${ARCH64}/pkgconfig

for file in libfreebl3.so libnss3.so libnssckbi.so libnssdbm3.so libnssutil3.so libsmime3.so libsoftokn3.so libssl3.so libfreebl3.chk libnssdbm3.chk libsoftokn3.chk
do
    cp ../dist/${OBJDIR32}/lib/$file ${DESTDIR}/usr/lib/mps
    ln -s ../$file ${DESTDIR}/usr/lib/mps/secv1
    cp ../dist/${OBJDIR64}/lib/$file ${DESTDIR}/usr/lib/mps/${ARCH64}
    ln -s ../../${ARCH64}/$file ${DESTDIR}/usr/lib/mps/secv1/${ARCH64}
done

#
# libfreebl is done differently on sparc
#
for file in libfreebl_32fpu_3.so libfreebl_32int64_3.so libfreebl_32fpu_3.chk libfreebl_32int64_3.chk
do
    cp ../dist/${OBJDIR32}/lib/$file ${DESTDIR}/usr/lib/mps
    ln -s ../$file ${DESTDIR}/usr/lib/mps/secv1
done
for file in libfreebl_64fpu_3.so libfreebl_64int_3.so libfreebl_64fpu_3.chk libfreebl_64int_3.chk
do
    cp ../dist/${OBJDIR64}/lib/$file ${DESTDIR}/usr/lib/mps/${ARCH64}
    ln -s ../../${ARCH64}/$file ${DESTDIR}/usr/lib/mps/secv1/${ARCH64}
done

#
# utilities - limited to certutil at this point
#
mkdir -p ${DESTDIR}/usr/bin/${ARCH64}
mkdir -p ${DESTDIR}/usr/share/man/man1
for file in certutil
do
    cp ../dist/${OBJDIR32}/bin/$file ${DESTDIR}/usr/bin
    elfedit -e "dyn:runpath /usr/lib/mps" ${DESTDIR}/usr/bin/$file
    cp ../dist/${OBJDIR64}/bin/$file ${DESTDIR}/usr/bin/${ARCH64}
    elfedit -e "dyn:runpath /usr/lib/mps/${ARCH64}" ${DESTDIR}/usr/bin/${ARCH64}/$file
    cp doc/nroff/${file}.1 ${DESTDIR}/usr/share/man/man1
done

cd ../dist/public/nss
tar cf - . | (cd ${DESTDIR}/usr/include/mps ; tar xf -)

cat >> ${DESTDIR}/usr/lib/pkgconfig/nss.pc <<EOF
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/mps
includedir=/usr/include/mps

Name: NSS
Description: Network Security Services
Version: 3.116
Requires: nspr >= 4.37
Libs: -L/usr/lib/mps -R/usr/lib/mps -lnss3 -lsmime3 -lssl3 -lnssutil3
Cflags: -I/usr/include/mps
EOF

cat >> ${DESTDIR}/usr/lib/${ARCH64}/pkgconfig/nss.pc <<EOF
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/mps/${ARCH64}
includedir=/usr/include/mps

Name: NSS
Description: Network Security Services
Version: 3.116
Requires: nspr >= 4.37
Libs: -L/usr/lib/mps/${ARCH64} -R/usr/lib/mps/${ARCH64} -lnss3 -lsmime3 -lssl3 -lnssutil3
Cflags: -I/usr/include/mps
EOF
