#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# don't need build artefacts
#
rm -f usr/lib/evince/3/backends/lib*.a
rm -f usr/lib/evince/3/backends/lib*.la
rm -f usr/lib/evince/4/backends/lib*.a
rm -f usr/lib/evince/4/backends/lib*.la
rm -f usr/lib/*/evince/4/backends/lib*.a
rm -f usr/lib/*/evince/4/backends/lib*.la
