#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
# the install doesn't understand DESTDIR, so will fail
# but we need to have run make install as it creates
# the .ad file
#
mkdir -p ${DESTDIR}/usr/share/man/man1
cp xshisen.man ${DESTDIR}/usr/share/man/man1/xshisen.1
mkdir -p ${DESTDIR}/usr/share/xshisen
cp pixmaps/*.xpm ${DESTDIR}/usr/share/xshisen
mkdir -p ${DESTDIR}/usr/bin
cp xshisen ${DESTDIR}/usr/bin
mkdir -p ${DESTDIR}/usr/lib/X11/app-defaults
cp XShisen.ad ${DESTDIR}/usr/lib/X11/app-defaults/XShisen
