#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# don't ship anything to do with cmake
#
rm -fr usr/lib/cmake
rm -fr usr/lib/${ARCH64}/cmake
#
# remove docs (gtk-doc is done automatically)
#
rm -fr usr/share/doc
