#!/bin/sh
#
# cleanup to save space
#
INSTDIR="opt/tribblix/mysql"
rm -fr ${INSTDIR}/mysql-test
rm -fr ${INSTDIR}/sql-bench
rm ${INSTDIR}/lib/*.a
#
# this is a real hack
#
gsed -i 's/-lsocket -lnsl/-lsocket -lstdc++ -lnsl/' ${INSTDIR}/bin/mysql_config
