#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# remove docs (gtk-doc is done automatically)
#
rm -fr usr/share/doc
#
# put python in the right place
#
if [ -d usr/lib/python3.12 ]; then
    rm -f usr/lib/python3.12/site-packages/libxsltmod.la
    mkdir -p usr/versions/python-3.12/lib
    mv usr/lib/python3.12 usr/versions/python-3.12/lib
fi
