#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# remove docs (gtk-doc is done automatically)
#
rm -fr usr/share/doc
#
# put python in the right place
#
if [ -d usr/lib/python3.13 ]; then
    rm -f usr/lib/python3.13/site-packages/libxsltmod.la
    mkdir -p usr/versions/python-3.13/lib
    mv usr/lib/python3.13 usr/versions/python-3.13/lib
fi
