#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#

#
# the Makefile assumes the SunOS install,
# but doesn't make the directories first
#
mkdir -p ${DESTDIR}/usr/bin
mkdir -p ${DESTDIR}/usr/share/man/man1
mkdir -p ${DESTDIR}/usr/share/man/man4
mkdir -p ${DESTDIR}/usr/lib/X11/app-defaults
