#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# this package is now common to x86 and sparc
#

#
# xkeystone needs things we don't have
#
rm -f usr/bin/xkeystone

#
# xmakemap is just a script, so install it here
#
mkdir -p usr/bin
mkdir -p usr/share/man/man1
cp ${BUILDROOT}/patches/xmakemap/xmakemap usr/bin
chmod 0555 usr/bin/xmakemap
cp ${BUILDROOT}/patches/xmakemap/xmakemap.man usr/share/man/man1/xmakemap.1
chmod 0444 usr/share/man/man1/xmakemap.1
