#!/bin/sh
#
# just name off the primary version
#
VERSION=2.8.11

UVER=r2396
mv usr/versions/ganttproject-${VERSION}-${UVER} usr/versions/ganttproject-${VERSION}

mkdir -p usr/bin
rm -f usr/versions/ganttproject-${VERSION}/ganttproject.bat
rm -f usr/versions/ganttproject-${VERSION}/ganttproject.exe
cd usr/bin
ln -s ../../usr/versions/ganttproject-${VERSION}/ganttproject .
