#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   mkdir -p ${DESTDIR}
fi

#
# local package tweaks below
#

#
# the assumption here is that 'make install' just fell flat on its face
# so we just copy the files we need
#
# also assume we're in the nss directory that the build ran from
#
mkdir -p ${DESTDIR}/usr/lib/mps/amd64
ln -s amd64 ${DESTDIR}/usr/lib/mps/64
mkdir -p ${DESTDIR}/usr/lib/mps/secv1/amd64
ln -s amd64 ${DESTDIR}/usr/lib/mps/secv1/64
mkdir -p ${DESTDIR}/usr/include/mps
mkdir -p ${DESTDIR}/usr/lib/pkgconfig

NSARCH=`uname -m`
OBJDIR32=SunOS5.11_${NSARCH}_gcc_OPT.OBJ
OBJDIR64=SunOS5.11_${NSARCH}_gcc_64_OPT.OBJ

for file in libnspr4.so libplc4.so libplds4.so
do
    cp ../dist/${OBJDIR32}/lib/$file ${DESTDIR}/usr/lib/mps
    ln -s ../$file ${DESTDIR}/usr/lib/mps/secv1
    cp ../dist/${OBJDIR64}/lib/$file ${DESTDIR}/usr/lib/mps/amd64
    ln -s ../../amd64/$file ${DESTDIR}/usr/lib/mps/secv1/amd64
done

cd ../dist/${OBJDIR32}/include
tar cf - . | (cd ${DESTDIR}/usr/include/mps ; tar xf -)

cat >> ${DESTDIR}/usr/lib/pkgconfig/nspr.pc <<EOF
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/mps
includedir=/usr/include/mps

Name: NSPR
Description: The Netscape Portable Runtime
Version: 4.10.10
Libs: -L/usr/lib/mps -R/usr/lib/mps -lplds4 -lplc4 -lnspr4
Cflags: -I/usr/include/mps
EOF
