#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# make sure you get the tarball created by the project, not the
# github autogenerated one
#
$THOME/build/unpack rclone-v1.71.2
cd rclone-v1.71.2
env PATH=/usr/gnu/bin:/usr/versions/go-1.25/bin:$PATH gmake

rm -fr /tmp/cs
mkdir -p /tmp/cs/usr/bin
mkdir -p /tmp/cs/usr/share/rclone
mkdir -p /tmp/cs/usr/share/man/man1
cp ./rclone /tmp/cs/usr/bin
cp ./README.md ./COPYING /tmp/cs/usr/share/rclone
cp ./rclone.1 /tmp/cs/usr/share/man/man1
${THOME}/build/create_pkg TRIBrclone /tmp/cs
rm -fr /tmp/cs
cd ..
