#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we don't ship .la files
#
/usr/bin/rm -f `/usr/bin/find usr/lib -name '*.la'`
#
# compat symlinks provided automatically by use of the
# --enable-replace flag to ./configure
#
