#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we cheat here; there are post scripts for real-time, and a startup
# script for first boot
#
mkdir -p etc/rc2.d
cd etc/rc2.d
cat > S99gsettings << _EOF
#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
if [ -x /usr/bin/glib-compile-schemas ]; then
  /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
fi
_EOF
chmod a+x S99gsettings
