#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we don't have systemtap
#
rm -fr usr/versions/node-v${VERSION}/share/systemtap
#
# Only the currently supported LTS release has standard symlinks
#
VERSION=24
exit 0
mkdir -p usr/bin
ln -s ../versions/node-v${VERSION}/bin/node usr/bin/node
ln -s ../versions/node-v${VERSION}/bin/npm usr/bin/npm
ln -s ../versions/node-v${VERSION}/bin/npx usr/bin/npx
ln -s ../versions/node-v${VERSION}/bin/corepack usr/bin/corepack
