#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# the french documentation is bigger than the product itself
#
rm -fr usr/share/doc/grisbi/fr
#
# german isn't much better
#
rm -fr usr/share/doc/grisbi/de
#
# the english documentation is a duplicate of C
#
rm -fr usr/share/doc/grisbi/en
ln -s C usr/share/doc/grisbi/en
