#!/bin/sh
#
VERSION=29
rm -fr usr/versions/emacs-${VERSION}/lib/*/systemd
rm -f usr/versions/emacs-${VERSION}/share/emacs/*/etc/emacs.service
mkdir -p usr/bin
ln -s ../versions/emacs-${VERSION}/bin/emacs usr/bin/emacs
ln -s ../versions/emacs-${VERSION}/bin/emacsclient usr/bin/emacsclient
ln -s ../versions/emacs-${VERSION}/bin/etags usr/bin/etags
mkdir -p usr/share/man/man1
gunzip usr/versions/emacs-${VERSION}/share/man/man1/*.gz
mv usr/versions/emacs-${VERSION}/share/man/man1/emacs* usr/share/man/man1
mv usr/versions/emacs-${VERSION}/share/man/man1/etags* usr/share/man/man1
