#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# move any perl manpages that end up in the wrong place
#
mv usr/man/man3 usr/share/man
rmdir usr/man
#
# put perl files in the right place
#
mkdir -p usr/perl5
mv usr/lib/site_perl usr/perl5
mv usr/perl5/site_perl/$(${THOME}/build/getperlver).0 usr/perl5/site_perl/$(${THOME}/build/getperlver)
mv usr/perl5/site_perl/C* usr/perl5/site_perl/$(${THOME}/build/getperlver)
rm -fr usr/lib/*-solaris-thread-multi-64

rm -f usr/lib/*/collectd/*.la
