#!/bin/sh
#
# move any perl manpages that end up in the wrong place
#
mv usr/man/man3 usr/share/man
rmdir usr/man
#
# put perl files in the right place
#
mkdir -p usr/perl5
mv usr/lib/site_perl usr/perl5
mv usr/perl5/site_perl/5.34.0 usr/perl5/site_perl/5.34
mv usr/perl5/site_perl/C* usr/perl5/site_perl/5.34
rm -fr usr/lib/*-solaris-thread-multi-64

rm -f usr/lib/*/lib*.la
rm -f usr/lib/*/collectd/*.la
