#!/sbin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# don't rely on the owner being in the password file
# (will fail if installing to an alternate root)
#
/usr/bin/chown -hR 112:112 ${BASEDIR}/var/zabbix_proxy
