#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
        DESTDIR=$1
        ;;
*)
        exit 0
        ;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ARCH="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ARCH="x86_64"
  ;;
esac

#
# copy the built library
#
mkdir -p ${DESTDIR}/usr/lib/${ARCH64}
cp target/classes/org/sqlite/native/SunOS/${ARCH}/libsqlitejdbc.so ${DESTDIR}/usr/lib/${ARCH64}
