#!/bin/sh
#
# we never shipped .la files before, no need to do so now
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
rm usr/lib/libexpat.la
rm usr/lib/${ARCH64}/libexpat.la
#
# we don't need a 64-bit xmlwf
#
rm usr/bin/${ARCH64}/xmlwf
rmdir usr/bin/${ARCH64}
#
# the changelog isn't necessary
#
rm -fr usr/share/doc
