#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
if [ ! -f ${DESTDIR}/usr/share/man/man1/xmlwf.1 ]; then
    mkdir -p ${DESTDIR}/usr/share/man/man1
    cp doc/xmlwf.1 ${DESTDIR}/usr/share/man/man1/xmlwf.1
fi
