#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# we never shipped .la files before, no need to do so now
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
rm usr/lib/libexpat.la
rm usr/lib/${ARCH64}/libexpat.la
#
# default to 64-bit xmlwf
#
if [ -f usr/bin/${ARCH64}/xmlwf ]; then
    rm -f usr/bin/xmlwf
    mv usr/bin/${ARCH64}/xmlwf usr/bin/xmlwf
    rmdir usr/bin/${ARCH64}
fi
#
# the changelog isn't necessary
#
rm -fr usr/share/doc
