#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#
VERSION=0.15.0

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#

#
# there is no make install, simply copy the file
#
mkdir -p ${DESTDIR}/opt/tribblix/prometheus/sbin
cp haproxy_exporter-${VERSION}/haproxy_exporter-${VERSION} ${DESTDIR}/opt/tribblix/prometheus/sbin/haproxy_exporter
