#!/bin/sh
#
# pkgproto generates garbage when fed hard links, so a symlink is just as good
#
VERSION=0.10.42
mkdir -p usr/bin
ln -s ../versions/node-v${VERSION}/bin/node usr/bin/node-010
ln -s ../versions/node-v${VERSION}/bin/npm usr/bin/npm-010
