#!/bin/sh
#
# this is where our python really lives
#
if [ -d usr/lib/python2.7/site-packages ]; then
    mkdir -p usr/versions/python-2.7/lib/python2.7
    mv usr/lib/python2.7/site-packages usr/versions/python-2.7/lib/python2.7
    rmdir usr/lib/python2.7
fi
if [ -d usr/lib/python3.7/site-packages ]; then
    mkdir -p usr/versions/python-3.7/lib/python3.7
    mv usr/lib/python3.7/site-packages usr/versions/python-3.7/lib/python3.7
    rmdir usr/lib/python3.7
fi
