#!/bin/sh
#
# pkgproto generates garbage when fed hard links, so a symlink is just as good
#
VERSION=1.7.26
mkdir -p usr/bin
ln -s ../../usr/versions/jruby-${VERSION}/bin/jruby usr/bin/
ln -s ../../usr/versions/jruby-${VERSION}/bin/jrubyc usr/bin/
ln -s ../../usr/versions/jruby-${VERSION}/bin/jgem usr/bin/
ln -s ../../usr/versions/jruby-${VERSION}/bin/jirb usr/bin/
cd usr/versions/jruby-${VERSION}
rm bin/*.bat
rm bin/jruby.sh bin/jruby.bash
rm bin/*.exe
rm bin/*.dll
rm -fr lib/ruby/shared/ffi/platform/*linux
rm -fr lib/ruby/shared/ffi/platform/*darwin
rm -fr lib/ruby/shared/ffi/platform/*windows
rm -fr lib/ruby/shared/ffi/platform/*bsd
rm -fr lib/ruby/shared/ffi/platform/*aix
rm -fr lib/ruby/shared/ffi/platform/i486-gnu
rm -fr lib/jni/*Windows
rm -fr lib/jni/*Linux
rm -fr lib/jni/*BSD
rm -fr lib/jni/*AIX
rm -fr lib/jni/Darwin
#
# We need to fix the jruby script as the Solaris/illumos
# basename in /usr/bin is utter bilge. Either the xpg4 or
# the gnu version is fine, both are in the base overlay.
#
gsed -i 's:basename:/usr/xpg4/bin/basename:g' bin/jruby
