#!/bin/sh
#
# pkgproto generates garbage when fed hard links, so a symlink is just as good
#
VERSION=1.7.13
mkdir -p usr/bin
ln -s ../versions/jruby-${VERSION}/bin/jruby usr/bin/
ln -s ../versions/jruby-${VERSION}/bin/jrubyc usr/bin/
ln -s ../versions/jruby-${VERSION}/bin/jgem usr/bin/
cd usr/versions/jruby-${VERSION}
rm bin/*.bat
rm bin/*.exe
rm bin/*.dll
rm -fr lib/ruby/shared/ffi/platform/*linux
rm -fr lib/ruby/shared/ffi/platform/*darwin
rm -fr lib/ruby/shared/ffi/platform/*windows
rm -fr lib/ruby/shared/ffi/platform/*bsd
rm -fr lib/ruby/shared/ffi/platform/*aix
rm -fr lib/ruby/shared/ffi/platform/i486-gnu
rm -fr lib/native/*Windows
rm -fr lib/native/*Linux
rm -fr lib/native/*BSD
rm -fr lib/native/*AIX
rm -fr lib/native/Darwin
