#!/bin/sh
#

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# prefer 64-bit
#
for file in usr/bin/${ARCH64}/*
do
    mv $file usr/bin
done
rmdir usr/bin/${ARCH64}
