#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# only ship the 64-bit binaries
# the cmake config files require the binaries to be present in the 64-bit
# locations, though, so add hard links
#
if [ -d usr/bin/${ARCH64} ]; then
    cd usr/bin/${ARCH64}
    mv * ..
    ln ../opj* .
    cd ..
    cd ../..
fi
