#!/bin/sh
#
# fix script run in the install context
# assumes you're in the directory containing the built software
# the argument is DESTDIR
#

case $# in
1)
	DESTDIR=$1
	;;
*)
	exit 0
	;;
esac

if [ ! -d "${DESTDIR}" ]; then
   exit 0
fi

#
# local package tweaks below
#
mkdir -p ${DESTDIR}/opt/tribblix/pound/man/man8
cp poundctl.8 pound.8 ${DESTDIR}/opt/tribblix/pound/man/man8
chmod 444 ${DESTDIR}/opt/tribblix/pound/man/man8/*
cp FAQ README ${DESTDIR}/opt/tribblix/pound
cp GPL.txt ${DESTDIR}/opt/tribblix/pound/LICENSE
chmod 444 ${DESTDIR}/opt/tribblix/pound/FAQ
chmod 444 ${DESTDIR}/opt/tribblix/pound/README
chmod 444 ${DESTDIR}/opt/tribblix/pound/LICENSE
