#!/bin/sh
#
# add nc as a symlink
#
cd usr/bin
ln -s ncat nc
cd ../..
#
# this is where our python really lives
#
mkdir -p usr/versions/python-2.7/lib/python2.7/site-packages
mv usr/lib/python2.7/site-packages/* usr/versions/python-2.7/lib/python2.7/site-packages
rmdir usr/lib/python2.7/site-packages
rmdir usr/lib/python2.7
rmdir usr/lib
#
# and we don't want to ship uninstall_ndiff
#
rm usr/bin/uninstall_ndiff
#
# or the localised man pages
#
rm -fr usr/share/man/??
rm -fr usr/share/man/??_??
