#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac
#
# for binary compatibility, ship the 0.9.8 libs
#
mkdir -p lib/${ARCH64}
cp -p /lib/libcrypto.so.0.9.8 lib
cp -p /lib/libssl.so.0.9.8 lib
cp -p /lib/${ARCH64}/libcrypto.so.0.9.8 lib/${ARCH64}
cp -p /lib/${ARCH64}/libssl.so.0.9.8 lib/${ARCH64}
#
# the files live under /lib, symlinks under usr/lib
#
mkdir -p usr/lib/${ARCH64}
cd usr/lib
ln -s ../../lib/libssl.so* .
ln -s ../../lib/libcrypto.so* .
cd ${ARCH64}
ln -s ../../../lib/${ARCH64}/libssl.so* .
ln -s ../../../lib/${ARCH64}/libcrypto.so* .
