#!/bin/sh
#
# remove the qt gui which is shipped separately
# in the TRIBwireshark-qt package
#

#
# cannot package files with spaces in the name
#
mv "usr/share/wireshark/profiles/No Reassembly" "usr/share/wireshark/profiles/No_Reassembly"

#
# keep the gui separately to slim the dependency tree
#
rm -f usr/bin/wireshark
rm -f usr/share/applications/wireshark.desktop
