#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#

case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

cd usr/bin
ln -s tclsh8.6 tclsh
cd $ARCH64
ln -s tclsh8.6 tclsh
cd ..
cd ..
mv man/man1 share/man
mv man/man3 share/man
mv man/man3/* share/man/man3
mv man/mann/* share/man/mann
rmdir man/man3
rmdir man/mann
rmdir man
