#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# put in the regular path
#
VERSION=3.29
mkdir usr/bin
cd usr/bin
ln -s ../versions/cmake-${VERSION}/bin/c* .
cd ../versions/cmake-${VERSION}/bin
strip c*
cd ../share/cmake-${VERSION}/Help/generator
for file in *
do
    nfile=${file// /_}
    mv "$file" "$nfile"
done
