#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/haskell/bin/ghc .
ln -s ../../usr/versions/haskell/bin/ghc-pkg .
ln -s ../../usr/versions/haskell/bin/ghci .
ln -s ../../usr/versions/haskell/bin/haddock .
ln -s ../../usr/versions/haskell/bin/hp2ps .
ln -s ../../usr/versions/haskell/bin/hpc .
ln -s ../../usr/versions/haskell/bin/hsc2hs .
ln -s ../../usr/versions/haskell/bin/runghc .
cd ../..

#
# it manages to link against ncurses, but we need to help it
# find the library at runtime
#
# rts is in the RPATH for the 3 binaries that matter: ghc, ghc-pkg, haddock
#
cd usr/versions/haskell/lib/ghc-9.4.7/rts
ln -s /usr/gnu/lib/amd64/libncurses.so.6 .
