#!/bin/sh
#
PYVERS=3.9
mkdir -p usr/bin
cd usr/bin
ln -s ../../usr/versions/python-${PYVERS}/bin/s3cmd .
cd ../..
mkdir -p usr/share/man/man1
mv usr/versions/python-${PYVERS}/share/man/man1/s3cmd.1 usr/share/man/man1
rmdir usr/versions/python-${PYVERS}/share/man/man1
rmdir usr/versions/python-${PYVERS}/share/man
