#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# use the proper project tarballs, not the github autogenerated ones
# disable lv-tool, to avoid pulling in SDL1
#
${THOME}/build/dobuild -64 libvisual-0.4.2 -C --disable-lv-tool
#
# this is a 2-stage build, you need to package the above and install it, then
# build the plugins against it to make the full package
#
env CONFIG_SHELL=/bin/bash ${THOME}/build/dobuild -64 libvisual-plugins-0.4.2 -C "--disable-gstreamer-plugin --disable-gdkpixbuf-plugin --disable-corona --disable-gforce --disable-alsa"

${THOME}/build/genpkg TRIBlibvisual libvisual-0.4.2 libvisual-plugins-0.4.2
