#!/bin/sh
#
# clean up the junk
# and add convenience links
#
VERSION=1.11
rm -fr usr/versions/go-${VERSION}/pkg/bootstrap
rm -fr usr/versions/go-${VERSION}/pkg/obj/go-build
rmdir usr/versions/go-${VERSION}/pkg/obj
rm -fr usr/versions/go-${VERSION}/test
rm -f usr/versions/go-${VERSION}/favicon.ico
rm -f usr/versions/go-${VERSION}/robots.txt
# no longer default
#mkdir -p usr/bin
#cd usr/bin
#ln -s ../versions/go-${VERSION}/bin/* .
