#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# clean up and move
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# as we're only shipping the library components, delete the bits we
# don't want to ship at all
# note that the manpages are originally installed under usr/ssl so get
# deleted here too
#
rm -fr usr/bin usr/include usr/ssl
rm -fr usr/lib/pkgconfig usr/lib/64/pkgconfig
#
# delete the compilation symlinks
#
rm -f usr/lib/lib*.so
rm -f usr/lib/lib*.a
rm -f usr/lib/64/lib*.so
rm -f usr/lib/64/lib*.a
#
# libraries expect to live in /lib
#
mv usr/lib/64 usr/lib/${ARCH64}
mkdir -p lib/${ARCH64}
mv usr/lib/lib*so* lib
mv usr/lib/${ARCH64}/lib*so* lib/${ARCH64}
#
# the files live under /lib, symlinks under usr/lib
#
cd usr/lib
ln -s ../../lib/libssl.so* .
ln -s ../../lib/libcrypto.so* .
cd ${ARCH64}
ln -s ../../../lib/${ARCH64}/libssl.so* .
ln -s ../../../lib/${ARCH64}/libcrypto.so* .
