#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
VERSION="2.7"

#
# we don't yet ship a 64-bit python, but some of the code here is what
# we might use if we did
#
case `uname -p` in
sparc)
  ARCH64="sparcv9"
  ;;
i386)
  ARCH64="amd64"
  ;;
esac

#
# first strip out the tests
#
TESTDIR=/tmp/ptest.$$
rm -fr $TESTDIR
mkdir -p $TESTDIR
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/sqlite3/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/sqlite3/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-tk/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/lib-tk/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib2to3/tests | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/lib2to3/tests
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/json/tests | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/json/tests
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/idlelib/idle_test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/idlelib/idle_test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/bsddb/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/bsddb/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/email/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/email/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/ctypes/test | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/ctypes/test
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/distutils/tests | ( cd $TESTDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/distutils/tests
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_ctypes_test.so | ( cd $TESTDIR ; tar xf -)
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_testcapi.so | ( cd $TESTDIR ; tar xf -)
rm -f usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_ctypes_test.so
rm -f usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_testcapi.so
#
# having copied them off, package them
#
$THOME/build/create_pkg TRIBv-python-27-tests $TESTDIR
rm -fr $TESTDIR

#
# next strip out the idle/tkinter components so base python doesn't
# drag in tk and x11
#
PTKDIR=/tmp/ptkidle.$$
mkdir -p $PTKDIR
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_tkinter.so | ( cd $PTKDIR ; tar xf -)
rm -f usr/versions/python-${VERSION}/lib/python${VERSION}/lib-dynload/_tkinter.so
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/lib-tk | ( cd $PTKDIR ; tar xf -)
tar cf - usr/versions/python-${VERSION}/lib/python${VERSION}/idlelib | ( cd $PTKDIR ; tar xf -)
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/lib-tk
rm -fr usr/versions/python-${VERSION}/lib/python${VERSION}/idlelib
tar cf - usr/versions/python-${VERSION}/bin/idle* | ( cd $PTKDIR ; tar xf -)
rm -f usr/versions/python-${VERSION}/bin/idle*
#
# having copied them off, package them
#
$THOME/build/create_pkg TRIBv-python-27-tkinter $PTKDIR
rm -fr $PTKDIR

mkdir -p usr/bin
mkdir -p usr/lib/pkgconfig
mkdir -p usr/share/man/man1
cd usr/share/man/man1
ln -s ../../../../usr/versions/python-${VERSION}/share/man/man1/python${VERSION}.1 .
ln -s ../../../../usr/versions/python-${VERSION}/share/man/man1/python2.1 .
cd ../../../..
cd usr/bin
ln -s ../../usr/versions/python-${VERSION}/bin/py* .
# remove the bare versions
rm -f python
rm -f python-config
#
cd ../lib
ln -s ../../usr/versions/python-${VERSION}/lib/libpython2.7.so* .
cd pkgconfig
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python-2.7.pc .
ln -s ../../versions/python-${VERSION}/lib/pkgconfig/python2.pc .
cd ..
