#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# place a wrapper in the normal path
#
mkdir -p usr/bin
cd usr/bin
cat > nikto <<EOF
#!/bin/sh
cd /usr/versions/nikto
exec /usr/bin/perl ./nikto.pl "\$@"
EOF
chmod a+x nikto
