#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# just name off the primary version
#
VERSION=10.1.50
cd usr/versions
ln -s apache-tomcat-${VERSION} tomcat10
chmod a+x apache-tomcat-${VERSION}/bin/*.sh
rm apache-tomcat-${VERSION}/bin/*.bat
