#!/bin/sh
#
# put in the regular path
#
VERSION=3.5
mkdir usr/bin
cd usr/bin
ln -s ../versions/cmake-${VERSION}/bin/c* .
cd ../versions/cmake-${VERSION}/bin
strip c*
cd ../share/cmake-${VERSION}/Help/generator
for file in *
do
    nfile=`echo $file | sed 's: :_:g'`
    mv "$file" $nfile
done
